### ISSUE TITLE
Run error when running Angular project

### ISSUE THREAD

**Issue by Y2zz** [aspnetboilerplate/module-zero-core-template#107]
Error message：
![tim 20170824134059](https://user-images.githubusercontent.com/252604/29651180-ef72111c-88d1-11e7-9d56-8a2359332306.png)

**Comment by ismcagdas** [comment]
Hi @Y2zz,

Which version of angular-cli do you use ?
Did you install npm dependencies using "npm install" or "yarn" ?

**Comment by Y2zz** [comment]
@ismcagdas 

@angular/cli: 1.3.1
node: 6.11.2
os: win32 x64
@angular/animations: 4.3.5
@angular/common: 4.3.5
@angular/compiler: 4.3.5
@angular/core: 4.3.5
@angular/forms: 4.3.5
@angular/http: 4.3.5
@angular/platform-browser: 4.3.5
@angular/platform-browser-dynamic: 4.3.5
@angular/router: 4.3.5
@angular/cli: 1.3.1
@angular/compiler-cli: 4.3.5

It has been used 'npm install'

**Comment by ismcagdas** [comment]
As I tried, angular-cli 1.3.1 had an important problem https://github.com/angular/angular-cli/issues/7341.
They have fixed it but we haven't upgraded our solution to it yet.

You can either tyr to use angular-cli v1.3.2 or you can use yarn to install npm dependencies until we upgrade templates to newer version of angular and angular-cli.

Thanks.

**Comment by Y2zz** [comment]
@ismcagdas OK, thanks

**Comment by Y2zz** [comment]
use “yarn”
