### ISSUE TITLE
this template has a error: when try Update-Database, the seed can't build

### ISSUE THREAD

**Issue by easyfast** [aspnetboilerplate/module-zero-core-template#109]
user commond Update-Database, the seeddata doest Insert. why?

**Comment by acjh** [comment]
See https://github.com/aspnetboilerplate/module-zero-core-template/issues/38#issuecomment-303942645:
>> Entity Framework Core does not support Seeding database on running migrations (you can search on the web).
As a current workaround, we do it when the application starts (https://github.com/aspnetboilerplate/module-zero-core-template/blob/master/aspnet-core/src/AbpCompanyName.AbpProjectName.EntityFrameworkCore/EntityFrameworkCore/AbpProjectNameEntityFrameworkModule.cs#L40).
