### ISSUE TITLE
Dynamically set LOCALE_ID provider

### ISSUE THREAD

**Issue by vdurante** [aspnetboilerplate/module-zero-core-template#114]
I noticed that, although localization works properly on the Angular application, setting LOCALE_ID is essential to work with features such as `DecimalPipe`. Example: `2.23`  vs. `2,23` in some countries.

I am unsure if this is already treated by ABP, but apparently in my application it is not. Adding the following to `providers` in `root.module.ts` did the trick in formatting decimals:

```js
{ provide: LOCALE_ID, useValue: 'pt-BR' }
```

But would be ideal do set it automatically based on selected language by the user. I may attempt doing it myself and make a pull request, but I might fail miserably.

Thanks!

**Comment by hikalkan** [comment]
I'm not sure if we know user's language at that stage. Should check it.
