### ISSUE TITLE
NSWAG ERROR

### ISSUE THREAD

**Issue by ismcagdas** [aspnetboilerplate/module-zero-core-template#115]
See https://github.com/aspnetboilerplate/aspnetboilerplate/issues/2519#issuecomment-330751550.

We also need to upgrade angular & angular-cli versions.

**Comment by wboebel** [comment]
I also tried to use the new template, re-generate the service-proxy using nswag, and reached the same error.  

Here are some manual updates I did to get it working in case you don't want to wait.

1) \src\shared\service-proxies\service-proxies.ts  (the nswag generated file)

  a) remove one of duplicated "import * as moment from 'moment';" lines, I removed the first one and kept the one near line 23

  b) add this line near the top with the others:   import 'rxjs/add/operator/finally';

2) You will have a few compile errors for various "create" modals when you do "npm start", create-user.component.ts for example among others.

For some reason it doesn't like this syntax where you set a field in the constructor:
   this.user = new CreateUserDto({ isActive: true });

If you replace it with this syntax, it will then work:
   this.user = new CreateUserDto();
    this.user.isActive = true;


There may be better ways to solve these issues, I'm very new to typescript, but these changes got it working for me.

**Comment by ismcagdas** [comment]
Thanks a lot @wboebel, as far as I know this is the only way.

**Comment by brunobertechini** [comment]
Hit the same problem here...sad :(

Is that related to new nswag version 11.6 ?

As a workaroung, I fixed it by doing:

```
yarn remove nswag
yarn add nswag@8.8.0 --dev
``` 

refreshing service proxies do not cause errors...

Are there any drawbacks on this ?

Any bug/strong reason to move to 11.6 nswag version? Or it was jsut a mindset of - lets update it ?

**Comment by hikalkan** [comment]
Closed by https://github.com/aspnetboilerplate/module-zero-core-template/pull/124
