### ISSUE TITLE
Error.cshtml gets stuck in 'Please wait...' loop

### ISSUE THREAD

**Issue by SteveArr** [aspnetboilerplate/module-zero-core-template#118]
By default, the .Net Core Module Zero MVC template needs every view to have a ViewBag.CurrentPageName = (enum) at the top of the page.  When this is not included, shared-layout.js throws an error and causes the page to get stuck with a swirling 'Please wait...' logo.   The error thrown is 'Unable to get property 'offsetTop' of undefined or null reference.'

Error.cshtml does not include the ViewBag.CurrentPageName entry at the top and thus triggers this bug.  Note that Error.cshtml itself is typically only called when enviroment is set to anything but Development.

In the attached screenshot, you can see I have commented out the ViewBag.CurrentPageName I added to fix the bug.  Toggling the comment on and off turns the bug on and off.

Tested in Chrome 61, IE 11 on Windows 10.

![bug](https://user-images.githubusercontent.com/11781083/30777968-a3044922-a07c-11e7-8563-09bb002ce017.PNG)

**Comment by acjh** [comment]
Fixed by #168
