### ISSUE TITLE
NSwag update breaks execution after dependency update

### ISSUE THREAD

**Issue by vdurante** [aspnetboilerplate/module-zero-core-template#123]
You should run refresh.bat and check the errors that show up.

Apparently, new NSwag changes the code generation and breaks the template's implementation in some parts, such as `create-tenant.component.ts`

```
[ts]
Argument of type '{ isActive: true; }' is not assignable to parameter of type 'ICreateTenantDto'.
  Property 'tenancyName' is missing in type '{ isActive: true; }'.
```

Apparently, it makes all properties required.

**Comment by hikalkan** [comment]
What's your current nswag version?

**Comment by vdurante** [comment]
commit `c664efd` updated npm dependencies, including NSWag to version `^11.6.1`. After running `refresh.bat`, a new version of `service-proxies.ts` is generated, causing following issues

![image](https://user-images.githubusercontent.com/5401232/31131488-b1a22592-a830-11e7-9db5-a2cb30b33a69.png)

```ts
/* tslint:disable */
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v11.8.3.0 (NJsonSchema v9.6.5.0 (Newtonsoft.Json v9.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------
// ReSharper disable InconsistentNaming
````

**Comment by vdurante** [comment]
Rolling back didn't work. I found a workaround, but it is not elegant. I will make a pull request with the changes.

**Comment by vdurante** [comment]
I understood what is going on. The setting `"generateConstructorInterface": true,` forces you to pass an object that implements the interface. This means that `this.tenant = new CreateTenantDto({isActive: true});` is not valid.

The solution is use the `init` method

`this.tenant = new CreateTenantDto().init({isActive: true});`

**Comment by ismcagdas** [comment]
Closed by @vdurante via https://github.com/aspnetboilerplate/module-zero-core-template/pull/124
