### ISSUE TITLE
Add template options to user IdentityServer4 by default 

### ISSUE THREAD

**Issue by badre429** [aspnetboilerplate/module-zero-core-template#132]
i fallowed the Abp docs to integrate IdentityServer 4 

please take a look at the startup file for web.host project 
[https://github.com/NgDZ/ngdz-aspnet/blob/master/src/Ngdz.Web.Host/Startup/Startup.cs](https://github.com/NgDZ/ngdz-aspnet/blob/master/src/Ngdz.Web.Host/Startup/Startup.cs)

when i try to generate at token i get  the exception 
` Unhandled exception: Abp.Domain.Uow.AbpDbConcurrencyException: Database operation expected to affect 1 row(s) but actually affected 0`

**Comment by hikalkan** [comment]
I created an issue about that (https://github.com/aspnetboilerplate/aspnetboilerplate/issues/2635). We will check & test documentation again if it works with the lates template.

We wanted to keep startup template simpler because most developers don't need IdentityServer4.

**Comment by yekalkan** [comment]
I have just updated the document. You can check it again.
