### ISSUE TITLE
Some issues with a freshly generated project from template.

### ISSUE THREAD

**Issue by fretje** [aspnetboilerplate/module-zero-core-template#136]
When a new project is created using the aspnetboilerplate website, there are some issues with the code which are kind of beyond the scope of this project, as they happen somewhere during code generation, after the source of this repository has been pulled. But I don't know where else to go with this, so here they are:

* All the .csproj files have everything on one line. This might have to do something with difference of newline characters on different platforms.
* The "abpProjectName" placeholder (camel case iso pascal case) is not replaced in AbpProjectNameTestModule and AbpProjectNameMigratorModule
* On the angular client side, the abp-project-name-template placeholder is not replaced in .angular-cli.json, app.e2e-spec.ts and package.json.
* build\build-mvc.ps1 and the whole docker\mvc folder is included when generating an angular project. I don't think these are necessary.

**Comment by hikalkan** [comment]
Thank you @fretje we will check them.
