### ISSUE TITLE
How to login as host when subdomain is enabled?

### ISSUE THREAD

**Issue by kibria06cse** [aspnetboilerplate/module-zero-core-template#144]
I have enabled multi tenancy in my project and also able to login via sub domain. But after enabling sub domain, I am not able to login without subdomain, no tenant selection option if I try to login with only localhost without subdomain. Also, login with localhost only on url, redirects to Host Dashboard.
My appsettings.json file in Web.MVC is like:
//"WebSiteRootAddress": "http://localhost:62114/",
"WebSiteRootAddress": "http://{TENANCY_NAME}.localhost:62114/",

What should I do?

**Comment by ismcagdas** [comment]
@kibria06cse it is designed like that. When there is no subdomain, system works on host context.
If you want to allow users to select tenant on login page, when subdomain is enabled, you need to modify login page to show tenant change link.
