### ISSUE TITLE
restore failed when use VS for Mac open the solution

### ISSUE THREAD

**Issue by evenlee** [aspnetboilerplate/module-zero-core-template#145]
I tried both this template and the template generated by https://aspnetboilerplate.com/Templates, the results are same, both cannot be restored successfully.

I chose AspNetCore 2.x and angular.

**Comment by hikalkan** [comment]
Edit every csproj file to remove conditional (``'$(TargetFramework)' == 'net461'``) ItemGroup and PropertyGroup tags and their inner tags, like:

https://github.com/aspnetboilerplate/module-zero-core-template/blob/master/aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Core/AbpCompanyName.AbpProjectName.Web.Core.csproj#L39-L45

I created an issue to remove these items on project creation: https://github.com/aspnetboilerplate/module-zero-core-template/issues/146

**Comment by evenlee** [comment]
thanks for your solution, and it works, but Migrator project failed.

**Comment by ismcagdas** [comment]
@evenlee can you share the error message for Migrator project ?

**Comment by evenlee** [comment]
[restore_log.txt](https://github.com/aspnetboilerplate/module-zero-core-template/files/1517466/restore_log.txt)
csproj:
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <AssetTargetFallback>$(AssetTargetFallback);portable-net45+win8+wp8+wpa81;</AssetTargetFallback>
    <AssemblyName>FishPosition.Migrator</AssemblyName>
    <OutputType>Exe</OutputType>
    <PackageId>FishPosition.Migrator</PackageId>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
  </PropertyGroup>

  <ItemGroup>
    <None Update="appsettings.json;log4net.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Abp.Castle.Log4Net" Version="3.2.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FishPosition.Core\FishPosition.Core.csproj" />
    <ProjectReference Include="..\FishPosition.EntityFrameworkCore\FishPosition.EntityFrameworkCore.csproj" />
  </ItemGroup>

</Project>
