### ISSUE TITLE
Remove '$(TargetFramework)' == 'net461' conditional tags on .net core project creation

### ISSUE THREAD

**Issue by hikalkan** [aspnetboilerplate/module-zero-core-template#146]
Otherwise it does not restore packages on Mac. See https://github.com/aspnetboilerplate/module-zero-core-template/issues/145

**Comment by alirizaadiyahsi** [comment]
This issue is resolved. We can close this issue after releasing aspnetboilerplate.com new version.

**Comment by ismcagdas** [comment]
Moved to a private repository
