### ISSUE TITLE
dotnet quit unexpectedly when run web.host project in VS for Mac

### ISSUE THREAD

**Issue by evenlee** [aspnetboilerplate/module-zero-core-template#147]
thanks the guide to remove net 461 label, I can restore all the projects now, and migrator project works fine. but when I try to run host.web project, get an error "dotnet quit unexpectedly", the debug point is:

````C#
//program.cs
return WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>()
                .Build();`
````

I also tried the this master code, results are same, but the project I created by vs for Mac works fine with the same program.cs.

<img width="527" alt="screen shot 2017-12-03 at 8 23 09 am" src="https://user-images.githubusercontent.com/4009476/33521107-4e39c00c-d803-11e7-95a2-2525f33890bc.png">

**Comment by hikalkan** [comment]
I suppose there should be some log about the problem.
But we will try that again to see the problem in our local.

**Comment by ismcagdas** [comment]
@evenlee can you try this https://github.com/aspnetboilerplate/aspnetboilerplate/issues/2717#issuecomment-348777116 ?

**Comment by evenlee** [comment]
@ismcagdas I tried, same result.

**Comment by ismcagdas** [comment]
@evenlee have you checked log files as @hikalkan suggested ?

**Comment by evenlee** [comment]
works now, I used try catch, and found the reason, a typo, my connection string ends by "}", but "}," is expected. sorry for the low level error.
