### ISSUE TITLE
User Role is removed on Submitting Edit User Modal (Although I don’t intend to..)

### ISSUE THREAD

**Issue by kayagultekin** [aspnetboilerplate/module-zero-core-template#148]
Using a fresh ASP.NET Core MVC & jQuery 3.4.0 template including module zero, submitting edit user modal even without making a change deletes the role of that user (only when you are at User Details tab, not if you submit while you are at User Roles tab), then redirects to login page.

**Comment by hikalkan** [comment]
Thank you. We will test & fix it.
