### ISSUE TITLE
Upgrade sweetalert to v2.0.8

### ISSUE THREAD

**Issue by acjh** [aspnetboilerplate/module-zero-core-template#149]
[ABP v3.2.0](https://github.com/aspnetboilerplate/aspnetboilerplate/releases/tag/v3.2.0) had a few **Breaking Changes**:

> [#2145](https://github.com/aspnetboilerplate/aspnetboilerplate/issues/2145) Upgrade to sweetalert v2.x. [Existing applications should upgrade sweetalert packages to v2.x.](https://github.com/aspnetboilerplate/aspnetboilerplate/pull/2694)

See also: https://stackoverflow.com/questions/47649563/promise-error-in-asp-net-boilerplate-core-2-0-angular-5-free-template

**Comment by hikalkan** [comment]
Thanks @acjh

**Comment by kelvinweiminn** [comment]
Thanks guise!
