### ISSUE TITLE
How to use multi tenant and web api with module-zero-core-template?

### ISSUE THREAD

**Issue by PMVDias** [aspnetboilerplate/module-zero-core-template#15]
Hi,

I have a new functionality to integrate in an old asp.net 4.5 application so I was thinking create a new web api project for this using your templates and consume it using angular on the old web application.
For this I was checking this article: https://www.codeproject.com/articles/1043326/a-multi-tenant-saas-application-with-asp-net-mvc-a but its using the old asp.net stuff.
Do you have any template or example with core, angular web api and multi tenant?

Regards,
Pedro

**Comment by hikalkan** [comment]
Hi,

Here, an example of consuming API from remote clients: http://www.aspnetboilerplate.com/Pages/Documents/Zero/Startup-Template-Core#token-based-authentication

If you are talking about dynamic Angularjs 1.x service proxies works for aspnet core, there is no such an integration. We are currently working on angular 2 + aspnet core 1.x template and we used [nswag](https://github.com/NSwag/NSwag) to generate typescript proxies. nswag has also generators for angularjs 1.x, you can try it.

**Comment by PMVDias** [comment]
Thanks for the documentation
