### ISSUE TITLE
User Register Behaviour

### ISSUE THREAD

**Issue by ryancyq** [aspnetboilerplate/module-zero-core-template#151]
I think the `Register` function in [`AccountAppService.cs`](https://github.com/aspnetboilerplate/module-zero-core-template/blame/master/aspnet-core/src/AbpCompanyName.AbpProjectName.Application/Authorization/Accounts/AccountAppService.cs#L43) & [`AccountController.cs`](https://github.com/aspnetboilerplate/module-zero-core-template/blob/master/aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/Controllers/AccountController.cs#L188) should be consistent in term of default value for `IsEmailConfirmed`

**Comment by hikalkan** [comment]
Will check this. Thanks.
