### ISSUE TITLE
User sensitive data being stored in audit log

### ISSUE THREAD

**Issue by ryancyq** [aspnetboilerplate/module-zero-core-template#152]
mentioned in https://github.com/aspnetboilerplate/aspnetboilerplate/issues/2765

In `AccountAppService`, the input [`RegisterInput.cs`](https://github.com/aspnetboilerplate/module-zero-core-template/blob/master/aspnet-core/src/AbpCompanyName.AbpProjectName.Application/Authorization/Accounts/Dto/RegisterInput.cs) has `DisableAuditing` attribute for `Password` field.

This should be applied to [`LoginViewModel.cs`](https://github.com/aspnetboilerplate/module-zero-core-template/blob/master/aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/Models/Account/LoginViewModel.cs) & [`RegisterViewModel.cs`](https://github.com/aspnetboilerplate/module-zero-core-template/blob/master/aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/Models/Account/RegisterViewModel.cs) as well

**Comment by ismcagdas** [comment]
Thanks @ryancyq
