### ISSUE TITLE
I want to change default route but it wont login me into to angular app if i do

### ISSUE THREAD

**Issue by smooney123** [aspnetboilerplate/module-zero-core-template#162]
````C#
using System.Web.Http;
using System.Web.Mvc;
using System.Web.Routing;

namespace Test.Web
{
    public static class RouteConfig
    {
        public static void RegisterRoutes(RouteCollection routes)
        {
            routes.IgnoreRoute("{resource}.axd/{*pathInfo}");

            //ASP.NET Web API Route Config
            routes.MapHttpRoute(
                name: "DefaultApi",
                routeTemplate: "api/{controller}/{id}",
                defaults: new { id = RouteParameter.Optional }
                );

            routes.MapRoute(
                name: "Default",
                url: "{controller}/{action}/{id}",
                defaults: new { controller = "Secure", action = "Index", id = UrlParameter.Optional }
            );

           /* // Show a 404 error page for anything else.
            routes.MapRoute("Error", "{*url}",
                new { controller = "Error", action = "404" }
            );*/

        }
    }
}
````

Hi,

I want the default route to be home/index, however when i change this i can no longer login to the angular application. Why is this?

**Comment by hikalkan** [comment]
Is that Asp.Net Core or AspNet MVC 5.x? This repository is for core.

**Comment by smooney123** [comment]
Mvc5

**Comment by hikalkan** [comment]
Startup template already has Home/Index route as default (https://github.com/aspnetboilerplate/module-zero-template/blob/master/src/AbpCompanyName.AbpProjectName.WebSpaAngular/App_Start/RouteConfig.cs).

And it redirects to the angularjs app's layout view:

https://github.com/aspnetboilerplate/module-zero-template/blob/master/src/AbpCompanyName.AbpProjectName.WebSpaAngular/Controllers/HomeController.cs#L9-L12

As I can see, you changed "Home" to "Secure" in your route. So, I didn't understand why changing back to "Home" causes problem. Maybe your Home/Index does not return angularjs app's view.

**Comment by smooney123** [comment]
You are right. I am using my home controller for other things.

I want to change because the redirect is making loading the website slow.

www.drumfights.co.uk

**Comment by acjh** [comment]
@smooney123 Do you mean you "want the default route to be ~home/index~ Secure/Index" instead?

**Comment by smooney123** [comment]
No, i mean i want my default route to be home/index but when i login to the application it is redirecting me back to home/index, where i want it to redirect me to secure/index

**Comment by acjh** [comment]
You could have said that in the first place. Set `returnUrl` in the `Login` method of [`AccountController`](https://github.com/aspnetboilerplate/module-zero-template/blob/46e610ac56effdf216e4aa9625b23c32b4ed9183/src/AbpCompanyName.AbpProjectName.WebSpaAngular/Controllers/AccountController.cs#L116):
```c#
if (string.IsNullOrWhiteSpace(returnUrl))
{
    returnUrl = Request.ApplicationPath; // Change this line
}
```

**Comment by smooney123** [comment]
how would that help?

what if the return url is something different?

**Comment by acjh** [comment]
Try it.

**Comment by smooney123** [comment]
thanks
