### ISSUE TITLE
bootstrap, jquery version for MPA Template

### ISSUE THREAD

**Issue by ryancyq** [aspnetboilerplate/module-zero-core-template#166]
Consider to update [bower.json](https://github.com/aspnetboilerplate/module-zero-core-template/blob/master/aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/bower.json)
`bootstrap` 3.3.6 -> 3.3.7
`jquery`  2.2.0 -> 3.1.1

**Comment by ismcagdas** [comment]
Thanks @ryancyq we will do.

**Comment by ismcagdas** [comment]
closed via https://github.com/aspnetboilerplate/module-zero-core-template/pull/172
