### ISSUE TITLE
After update to 1.5.1 and VS 2017 warring 

### ISSUE THREAD

**Issue by Klainer** [aspnetboilerplate/module-zero-core-template#17]
Hi after update project to VS 2017 nad ABP 1.5.1 I have this warring aftrer build:

Consider app.config remapping of assembly "System.Security.Cryptography.X509Certificates, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" from Version "4.0.0.0" [] to Version "4.1.1.0" [C:\Users\Martin\.nuget\packages\system.security.cryptography.x509certificates\4.3.0\ref\net461\System.Security.Cryptography.X509Certificates.dll] to solve conflict and get rid of warning.

Does anyone know how to get ride of this warning ? Thanks!

**Comment by hikalkan** [comment]
We haven't using this packages, but it should be general situation about .net & Visual studio. Have you searched it on the web?

**Comment by Klainer** [comment]
Hi I looked to appveyor history of build and you have similiar warring on line 277: [https://ci.appveyor.com/project/hikalkan/module-zero/build/1.5.1-beta226](LINK)

I tried search, found solution do not help me yet, I will keep trying to search....

**Comment by hikalkan** [comment]
Thank you. Please inform us if you find something. We are also still learning and trying to understand VS2017 changes (which are not documented).

**Comment by Klainer** [comment]
Hi I have no luck yet. It seems that in some NUGET packages we have different versions of the same assembly, but I do not know how to find what concerete dll cause this mishmash..

**Comment by hikalkan** [comment]
Yes, but still it works properly. We will inform if we can find something. It has less priority for us since it's working :)
