### ISSUE TITLE
Hide connection string from migrator output

### ISSUE THREAD

**Issue by gokhansengun** [aspnetboilerplate/module-zero-core-template#175]
Running the migrator outputs the connection string configured with it like below. The output includes password when `Trusted_Connection` is `False` which is always the case for `MySql` and `Postgres`.

```
2018-01-27 23:03:42 | Host database: Server=localhost; Database=AbpProjectNameDb; Trusted_Connection=True;
2018-01-27 23:03:42 | HOST database migration started...
```

This is a security risk when the app runs in production. Best practices tell to keep the secrets in a trusted place and render configuration files in the running app or container where authorized people have access. Logs are expected to include no sensitive information as they are human readable and is expected to be looked at by operation personnel.

This issue is to discuss what to do, options seem to be:

- Remove the log
- Show it only when `skipConnVerification` is `false` where human intervention is needed.

**Comment by hikalkan** [comment]
Thanks @gokhansengun 

We write the conn string to make we sure that we are migrating the correct database. However, this may be a security problem. We will think on that.

**Comment by gokhansengun** [comment]
Agreed, thats why one option I suggested is to hide it when `skipConnVerification` is `true`( it skips user confirmation). In this case, it is already too late if a wrong database is being migrated ;-)
