### ISSUE TITLE
I've got error due optimization phase when use command ng build --prod

### ISSUE THREAD

**Issue by SergeyLimonov** [aspnetboilerplate/module-zero-core-template#176]
Hi,

I've created a project using **ASP.NET Boilerplate Core + Angular** templete v3.4.1.

Without any changes when I try to use command **ng build --prod** I've got error due optimization phase:
`
C:\Projects\demo\angular>ng build --prod
 10% building modules 8/14 modules 6 active ...\bootstrap\dist\css\bootstrap.min.cssNode#moveTo was deprecated. Use Container 94% asset optimization(node:26304) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): SyntaxError: Unexpected token: punc ({)
`

This command completes without errors for same project from template v3.4.0. So we can't use it for production builds.

Please help us fix this issue.
Thanks!

**Comment by exiled78** [comment]
You guys are awesome!

**Comment by SergeyLimonov** [comment]
Hi,
This issue is closed but it is not fixed for me sorry.
Now I've checked out master branch from this repository and see described error again.
`C:\Projects\ThirdParty\module-zero-core-template\angular>ng build --prod
 11% building modules 11/14 modules 3 active ...\bootstrap\dist\css\bootstrap.min.cssNode#moveTo was deprecated. Use Contain 94% asset optimization(node:7688) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): SyntaxError: Unexpected token: punc ({)`

**Comment by ismcagdas** [comment]
@SergeyLimonov have you removed your node_modules folder and tried to install npm dependencies again ?

If you did this, can you share your angular-cli version as well ?

**Comment by SergeyLimonov** [comment]
I've tryed to investigate this issue and have removed all signalr usage code. And it this issue is no more appears. I think signalr is not ready for production yet.

**Comment by SergeyLimonov** [comment]
@ismcagdas I've got error on clean sources that I've checked out today.

**Comment by SergeyLimonov** [comment]
After remove signalr usage code I've tried to restore changes line by line and I've found that restoring following change breaks **ng build --prod**
`diff --git a/angular/.angular-cli.json b/angular/.angular-cli.json
index fae8146..f213caf 100644
--- a/angular/.angular-cli.json
+++ b/angular/.angular-cli.json
@@ -48,7 +48,6 @@
                 "../node_modules/lodash/lodash.min.js",
                 "../node_modules/moment/min/moment.min.js",
                 "../node_modules/signalr/jquery.signalR.js",
-                "../node_modules/@aspnet/signalr-client/dist/browser/signalr-client.min.js",
                 "../node_modules/toastr/toastr.js",
                 "../node_modules/sweetalert/dist/sweetalert.min.js",
                 "../node_modules/block-ui/jquery.blockUI.js",
`

**Comment by SergeyLimonov** [comment]
The following change fix **ng build --prod** but I don't know how it can affect the work of SignalR in ABP because I have not actually use this functionality in my project yet.
![image](https://user-images.githubusercontent.com/12935645/35592034-dc56953a-061c-11e8-9d5c-bf9c4005bea1.png)

**Comment by acjh** [comment]
It will not affect how SignalR works.

**Comment by ismcagdas** [comment]
@SergeyLimonov thanks a lot for finding this.  @acjh should we make the same change ? What do you think ?

**Comment by acjh** [comment]
I couldn't reproduce this on `master` branch.

@SergeyLimonov Can you check if https://github.com/aspnetboilerplate/module-zero-core-template/commit/1f61fd5cca712a1ba19b37f59b7651578c5527ea works?

```diff
// angular/.angular-cli.json
- "../node_modules/@aspnet/signalr-client/dist/browser/signalr-client.min.js",
+ "../node_modules/@aspnet/signalr/dist/browser/signalr.min.js",

// angular/package.json
- "@aspnet/signalr-client": "1.0.0-preview1-27891",
+ "@aspnet/signalr": "1.0.0-preview1-28189",

**Comment by SergeyLimonov** [comment]
@acjh I can't see this commit. May be it belongs to a hidden branch?

But I've tried to make manually changes on my side.

![image](https://user-images.githubusercontent.com/12935645/35619112-022d9814-068e-11e8-9323-d2f8ab4b84a4.png)

It seems to be OK but I don't see changes of **yarn.lock** in your commit. Is it OK? As I understood it should be modified and committed too.

**Comment by acjh** [comment]
Thanks for the verification! I will modify and commit **yarn.lock** too.
