### ISSUE TITLE
Has there been any initiative to migrate the Angular UI to Metronic v5?

### ISSUE THREAD

**Issue by tangoda** [aspnetboilerplate/module-zero-core-template#178]
Hey guys!

Has there been any initiative to migrate the UI to Metronic v5?

If not, I'd like to know if anyone is willing to do this with me.

P.S. Sorry for my English.

**Comment by acjh** [comment]
Metronic is a paid product, so it may be unsuitable for this open-source template.

Consider [ASP.NET Zero](https://aspnetzero.com), which comes with Metronic license and great integration.

**Comment by tangoda** [comment]
ASP.NET Zero is great, but too expensive for small projects. :(

**Comment by ismcagdas** [comment]
@tangoda as @acjh said, Metronic is a paid product and we cannot use it in our free templates.
