### ISSUE TITLE
Cannot revert EF migration after ABP v3.4 upgrade

### ISSUE THREAD

**Issue by acjh** [aspnetboilerplate/module-zero-core-template#182]
Follows aspnetboilerplate/aspnetboilerplate#2841 (Abp.Zero fixes for Abp.ZeroCore.EntityFramework)
Follows aspnetboilerplate/aspnetboilerplate#2835 (Entity History feature)

---

It seems the migration caused by aspnetboilerplate/aspnetboilerplate#2841 cannot be rolled back with:

```shell
dotnet ef database update Upgraded_To_Abp_v2.2.2
```

> The index 'IX_AbpUserClaims_TenantId_ClaimType' is dependent on column 'ClaimType'.
ALTER TABLE ALTER COLUMN ClaimType failed because one or more objects access this column.
>
> The index 'IX_AbpUserAccounts_UserName' is dependent on column 'UserName'.
The index 'IX_AbpUserAccounts_TenantId_UserName' is dependent on column 'UserName'.
ALTER TABLE ALTER COLUMN UserName failed because one or more objects access this column.
>
> The index 'IX_AbpUserAccounts_EmailAddress' is dependent on column 'EmailAddress'.
The index 'IX_AbpUserAccounts_TenantId_EmailAddress' is dependent on column 'EmailAddress'.
ALTER TABLE ALTER COLUMN EmailAddress failed because one or more objects access this column.
>
> The index 'IX_AbpRoleClaims_TenantId_ClaimType' is dependent on column 'ClaimType'.
ALTER TABLE ALTER COLUMN ClaimType failed because one or more objects access this column.

😕

**Comment by alirizaadiyahsi** [comment]
Hi @acjh , I added migration and updated database with no error. Is there something I missed with your comments?

**Comment by acjh** [comment]
I mean that it can't be reverted (the "Down" doesn't work).

![](https://user-images.githubusercontent.com/14091939/35674099-8c7dd11e-077e-11e8-9c7b-2eb2f680bed2.png)

**Comment by ismcagdas** [comment]
@acjh I couldn't be sure if the problem is related with https://github.com/aspnetboilerplate/aspnetboilerplate/pull/2841 or not. The index "IX_AbpUserClaims_TenantId_ClaimType" is created in the initial script.

Have you find a good way to solve this problem ?

**Comment by acjh** [comment]
Hmm, unfortunately not.
