### ISSUE TITLE
Guide explaining the front end scaffolding

### ISSUE THREAD

**Issue by Donistivanov** [aspnetboilerplate/module-zero-core-template#183]
I am trying to work through the front end code and to make changes slowly, but I think it would be very useful to read a guide on a sample workflow and the features that are present in the SPA. 

I hope this is not out of scope for ABP!

**Comment by hikalkan** [comment]
We will create an article for this template that will explain how to add new features step by step. I'm closing this issue since it's tracked internally by our team.
