### ISSUE TITLE
can't install "@aspnet/signalr" 

### ISSUE THREAD

**Issue by mokey1** [aspnetboilerplate/module-zero-core-template#188]
i added  `"@aspnet/signalr": "1.0.0-preview1-28189"` to my package.json and run npm install , but get this error in my console:
`Not found : @aspnet/signalr`

**Comment by ismcagdas** [comment]
Have you created the ".npmrc" file as mentioned here https://github.com/aspnet/SignalR#packages ?

**Comment by mokey1** [comment]
@ismcagdas thanks, its install successful
