### ISSUE TITLE
Swashbuckle generates list of params instead of an input box expecting a model in a controller

### ISSUE THREAD

**Issue by Donistivanov** [aspnetboilerplate/module-zero-core-template#189]
This later affects me because when I run refresh.bat for nswag on the frontend, I do not get a class definition for the dto made, but a service method that takes in many parameters.

I do not know if this is somehow intended, but it might be a nice QoL.

My controller inherts from xxxControllerBase

and I have
```
        [HttpPost]
        public TestDto Hello(TestDto input)
        {
            return input;
        }

        public class TestDto
        {
            public string To { get; set; }
            public string From { get; set; }
            public string Message { get; set; }
        }
```

and I see on the swagger ui:
![image](https://user-images.githubusercontent.com/12190565/36454448-ecc02744-1669-11e8-850b-19f68b3bd1cd.png)

I was expecting to see something like:
![image](https://user-images.githubusercontent.com/12190565/36454509-354ad068-166a-11e8-8289-4f79a1a4e8be.png)

**Comment by ismcagdas** [comment]
@Donistivanov change your action like below:

```
[HttpPost]
public TestDto Hello([FromBody] TestDto input)
{
	return input;
}
```

**Comment by Donistivanov** [comment]
Thanks for this!
