### ISSUE TITLE
Request for a minimum template

### ISSUE THREAD

**Issue by dedlfix** [aspnetboilerplate/module-zero-core-template#192]
I want to suggest to create an (additional) Angular template that only includes what is really needed. The current template includes a sample dashboard and a lot of dependencies that are only needed for things in this dashboard but not necessarily in other projects. In my opinion this minimum template should only contain things that are needed for all the ABP functionality and simple bootstrap pages (even without material design, but ngx-bootstrap is fine, because an Angular project without it is cumbersome) for the login, register, user, role and tenant management pages.

**Comment by ismcagdas** [comment]
@dedlfix I think you also want us to remove current theme (BSB Admin), right ?

**Comment by dedlfix** [comment]
I guess the BSB Admin falls under "not necessarily needed in other projects". For your own projects based on ABP you probably want to use your own design (corporate identity) so that nearly bare HTML to build on seems to be better than to figure out what you all need to change. Even Bootstrap is questionable for this purpose, but it can be a compromise between ugly nakedness of html and a full-blown "don't need it for me".

An alternative could be that in the [Startup Templates page](https://aspnetboilerplate.com/Templates) one can uncheck "Include login, register, user, role and tenant management pages." but not lose the ability to select Angular.

**Comment by hikalkan** [comment]
Basic startup template has no angular version yet. We had an issue to follow it, but not worked on yet since there was not much request for it:
I suppose you want this: https://github.com/aspnetboilerplate/aspnet-core-template/issues/7

I'm closing this issue since there is already an issue for it.
