### ISSUE TITLE
lodash needed?

### ISSUE THREAD

**Issue by dedlfix** [aspnetboilerplate/module-zero-core-template#193]
The lodash package is imported 7 times but is only used 2 times. And these two usages could be replaced with vanilla javascript Array.prototype.filter() (browser compatibility: min. IE9).

with lodash:
`        this.languages = _.filter(this.localization.languages, l => !l.isDisabled);`
without lodash:
`        this.languages = this.localization.languages.filter(l => !l.isDisabled);`

Or did I miss something?

**Comment by ismcagdas** [comment]
@dedlfix we can remove not used imports but lodash is very handy for such kind of javascript operations.

**Comment by dedlfix** [comment]
Might be for other operations that don't have a vanilla pendant. But what is the benefit in case of the filter, that doesn't do anything other than the vanilla filter?

**Comment by hikalkan** [comment]
Added lodash to the solution since it's widely used and good to come with a new application template.
I agree that we could use the native one, but what matters after we imported lodash in the solution. In addition it will work in IE8 too.

**Comment by dedlfix** [comment]
Ok, on the other hand browser compatibility is a task for the polyfills.

**Comment by ismcagdas** [comment]
We decided to keep lodash but removed not used imports.
