### ISSUE TITLE
Error deploying to Azure

### ISSUE THREAD

**Issue by ahmed-sherien** [aspnetboilerplate/module-zero-core-template#197]
I'm using the asp.net core 2 + angular 5 template, I'm tryng to deploy the web.host to azure app service using bitbucket deployment option but it fails and gives me this error:
```
Error parsing the nested project section in solution file. A project with the GUID "{0FA75A5B-AB83-4FD0-B545-279774C01E87}" is listed as being nested under project "{AFAA0841-BD93-466F-B8F4-FB4EEC86F1FC}", but does not exist in the solution.
```

**Comment by alirizaadiyahsi** [comment]
Hi @ahmed-sherien, what is your product version? Is your project merged (one solution for host and angular)?

**Comment by ahmed-sherien** [comment]
@alirizaadiyahsi project version is v5.0.0, and nope they are 2 separate solutions

**Comment by ismcagdas** [comment]
@ahmed-sherien probably there was a problem with project generation.
Can you open your .sln file and remove the lines containst "0FA75A5B-AB83-4FD0-B545-279774C01E87".

**Comment by ismcagdas** [comment]
@ahmed-sherien I think you are using AspNet Zero, right ?

**Comment by ahmed-sherien** [comment]
@ismcagdas exactly, sorry I forgot to mention that.

**Comment by ismcagdas** [comment]
@ahmed-sherien then please use https://forum.aspnetboilerplate.com/viewforum.php?f=5 for your technical problems.
