### ISSUE TITLE
Web Mvc Project Localization

### ISSUE THREAD

**Issue by ryancyq** [aspnetboilerplate/module-zero-core-template#201]
I was wondering if it is a good practice to have embedded `Localization`  solely for `Web.Mvc` in the startup template.

For example, we can have the same `LocalizationConfigurer` which is currently in `AbpProjectNameCoreModule` to be in `AbpProjectNameWebMvcModule` as well

**Comment by ismcagdas** [comment]
@ryancyq I think using localization per platform is the best option. So, I think your suggestion is a good practice. But, placing localization in core project is handy as well, that is why we did it like this in our templates.

**Comment by ryancyq** [comment]
@ismcagdas i see. However, when I read up on the discussion at https://github.com/aspnetboilerplate/aspnetboilerplate/issues/3052. 

Seems that it makes more sense to have the localization separated for application layer and presentation. 

E.g application layer uses localization in application layer and `Core.Shared`, presentation layer uses localization in presentation layer and `Core.Shared`

**Comment by ismcagdas** [comment]
@ryancyq I wanted to say same thing but couldn't explain it correctly :).

**Comment by ismcagdas** [comment]
We will keep the templates this way to make it simpler.
