### ISSUE TITLE
Web Mvc Project AccountController namespace

### ISSUE THREAD

**Issue by ryancyq** [aspnetboilerplate/module-zero-core-template#202]
Currently, Account Controller in `Web.Mvc` project sits under the namespace of `AbpCompanyName.AbpProjectName.Web.Controllers`. 

Was having the thoughts that should `AccountController` namespace be consistent with `AccountAppService`? In this case, allowing more flexibilities to developer who might want to use `AccountController` in the default `Controllers` namespace.

For example, change to `AbpCompanyName.AbpProjectName.Web.Controllers.Authorization`.

**Comment by hikalkan** [comment]
We wanted to follow ASP.NET MVC's conventions to place controllers, views and models under folders.
Otherwise, you're true, we don't like to define namespaces by class type (like Controllers, Enums, Entities, Services... etc.).

**Comment by ryancyq** [comment]
I see. I came across this when deciding if I should follow best practices vs ease of template upgrade. Seems that best practices makes more sense now.

Thanks
