### ISSUE TITLE
In UnitTest project, seed db methods are run twice

### ISSUE THREAD

**Issue by chrsas** [aspnetboilerplate/module-zero-core-template#211]
In UnitTest project, `InitialHostDbBuilder`, `DefaultTenantBuilder` and `TenantRoleAndUserBuilder` are run twice. First time is in `EntityFrameworkCoreMolule.SeedBb`, second time is in TestBase's constructor, so I think these three calls should be removed from TestBase's constructor.

**Comment by ismcagdas** [comment]
@chrsas the correct usage is to call seed in the constructor of TestBase class. In this way, for each test all the database will be filled with same seed data and tests will not affect each other.
