### ISSUE TITLE
Web MVC / SweetAlert Localization

### ISSUE THREAD

**Issue by jonassix** [aspnetboilerplate/module-zero-core-template#212]
When deleting a tenant or user a SweetAlert is invoked.
However that message is not localized. 
See screenshot
![image](https://user-images.githubusercontent.com/22755764/37828936-6f96603e-2e9d-11e8-89b7-6baeea1591fb.png)

My resource file has 
    text name="Cancel" value="Annuleer" 
    text name="Yes" value="Ja" 

i have found the same issue with the angular template. However someone already provided a fix for that.

**Comment by ismcagdas** [comment]
@jonassix is your xml file marked as embedded resource ?

**Comment by jonassix** [comment]
if i right click on it, on build action it has Embedded resource

**Comment by ismcagdas** [comment]
@jonassix can you share it's content and the name of the xml file you have created ?

**Comment by jonassix** [comment]
Well i haven't created the xml. it's the template itself. 
[PaymentPortal.txt](https://github.com/aspnetboilerplate/module-zero-core-template/files/1841619/PaymentPortal.txt)
[PaymentPortal-nl.txt](https://github.com/aspnetboilerplate/module-zero-core-template/files/1841620/PaymentPortal-nl.txt)

See files in attachment. i changed the extension name to txt so i could upload it.

Do note,  i've upgraded abp from previous version through nuget. i downloaded the template right before the new version.

**Comment by ismcagdas** [comment]
@jonassix thanks for sharing the files.

The messages on sweet-alert are retrieved from a different localization source which is AbpWeb, see https://github.com/aspnetboilerplate/module-zero-core-template/blob/master/aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/wwwroot/lib/abp-web-resources/Abp/Framework/scripts/libs/abp.sweet-alert.js#L103.

So, you need to add a new xml file for AbpWeb localization source and use it as exmplained in here
https://aspnetboilerplate.com/Pages/Documents/Localization#extending-localization-sources.

Here is the file for english translations https://github.com/aspnetboilerplate/aspnetboilerplate/blob/dev/src/Abp.Web.Common/Web/Localization/AbpWebXmlSource/AbpWeb.xml, so you can use it to create your **AbpWeb-nl.xml** file.

**Comment by ismcagdas** [comment]
@jonassix you can also share your translation by sending a PR to ABP framework 😄 .

**Comment by jonassix** [comment]
oh, that makes sense. When i get around to it. I'll share the translation.
Will be dutch and french.
