### ISSUE TITLE
Missing Web.Mvc Project From ASP.NET Core SPA Template

### ISSUE THREAD

**Issue by mhellem** [aspnetboilerplate/module-zero-core-template#215]
After downloading the ASP.NET Core SPA template, it appears that the Read Documentation link takes you to the wrong topic - it goes to the multi-page template topic.

**Comment by ismcagdas** [comment]
@mhellem Web.Mvc project is generated when you download ASP.NET Core Multi Page Application template.

If you want to use SPA, then you will have Web.Host for APIs and a seperate Angular app for the client side.
