### ISSUE TITLE
CreatorUserId not be set

### ISSUE THREAD

**Issue by rcl4444** [aspnetboilerplate/module-zero-core-template#219]
I create a service inherit AsyncCrudAppService. when I invoke create api, CreatorUserId not be set.
I login with the default tenants.
It's what I missed, or I should do it myself
![image](https://user-images.githubusercontent.com/19640490/38776959-5b60f894-40d2-11e8-94ae-7713c78ef259.png)

**Comment by acjh** [comment]
How is your entity defined?

**Comment by rcl4444** [comment]
hi acjh:
it inherit FullAuditedEntity
![image](https://user-images.githubusercontent.com/19640490/38777049-0e5e8474-40d4-11e8-8271-4eac01fe83e3.png)

**Comment by Liu233w** [comment]
hi, I think that you should inherit the interface `IFullAudited` too

**Comment by acjh** [comment]
Is the `TenantId` set correctly?

**Comment by rcl4444** [comment]
hi acjh:
TenantId Normal work,

**Comment by rcl4444** [comment]
hi liu233w:
I inherit the interface IFullAudited too,but is do not work

**Comment by rcl4444** [comment]
default abpsession is NullAbpSession.Instance.
![image](https://user-images.githubusercontent.com/19640490/38777458-0ac4763c-40db-11e8-8181-7ac1eec66c8b.png)
![image](https://user-images.githubusercontent.com/19640490/38777601-6030fe40-40dd-11e8-80ea-974269afb97c.png)
it cause <code>TenantId</code> have value,but <code>CreatorUserId</code> not be set, and what can i do?

**Comment by acjh** [comment]
That's not the cause.

**Comment by rcl4444** [comment]
@acjh 
I change the /api/TokenAuth/Authenticate, add the AbpClaimTypes.TenantId
![image](https://user-images.githubusercontent.com/19640490/38921248-da375792-4327-11e8-9cf9-51c1aa4edcc1.png)
This is normal
![image](https://user-images.githubusercontent.com/19640490/38921589-c29a98b4-4328-11e8-9fa6-7989b56931de.png)
and i have a problem,In terms of design, is the user unique based on the tenant, then is there a problem with the login implementation logic? The default tenant userid should be 2

**Comment by acjh** [comment]
Can you set a breakpoint and show the values of `TenantId` and `UserId` in `AbpSession`?

**Comment by rcl4444** [comment]
@acjh 
i clear the cookie,and login in
![image](https://user-images.githubusercontent.com/19640490/38964956-6c4e6ba0-43ac-11e8-8629-5c88e8fa417b.png)

**Comment by rcl4444** [comment]
this is the <code>AbpSession</code>
![image](https://user-images.githubusercontent.com/19640490/38965084-1503effe-43ad-11e8-8d8a-da0b0aaa7caf.png)

**Comment by ismcagdas** [comment]
@rcl4444 can you share the data in yoru AbpUsers table as well ?

**Comment by rcl4444** [comment]
@ismcagdas 
I change the table Prefix,so my AbpUsers is users;
![image](https://user-images.githubusercontent.com/19640490/38974057-2a316af4-43db-11e8-952a-d1fb1dee2df6.png)
![image](https://user-images.githubusercontent.com/19640490/38974113-6ec93c0a-43db-11e8-8cd2-623cd5bddb4d.png)

**Comment by rcl4444** [comment]
I find my problem,I override the OnModelCreating,but I do not invoke the base. OnModelCreating
