### ISSUE TITLE
version 4 issue 

### ISSUE THREAD

**Issue by MoatazGitHub** [aspnetboilerplate/module-zero-core-template#220]
Hello I'm using
  "name": "abp-zero-template",
  "version": "4.0.0",
I am facing this problem
![image](https://user-images.githubusercontent.com/17373050/38973947-61642224-43a8-11e8-972f-6ae986f24c6e.png)

```
 Class 'AbpHttp' incorrectly extends base class 'Http'.
  Type '(url: string | Request, options?: RequestOptionsArgs) => Observable<Response>' is not assignable to type '(url: string | Request, options?: RequestOptionsArgs) => Observable<Response>'. Two different types with this name exist, but they are unrelated.
      Type 'Observable<Response>' is not assignable to type 'Observable<Response>'. Two different types with this name exist, but they are unrelated.
        Types of property 'source' are incompatible.
          Type 'Observable<any>' is not assignable to type 'Observable<any>'. Two different types with this name exist, but they are unrelated.
            Property 'operator' is protected but type 'Observable<T>' is not a class derived from 'Observable<T>'.

```

Please HELP !!

**Comment by ismcagdas** [comment]
@MoatazGitHub have you updated abp-ng2-module recently ? It's latest version requires angular5 as well.

**Comment by MoatazGitHub** [comment]
@ismcagdas thanks for fast reply but I'm not sure.
Could you provide my with working version 4 packages.json file where all packages are compatible ???

**Comment by ismcagdas** [comment]
@MoatazGitHub can you share your packages.config ? By the way, if you remove node_modules folder and install the packages using [yarn](https://yarnpkg.com/) this problem might be fixed.

**Comment by MoatazGitHub** [comment]
@ismcagdas  Here is package.json file
{
  "name": "abp-zero-template",
  "version": "4.0.0",
  "license": "MIT",
  "angular-cli": {},
  "scripts": {
    "build:prod":"ng build --prod",
    "ng": "ng",
    "start": "ng serve --host 0.0.0.0 --port 4200",
    "hmr": "ng serve --host 0.0.0.0 --port 4200 4201 --hmr -e=hmr",
    "test": "ng test",
    "pree2e": "webdriver-manager update --standalone false --gecko false",
    "e2e": "protractor" 
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^4.3.1",
    "@angular/common": "^4.3.1",
    "@angular/compiler": "^4.3.1",
    "@angular/core": "^4.3.1",
    "@angular/forms": "^4.3.1",
    "@angular/http": "^4.3.1",
    "@angular/platform-browser": "^4.3.1",
    "@angular/platform-browser-dynamic": "^4.3.1",
    "@angular/router": "^4.3.1",
    "@types/bootstrap": "^3.3.33",
    "@types/jasmine": "^2.5.47",
    "@types/jquery": "^2.0.41",
    "@types/jquery.blockui": "0.0.27",
    "@types/jstree": "^3.3.34",
    "@types/lodash": "^4.14.62",
    "@types/moment": "^2.13.0",
    "@types/moment-timezone": "^0.2.34",
    "@types/node": "^6.0.42",
    "@types/signalr": "^2.2.33",
    "@types/tether": "^1.4.2",
    "@types/toastr": "^2.1.33",
    "abp-ng2-module": "^1.2.0",
    "abp-web-resources": "^2.2.1",
    "angular2-counto": "^1.2.3",
    "block-ui": "^2.70.1",
    "bootstrap": "^3.3.7",
    "bootstrap-daterangepicker": "^2.1.25",
    "bootstrap-select": "^1.12.2",
    "bootstrap-switch": "^3.3.4",
    "codelyzer": "^2.1.1",
    "core-js": "^2.4.1",
    "datamaps": "^0.5.8",
    "eonasdan-bootstrap-datetimepicker": "^4.17.47",
    "famfamfam-flags": "^1.0.0",
    "flot": "^0.8.0-alpha",
    "font-awesome": "^4.7.0",
    "jasmine-spec-reporter": "^3.3.0",
    "jquery": "^3.1.1",
    "jquery-migrate": "^3.0.0",
    "jquery-slimscroll": "^1.3.8",
    "jquery-sparkline": "^2.4.0",
    "jquery.flot.tooltip": "^0.9.0",
    "jquery.inputmask": "^3.3.4",
    "jquery.uniform": "^4.2.0",
    "jqueryui": "^1.11.1",
    "js-cookie": "^2.1.4",
    "jstree": "^3.3.4",
    "karma": "^1.6.0",
    "localforage": "^1.5.0",
    "lodash": "^4.17.4",
    "moment": "^2.18.1",
    "moment-timezone": "^0.5.13",
    "morris.js": "^0.5.0",
    "ng-recaptcha": "^2.0.2",
    "ng2-file-upload": "^1.2.1",
    "ng2-opd-popup": "^1.1.21",
    "ng2modules-easypiechart": "^0.0.4",
    "ng2modules-flot": "^0.0.1",
    "ngx-bootstrap": "^1.8.0",
    "primeng": "^4.1.1",
    "push.js": "0.0.12",
    "raphael": "^2.2.7",
    "rtl-detect": "^1.0.0",
    "rxjs": "^5.4.2",
    "signalr": "^2.2.1",
    "simple-line-icons": "^2.4.1",
    "spin.js": "^2.3.2",
    "sweetalert": "^1.1.3",
    "tether": "^1.4.0",
    "timeago": "^1.6.1",
    "toastr": "^2.1.2",
    "ts-helpers": "^1.1.2",
    "ts-node": "~3.2.0",
    "typescript": "2.4",
    "waypoints": "^4.0.1",
    "zone.js": "0.8.7"
  },
  "devDependencies": {
    "@angular/cli": "1.2.4",
    "@angular/compiler-cli": "^4.3.1",
    "@angularclass/hmr": "^2.1.3",
    "@angularclass/hmr-loader": "^3.0.4",
    "@types/grecaptcha": "^2.0.31",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/morris.js": "^0.5.6",
    "@types/node": "^6.0.69",
    "codelyzer": "~3.0.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "nswag": "10.6.0",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.3.2",
    "typescript": "~2.4.0"
  }
}


2) I tried to use yarn instead of npm install but doesn't work :( 

3) I think to follow this tutorial and upgrade to 5 
http://www.talkingdotnet.com/upgrade-angular-4-app-angular-5-visual-studio-2017/

**Comment by MoatazGitHub** [comment]
@ismcagdas Here is packages.config
```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Abp.Web.Resources" version="2.2.1" targetFramework="net46" />
</packages>
```

**Comment by ismcagdas** [comment]
@MoatazGitHub please reopen this issue if you cannot fix this problem by upgrading to angular 5.
