### ISSUE TITLE
Routing Documentation Vue

### ISSUE THREAD

**Issue by skozzii** [aspnetboilerplate/module-zero-core-template#222]
Is there any documentation for the Vue routing?  I am having a lot of trouble simply getting a different landing page to load.  Not a bug, more of an inquiry.  

To specify a bit more, I can change the line in router/index.html 

if (!abp.session.userId && to.name !== 'login') {
      next({
        name: 'login'   // CHANGE THIS TO SOMETHING ELSE
      });

And when I am not logged in the page will be blank from what I assume is a router guard by authentication, but if I log in, and then navigate back to it, the content will load.  I cannot find what auth is blocking it.

I have tried deleting it all together and can reach the landing page having just next(); but that seems to allow navigation to home/home while not signed in, and other places without the redirect back.

Thanks and keep up the great work!

**Comment by ismcagdas** [comment]
@skozzii unfortunately there is no documentation for vue template right now.
So, as I understand you want to display a front-end page which doesn't require authentication, right ?

Do you have any javascript error on the browser console ?
