### ISSUE TITLE
AbpTenants table have some strange unique column

### ISSUE THREAD

**Issue by rcl4444** [aspnetboilerplate/module-zero-core-template#223]
![image](https://user-images.githubusercontent.com/19640490/39080381-922ba568-455f-11e8-809f-73dbd9340239.png)
when I use add-Migration init,it's that
![image](https://user-images.githubusercontent.com/19640490/39080401-1048eb90-4560-11e8-9d15-68acc5638f5d.png)
something wrong with me?
can i remove these unique

**Comment by hikalkan** [comment]
This is strange. It's also similar to other audit columns. I don't think the framework has something like that but we should check it.

**Comment by ismcagdas** [comment]
@rcl4444 have you followed this document https://aspnetboilerplate.com/Pages/Documents/EF-Core-MySql-Integration ?

**Comment by rcl4444** [comment]
@ismcagdas  yes, i followed again,it's' also.

**Comment by alirizaadiyahsi** [comment]
Hi @rcl4444, did you add any configuration to modelbuilder?
I see that Tenants table name, but original name of table is AbpTenants. 
Did you change migration configurations?

**Comment by alirizaadiyahsi** [comment]
When I tested with different DB providers (MySql, PostgreSQL, MSSql), it worked without any issue. 

Feel free to ask question and reopen the issue, if you can't resolve your issue.
