### ISSUE TITLE
Error in build vue in npm: unable to locate 'td_icon.ico'

### ISSUE THREAD

**Issue by phantasia166** [aspnetboilerplate/module-zero-core-template#224]
I got a error in build vue ui as: 
ERROR in [copy-webpack-plugin] unable to locate 'td_icon.ico' at 'xxxxxxxx\vue\td_icon.ico'
ERROR in   Error: HtmlWebpackPlugin: could not load file xxxxxxxx\vue\td_icon.ico

I found the 'td_icon.ico' was configured in '/build/webpack.prod.config.js', is there a wrong naming?
only 'abp.ico' at root of vue folder, I can run it right after I've changed it to ‘abp.ico’, but I'm not sure it's right.

**Comment by ismcagdas** [comment]
@phantasia166 thanks a lot. td_icon.ico is replaced with abp.ico but we forgot to change webpack.prod.config.js.

**Comment by phantasia166** [comment]
It's my pleasure
