### ISSUE TITLE
TypeError: $(...).datetimepicker is not a function

### ISSUE THREAD

**Issue by reuwarwema** [aspnetboilerplate/module-zero-core-template#228]
Following the [`EventCloud tutorial`](http://aspnetboilerplate.com/Pages/Documents/Articles/Developing-MultiTenant-SaaS-ASP.NET-CORE-Angular/index.html)

I am unable to get the datepicker element instead i get an text field.

Similarly, on inspecting the console, I get the error 
> TypeError: $(...).datetimepicker is not a function

Please find my sample files attached

[myfiles.zip](https://github.com/aspnetboilerplate/module-zero-core-template/files/1976389/myfiles.zip)

Please advise. Maybe am missing something and feel free to ask for additional files/code

**Comment by ismcagdas** [comment]
@reuwarwema it seems like this document doesn't refer to datetimepicker client side function, have you tried it yourself ?

If so, try to include one of the below libraries into your solution;

If you want to use jQuery:
https://github.com/Eonasdan/bootstrap-datetimepicker

If you want to use native angular components:
https://github.com/valor-software/ngx-bootstrap
https://github.com/primefaces/primeng
