### ISSUE TITLE
Expression StartsWith method strange in mysql

### ISSUE THREAD

**Issue by rcl4444** [aspnetboilerplate/module-zero-core-template#229]
I use mysql and ef.core for my project.there is my filter below
```
        protected override IQueryable<Tenant> CreateFilteredQuery(TenantSearchFilter input)
        {
            var query = Repository.GetAll();
            if (!string.IsNullOrEmpty(input.Name))
            {
                query = query.Where(o=>o.Name.StartsWith(input.Name));
            }
            return query;
        }
```
![image](https://user-images.githubusercontent.com/19640490/39685124-e1fa6d64-51f2-11e8-9195-cb5e106e6751.png)
and there is the generate sql
```
SELECT `t`.`Id`, `t`.`ApiKey`, `t`.`ApiSecret`, `t`.`ConnectionString`, `t`.`CreationTime`, `t`.`CreatorUserId`, `t`.`DeleterUserId`, `t`.`DeletionTime`, `t`.`EditionId`, `t`.`IsActive`, `t`.`IsDeleted`, `t`.`LastModificationTime`, `t`.`LastModifierUserId`, `t`.`Name`, `t`.`TenancyName`
FROM `Tenants` AS `t`
WHERE ((`t`.`IsDeleted` = FALSE) OR (`t`.`IsDeleted` <> true)) AND ((`t`.`Name` LIKE CONCAT('阿','%') AND (LEFT(`t`.`Name`, LENGTH('阿')) = '阿')) OR ('阿' = ''))
ORDER BY `t`.`Id` DESC
LIMIT 10 OFFSET 0
```
I think is should be use CHAR_LENGTH Suitable for LENGTH

**Comment by alirizaadiyahsi** [comment]
Hi @rcl4444 this is about EF provider that you use in your project. For example if you use `Pomelo.EntityFrameworkCore.MySql` than they have deep knowledge about MySql. There is nothing related with module-zero-core template. You can open an issue in related provider repository. 

If you provider that I mentioned above, you can open issue in this repo: https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql

**Comment by rcl4444** [comment]
I see.thank you
