### ISSUE TITLE
NSwag proxies not updating automatically

### ISSUE THREAD

**Issue by vdurante** [aspnetboilerplate/module-zero-core-template#23]
I created a new AppService, but NSwag is not generating the proxies (ts files) automatically. I couldn't find any info about it. I don't know if it is a bug or not.

I just downloaded the template from aspnetboilerplate dot com, opened the angular project through vscode and the aspnet-core thorugh vs2017.

I added a new appservice. That was it.

Thanks!

**Comment by ismcagdas** [comment]
Hi,

You need to run refresh.bat under https://github.com/aspnetboilerplate/module-zero-core-template/tree/master/angular/nswag/. 

We will update the documentation.

Thanks.

**Comment by vdurante** [comment]
Great. Thank you!
