### ISSUE TITLE
AjaxResponse parsing problem

### ISSUE THREAD

**Issue by g4bry** [aspnetboilerplate/module-zero-core-template#230]
Hi,

I use Asp.Net Zero project with Asp.Net Core and Angular applications.

I create MyAppService and one method that returns an AjaxResponse<MyDto> object to set result, success and error properties of AjaxResponse. 
Then through NSwag tool I generate the service-proxies.ts for Angular but when I call my method on client side, the response doesn't parse correctly because I read only the dto in result property and not the full AjaxResponse. On browser network the response with AjaxResponse seems correctly.

How can I parse correctly the AjaxResponse? I try with WrapResult and DontWrapResult attribute on method but seems don't work.

Thanks

**Comment by ismcagdas** [comment]
@g4bry have you tried this https://forum.aspnetboilerplate.com/viewtopic.php?f=5&t=11217 ?

**Comment by g4bry** [comment]
Thanks @ismcagdas for your response.

I can't apply this solution because the response that receive from service-proxies is not a string.

I describe well my question with example.
On server I have a method as follow:
```
public async Task<AjaxResponse<ObjResponseDto>> DoIt(string param)
        {
            if (..error..)
            {
                return new AjaxResponse<ObjResponseDto>()
                {
                    Result = new ObjResponseDto() { Id = "test" },
                    Success = false,
                    Error = new ErrorInfo(errorCode, "Error")
                };
            }
            else
            {
                return new AjaxResponse<ObjResponseDto>()
                {
                    Result = myObj,
                    Success = true
                };
            }
        }
```
On client Angular, I call method DoIt generate in proxy by nswag tool and I manage response as follow:
```

this.myService.DoIt(
                   param
                )
                .toPromise()
                .then(resp =>{                
			         if (resp.success && resp.error == null) {  // operation  } 
				else {
                                        if (resp.error.code === 1001) {  // other operation }		
				}
			}		
                })
                .catch(e => {
                   // other
                });

```
But `resp ` that I receive is an AjaxResponseOfObjResponseDto with all field null.
In service-proxies, it seems that the problem is on flatMap in the follow code:
```

 if (status === 200) {
            return blobToText(response.body).flatMap(_responseText => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);                
            result200 = resultData200 ? ObjResponseDto.fromJS(resultData200) : new ObjResponseDto();
            return Observable.of(result200);
            });
```
Here _responseText is already the result and not the entire AjaxResponse.

Can you suggest me how to proceed?

Thanks

**Comment by ismcagdas** [comment]
@g4bry you are right, nswag doesn't work well with generics. Why don't you create a new class similar to AjaxResponse and include ObjResponseDto in it and return your new class from your app service.

**Comment by g4bry** [comment]
Ok thanks @ismcagdas.
I thought nswag could have some problems with this. I'll try to follow your suggestion.

**Comment by ismcagdas** [comment]
@g4bry thanks. Let us know if you have any problems regarding to that.
