### ISSUE TITLE
Upgrade to Angular 6.0

### ISSUE THREAD

**Issue by ismcagdas** [aspnetboilerplate/module-zero-core-template#232]

**Comment by ismcagdas** [comment]
I have added rxjs-compat package because some of the most popular packages like ngx-bootstrap and primeng doesn't support RxJS 6 yet. This will be handled in https://github.com/aspnetboilerplate/module-zero-core-template/issues/247.

**Comment by ezra2310** [comment]
After updating Angular 6, Im getting below error while build. I using Core with Angular.

Help us to fix the issue

> ERROR in ./node_modules/abp-ng2-module/src/abp-user-configuration.service.ts
> Module build failed: Error: F:\Project\SourceCode\AlphaPhe\3\aspnet-core\src\AnkaaConsulting.APhe.Web.Host\node_modules\abp-ng2-module\src\abp-user-configuration.service.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
> The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
>     at AngularCompilerPlugin.getCompiledFile (F:\Project\SourceCode\AlphaPhe\3\aspnet-core\src\AnkaaConsulting.APhe.Web.Host\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:709:23)
>     at plugin.done.then (F:\Project\SourceCode\AlphaPhe\3\aspnet-core\src\AnkaaConsulting.APhe.Web.Host\node_modules\@ngtools\webpack\src\loader.js:41:31)
>     at <anonymous>
>     at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by ismcagdas** [comment]
@ezra2310 do you have the below line in your tsconfig.json ?

`"@abp/*": [ "../node_modules/abp-ng2-module/dist/src/*" ]`
