### ISSUE TITLE
How to localize DataAnnotation?

### ISSUE THREAD

**Issue by XelaNimed** [aspnetboilerplate/module-zero-core-template#239]
Hello.
I'm interested in how to localize the data annotations in models. In particular, the localization of errors, for example, Required, MaxLength, Range, and so on. If possible, may be can you add a manual to the documentation? If this is not possible for any reason, how can I localize data entry errors?

**Comment by ismcagdas** [comment]
It is tracked here https://github.com/aspnetboilerplate/aspnetboilerplate/issues/1360.
You might want to take a look at https://github.com/aspnetboilerplate/aspnetboilerplate/issues/582 as well.

So, currently it is not supported but we will work on that for the future.

**Comment by libotti** [comment]
Hi, ismcagdas!

Is there a forecast?

**Comment by ismcagdas** [comment]
@libotti seems like it will not be implemented https://github.com/aspnetboilerplate/aspnetboilerplate/issues/1360#issuecomment-427159819
