### ISSUE TITLE
Angular project does not respond to any clicks

### ISSUE THREAD

**Issue by pantonis** [aspnetboilerplate/module-zero-core-template#240]
When I click to any menu item nothing happens. Please check the moving gif below:

![capture](https://user-images.githubusercontent.com/3295086/40172955-dbe0a61c-59d8-11e8-8fbf-950c2b193df7.gif)

**Comment by alirizaadiyahsi** [comment]
It seems routerlinks are not generated. The weird thing that is working on dev branch. We will investigate to find what is wrong. Thanks for reporting.

**Comment by ismcagdas** [comment]
I guess, this is closed via https://github.com/aspnetboilerplate/module-zero-core-template/commit/ff9216564748230ec6407cccacd259a6f19a00c2.

@pantonis update your downloaded sidebar-nav.component.html with this one;

https://github.com/aspnetboilerplate/module-zero-core-template/blob/master/angular/src/app/layout/sidebar-nav.component.html

**Comment by pantonis** [comment]
thanks it works
