### ISSUE TITLE
Roadmap?

### ISSUE THREAD

**Issue by marcelo-maciel** [aspnetboilerplate/module-zero-core-template#243]
Hi guys, there are any roadmap to the nexts releases?

**Comment by hikalkan** [comment]
Hi,

Follow milestones for next features/enhancements: https://github.com/aspnetboilerplate/aspnetboilerplate/milestones (this is for the ABP framework in general)

If you are specifically asking for this startup template, see https://github.com/aspnetboilerplate/module-zero-core-template/milestones In general, we don't think to add more major features to this startup template.
