### ISSUE TITLE
Constantly happening angular change detection

### ISSUE THREAD

**Issue by ismcagdas** [aspnetboilerplate/module-zero-core-template#249]
Moved from https://github.com/aspnetboilerplate/aspnetboilerplate/issues/3414

Version: 3.8.0
Steps to reproduce: 
- Get latest  ASP.Net Core 2 & Angular ABP template.
- Configure it to start.
- In app.component.html add:
``` html 
<div>{{someFunction()}}</div>
```
- In app.component.ts add: 
``` js
someFunction() {
  console.log('someFunction');
}
```
- Launch the application, login  and open console in developer tools.
- See that “someFunction” is constantly logged into console.

![boilerplate_issue](https://user-images.githubusercontent.com/26853987/40489729-6d411c60-5f72-11e8-8be0-0bd3bd5ae2e8.gif)

**Comment by lytvynR** [comment]
@iyhammad if you create just new project with Angular CLI (without ABP) then console.logs do not happen every second.

**Comment by acjh** [comment]
Related: #68

**Comment by ismcagdas** [comment]
It seems like registering to window's resize event using JQuery constantly triggers Angular's change detection.
