### ISSUE TITLE
angular don't updated when I used "ng update @angular/cli" command

### ISSUE THREAD

**Issue by JigneshPatel04** [aspnetboilerplate/module-zero-core-template#252]
Hello ,
I have used angular/cli ^1.6.1, Angular 5.1.0  + aspnetboilerplate.
I want to need to updated angular 6.* ...
I have followed "https://update.angular.io/" this link.
But I have used "ng update @angular/cli" command then I got below error.
Updating karma configuration
            Updating configuration
            Removing old config file (.angular-cli.json)
            Writing config file (angular.json)
**Invalid JSON character: "﻿" at 0:0.**..

Any solution on it, I want to update angular in aspnetboilerplate.

**Comment by ismcagdas** [comment]
@JigneshPatel04 be sure that you have updated angular-cli before using "ng update".

**Comment by JigneshPatel04** [comment]
Yeah, I have followed the below steps in a link for update angular.
"https://update.angular.io/" .

**Comment by ismcagdas** [comment]
@JigneshPatel04 maybe your existing .angular-cli.json has some problems. You can search this on angular-cli's github repo. We have already updated to angular 6, you can also check our changes here https://github.com/aspnetboilerplate/module-zero-core-template/issues/232.

**Comment by ismcagdas** [comment]
@JigneshPatel04 as I said before, this doesn't seems to be related to ABP template. Could you check https://github.com/angular/angular-cli/issues/10715 ?

**Comment by JigneshPatel04** [comment]
it is running ng update @angular/cli
Thanks, it is fixed now.
converted some .json files (tsconfig, etc.) to UTF8
