### ISSUE TITLE
How can I localize SweetAlert?

### ISSUE THREAD

**Issue by ystemni** [aspnetboilerplate/module-zero-core-template#253]
I need to localize all the possible messages in project because my Boss is Chinese.
The SweetAlert is in moudles, so I can't modify the js.
I also need to localize the error messages such as I input TenancyName with Chinese chars when I edit it.

**Comment by ismcagdas** [comment]
@ystemni I couldn't understand which message you are talking about.

ABP's base localization files contains chinese translations;

https://github.com/aspnetboilerplate/aspnetboilerplate/blob/dev/src/Abp/Localization/Sources/AbpXmlSource/Abp-zh-Hans.xml
https://github.com/aspnetboilerplate/aspnetboilerplate/blob/dev/src/Abp.Zero.Common/Zero/Localization/Source/AbpZero-zh-Hans.xml
https://github.com/aspnetboilerplate/aspnetboilerplate/blob/dev/src/Abp.Web.Common/Web/Localization/AbpWebXmlSource/AbpWeb-zh-Hans.xml

Are you using zh-Hans as the culture code in your app ?

**Comment by ystemni** [comment]
@ismcagdas Thanks for your help.
Do you mean to select Chinese Language ?
![111](https://user-images.githubusercontent.com/16860072/40764294-13f8f6a0-64db-11e8-9081-23cf5bdea52f.png)

I want to translate messages like this
![222](https://user-images.githubusercontent.com/16860072/40764375-59c857f2-64db-11e8-9833-8d459f8912b9.png)

And the SweetAlert UI
![333](https://user-images.githubusercontent.com/16860072/40764419-84f2d3c6-64db-11e8-8e96-f614ad84083a.png)

**Comment by ystemni** [comment]
@ismcagdas 
ABP version : 3.8.0.0
AbpLanguages has "zh-CN" record

**Comment by ystemni** [comment]
I find the record for using zh-Hans instead of zh-CN a month ago, but the record in AbpLanguages table is zh-CN.  Is this the problem ?

**Comment by ismcagdas** [comment]
@ystemni can you change it to zh-Hans and try again ?

There are some other places in the solution.

1. Search for zh-CN in *.cs files and replace with zh-Hans.
2. Search for zh-CN in *.xml files and replace with zh-Hans.
3. Open AbpSettings table and change zh-CN to zh-Hans.

**Comment by ystemni** [comment]
It's working after I use zh-Hans instead of zh-CN.
I want to change the error message such as regex check faild. How should I do?
![444](https://user-images.githubusercontent.com/16860072/40765900-811ebcf6-64e0-11e8-909f-b8bc74a2233e.png)
![555](https://user-images.githubusercontent.com/16860072/40765908-85dcda02-64e0-11e8-9b46-cdfa0f0340fc.png)

**Comment by ismcagdas** [comment]
@ystemni for second one (Delete tenant) add missing files from https://github.com/aspnetboilerplate/module-zero-core-template/blob/master/aspnet-core/src/AbpCompanyName.AbpProjectName.Core/Localization/SourceFiles/AbpProjectName.xml to https://github.com/aspnetboilerplate/module-zero-core-template/blob/master/aspnet-core/src/AbpCompanyName.AbpProjectName.Core/Localization/SourceFiles/AbpProjectName-zh-CN.xml in your project.

I'm looking for regex message.

**Comment by ystemni** [comment]
@ismcagdas Thank you.
 (Delete tenant)  should modify \src\app\tenants\tenants.component.ts . I can do this.

Localize ValidationAttribute error messages seems difficult for me

**Comment by ismcagdas** [comment]
> (Delete tenant) should modify \src\app\tenants\tenants.component.ts . I can do this.

No, just add line below to your zh-Hans.xml file;

`<text name="AreYouSureWantToDelete">您确定要删除{0}吗</text>`

**Comment by ystemni** [comment]
All the delete fuctions in tenants/roles/users have the static string. So I modify them and it has showed correct message.

**Comment by ismcagdas** [comment]
@ystemni this error message is because of the attribute on the related DTO class, see https://github.com/aspnetboilerplate/module-zero-core-template/blob/master/aspnet-core/src/AbpCompanyName.AbpProjectName.Application/MultiTenancy/Dto/CreateTenantDto.cs#L13.

In ABP, it is not possible to localize validation messages. You can either remove this regex and implement it using ICustomValidate interface.
Or a better choice, you can make this validation on the client side.

**Comment by HodaSedighi** [comment]
@ystemni 
it is possible to translate the message without using customValidate. look at this guide, It can help you answer your question.
https://medium.com/@sedighi.iut/localize-validation-error-message-using-data-annotation-in-asp-net-boilerplate-fbd4a0371f2e
