### ISSUE TITLE
event Handler can't be Unit Of Work?

### ISSUE THREAD

**Issue by rcl4444** [aspnetboilerplate/module-zero-core-template#255]
I want to handle events in a chained manner
![image](https://user-images.githubusercontent.com/19640490/40767621-99f07e18-64e5-11e8-954b-d60d8b47eb17.png)
![image](https://user-images.githubusercontent.com/19640490/40767677-c46219a4-64e5-11e8-9083-afe3300ebde6.png)
I do this,but it can be work.

**Comment by hikalkan** [comment]
It can be unit of work. Just make the HandleEventAsync method virtual and add ``[UnitOfWork]`` attribute on top of it. See documents: http://www.aspnetboilerplate.com/Pages/Documents/Unit-Of-Work#controlling-the-unit-of-work

**Comment by rcl4444** [comment]
thank you ,It is work
