### ISSUE TITLE
How to use ClientWebSocket Connect to SignalR with authToken?

### ISSUE THREAD

**Issue by LGinC** [aspnetboilerplate/module-zero-core-template#256]
ClientWebSocket client = new ClientWebSocket();
 client.Options.SetRequestHeader("access_token", token);
await client.ConnectAsync(new Uri("ws://localhost:22742/signalr?access_token="+token), CancellationToken.None);
but not work

**Comment by ismcagdas** [comment]
@LGinC you need to add it to query string like below;

`?enc_auth_token={encrypted_token}`

Value of the {encrypted_token} must be the encrypted version of the original token. It is returned as "encryptedAccessToken" in your authenticate request to TokenAuth/Authenticate.

**Comment by LGinC** [comment]
I try it. but it will not trigger OnMessageReceived event
![image](https://user-images.githubusercontent.com/15363011/40778193-e91f91aa-6502-11e8-9de1-39a09a0d4161.png)

**Comment by ismcagdas** [comment]
@LGinC I just checked and it triggered the event. I used a code similar to yours;

```
ClientWebSocket client = new ClientWebSocket();
await client.ConnectAsync(new Uri("ws://localhost:21021/signalr?enc_auth_token=" + "{your_token}"), CancellationToken.None);
```

If you are using module-zero-core-template bu sure that you are using ws://localhost:21021.

**Comment by LGinC** [comment]
@ismcagdas 
` ClientWebSocket client = new ClientWebSocket();
            HttpClient hclient = new HttpClient();
            var res = await hclient.PostAsync(@"http://localhost:21021/api/TokenAuth/Authenticate", new StringContent(JsonConvert.SerializeObject(new
            {
                userNameOrEmailAddress = "admin",
                password = "123qwe",
                rememberClient = true,
           }), Encoding.UTF8, "application/json"));
            if (res.IsSuccessStatusCode)
            {
                var rjson = await res.Content.ReadAsStringAsync();
                JObject result = JObject.Parse(rjson);
                Console.WriteLine($"ws://localhost:21021/signalr?enc_auth_token={result["result"]["encryptedAccessToken"]}");
                await client.ConnectAsync(new Uri($"ws://localhost:21021/signalr?enc_auth_token={result["result"]["encryptedAccessToken"]}"), CancellationToken.None);
                var b = Encoding.UTF8.GetBytes(@"{""protocol"":""json"", ""version"":1}");             
                Console.WriteLine("Connect success");
                await client.SendAsync(new ArraySegment<byte>(new System.Collections.Generic.List<byte>(b){0x1e}.ToArray())
               , WebSocketMessageType.Text, true, CancellationToken.None);
                b =  Encoding.UTF8.GetBytes(@"{""type"":1, ""invocationId"":""12"", ""target"":""AddOnlineClient"",""arguments"":[16]}");    
                Console.WriteLine("Send success");
                Console.ReadLine();
            }`

![tim 20180601011421](https://user-images.githubusercontent.com/15363011/40796966-43b28b78-6539-11e8-8961-a16dc0b5fa5e.png)

 I add token and it can not connect

**Comment by LGinC** [comment]
![image](https://user-images.githubusercontent.com/15363011/40817978-82d95b08-6587-11e8-9d27-3ed6c6c0557e.png)
I modify enc_auth_token to encAccessToken, and client connect success.
but File.Wirte didn't trigger in OnMessageReceived event handler.
I can't find any txt file in my desktop

**Comment by acjh** [comment]
```c#
if (qsAuthToken == null)
{
    return Task.CompletedTask;
}
```

**Comment by LGinC** [comment]
@acjh `await client.ConnectAsync(new Uri($"ws://localhost:21021/signalr?encAccessToekn={result["result"]["encryptedAccessToken"]}")`

?encAccessToekn={result["result"]["encryptedAccessToken"]}  
is there qsAuthToken? why that is null?

**Comment by acjh** [comment]
encAccessTo**ek**n != encAccessTo**ke**n

**Comment by LGinC** [comment]
what??  oh...no

**Comment by ismcagdas** [comment]
@LGinC can't you get it in the initial Post request to TokenAuth/Authenticate ?

**Comment by acjh** [comment]
@LGinC `encryptedAccessToken`

**Comment by LGinC** [comment]
@ismcagdas  I use it but querystring is null in event handler.
$"ws://localhost:21021/signalr?encAccessToekn={result["result"]["encryptedAccessToken"]

**Comment by acjh** [comment]
encAccessTo**ek**n != encAccessTo**ke**n

**Comment by LGinC** [comment]
@acjh what's the mean? the encAccessToken in event handler != encAccessToken in my url?

**Comment by acjh** [comment]
Check your spelling.

**Comment by LGinC** [comment]
amazing, clientWebSocket connected when 'token' is not same as that in event handler.
![image](https://user-images.githubusercontent.com/15363011/40842092-49fe33b4-65df-11e8-9bea-005612e20c7a.png)
![image](https://user-images.githubusercontent.com/15363011/40842100-562168e6-65df-11e8-803a-ba0093901d2e.png)
there is a same key word called 'token', and can not connected.
![image](https://user-images.githubusercontent.com/15363011/40842160-82185324-65df-11e8-94cc-e29285e60d2d.png)


when I set different key word,
![image](https://user-images.githubusercontent.com/15363011/40842182-9be54bd6-65df-11e8-85c9-95b81667d41c.png)
![image](https://user-images.githubusercontent.com/15363011/40842193-a353bd58-65df-11e8-8cfc-d7aaee691824.png)
and it connected.
![image](https://user-images.githubusercontent.com/15363011/40842211-b2e9291a-65df-11e8-9a53-dd518a37010b.png)

**Comment by acjh** [comment]
Check your Logs.txt.

**Comment by LGinC** [comment]
![image](https://user-images.githubusercontent.com/15363011/40842403-5ec1c8aa-65e0-11e8-9607-0ab196065346.png)
there is some log about jwt.  oh yes

**Comment by LGinC** [comment]
I am sorry. there is last question.
![image](https://user-images.githubusercontent.com/15363011/40847940-4bc760f6-65f0-11e8-8fd4-867d5b2780a1.png)
I add this and application cannot startup.
log:
![image](https://user-images.githubusercontent.com/15363011/40848007-83249942-65f0-11e8-8f7b-bc7ec523b990.png)
