### ISSUE TITLE
AppEnums.ts's bug

### ISSUE THREAD

**Issue by xl-wenqiang** [aspnetboilerplate/module-zero-core-template#259]
The latest NSwag tool has a more reasonable generation of enumerations, but the definition of AppEnums.ts is still the previous format.I corrected this file, see attachment.
[AppEnums.ts.txt](https://github.com/aspnetboilerplate/module-zero-core-template/files/2075229/AppEnums.ts.txt)

**Comment by ismcagdas** [comment]
@xl-wenqiang this file belongs to AspNet Zero. Are you using `DescribeAllEnumsAsStrings `?

**Comment by xl-wenqiang** [comment]
NSwag now generates string by default, I didn't modify service.config.nswag.When I run `npm start`, I get an error if I don't modify AppEnums.ts.

**Comment by xl-wenqiang** [comment]
`<PackageReference Include="Swashbuckle.AspNetCore" Version="2.3.0" />`

**Comment by ismcagdas** [comment]
@xl-wenqiang so you also don't use DescribeAllEnumsAsStrings in your Startup.cs while configuring Swashbuckle.AspNetCore, right ?

**Comment by xl-wenqiang** [comment]
@ismcagdas right

**Comment by ismcagdas** [comment]
@xl-wenqiang Thanks. We had some problems when using **DescribeAllEnumsAsStrings** with ASP.NET Core. I also don't like using such kind of dirty enum definitions but we will keep that usage for now.

Thank you for your contribution anyway 😄 .
