### ISSUE TITLE
angular 2 template not start with compile error

### ISSUE THREAD

**Issue by heavenwing** [aspnetboilerplate/module-zero-core-template#26]
I got this error:
AppPreBootstrap.ts (65,24): Property 'tz' does not exist on type 'typeof mom
ent'.

ERROR in RootModule is not an NgModule

My npm version is:
{ 'abp-project-name-template': '0.0.0',
  npm: '3.10.10',
  ares: '1.10.1-DEV',
  http_parser: '2.7.0',
  icu: '58.2',
  modules: '48',
  node: '6.10.1',
  openssl: '1.0.2k',
  uv: '1.9.1',
  v8: '5.1.281.95',
  zlib: '1.2.8' }

angular-cli version is:
@angular/cli: 1.0.0
node: 6.10.1
os: win32 x64
@angular/common: 2.4.10
@angular/compiler: 2.4.10
@angular/core: 2.4.10
@angular/forms: 2.4.10
@angular/http: 2.4.10
@angular/platform-browser: 2.4.10
@angular/platform-browser-dynamic: 2.4.10
@angular/router: 3.4.10
@angular/cli: 1.0.0
@angular/compiler-cli: 2.4.10

**Comment by ismcagdas** [comment]
Hi,

We haven't test it with angular-cli 1.0.
Does this happen with angular-cli 1.0.0-rc.2 ?

**Comment by heavenwing** [comment]
Thanks for reply

But my angular-cli is 1.0.0

**Comment by ChiakiYu** [comment]
I also have this problem

**Comment by hikalkan** [comment]
Do you still have problems?
