### ISSUE TITLE
Crash when using Hsts and UseHttpsRedirection

### ISSUE THREAD

**Issue by XelaNimed** [aspnetboilerplate/module-zero-core-template#269]
Hello. I'm use:

- Abp version 3.7.2.
- Base framework: .Net Core 2.1.1.
- ORM framework: EF Core 2.1.1.
- and free startup template for multi-page application with included management pages (version .3.9.0).

In the ASP.Net version 2.1, it became possible to use the HTTPS protocol. To do this, need add middleware to the Configure method of the Startup.cs file, like so:
```c#
public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory) {
    app.UseAbp();
    if (env.IsDevelopment()) {
        app.UseDeveloperExceptionPage();
    }
    else {
        app.UseExceptionHandler("/Error");
        app.UseHsts();
    }
    app.UseHttpsRedirection();
    // other stuff
}
```
Just add this code does not work, because the specified extensions are not available. After adding the NuGet package Microsoft.AspNetCore.App extensions for IApplicationBuilder can be used, but when the project starts it crashes. 
Target framework is set to netcoreapp2.1. and checkbox "Enable SSL" is checked in project properties. 

How do I configure a project to use HTTPS?

**Comment by ismcagdas** [comment]
@XelaNimed we haven't tried using UseHsts or UseHttpsRedirection yet. 

> but when the project starts it crashes.

* Is there any error in the log file ?
* If not, is there any error message in windows event viewer ?

**Comment by ismcagdas** [comment]
@XelaNimed have you installed ASP.NET Core 2.1 hosting bundle https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-2.1&tabs=aspnetcore2x#install-the-net-core-hosting-bundle ?

**Comment by XelaNimed** [comment]
@ismcagdas I have ASP.Net Core 2.1.300 SDK installed. 
> C:\Users\J.Doe>dotnet --version
2.1.300

**Comment by ismcagdas** [comment]
@XelaNimed ok, we will check it, thanks.

**Comment by XelaNimed** [comment]
I deleted the Microsoft.AspNetCore.App NuGet package and middleware calls and just left the checked "Enable SSL" checkbox in projects properties (xxx.Web.MVC and xxx.Web.Host). After that, the project started without any errors, but I'm not sure that this method is correct.
What problems can occur without middleware calls (`UseHsts()` and `UseHttpsRedirection()`)?

**Comment by ismcagdas** [comment]
>  After that, the project started without any errors

Was taht using https or http ?

I'm not sure if there will be any errors in your case because we haven't used those middle-wares before as I said.

**Comment by XelaNimed** [comment]
@ismcagdas starts with HTTPS.

**Comment by zetic-be** [comment]
I installed the dotnet-hosting-2.1.1 as suggested in following post and it worked:

https://stackoverflow.com/questions/50919226/cant-run-net-core-2-1-1-application-on-windows-server-2016

**Comment by ismcagdas** [comment]
@zetic-be thanks. @XelaNimed I'm not sure why that didn't work for you.
