### ISSUE TITLE
Test publishing merged project

### ISSUE THREAD

**Issue by ismcagdas** [aspnetboilerplate/module-zero-core-template#270]
Moved from https://github.com/aspnetboilerplate/aspnetboilerplate/issues/3450#issuecomment-398112921

**Comment by alirizaadiyahsi** [comment]
I tried and can't reproduce the issue. I followed [instructions in this tutorial](https://aspnetzero.com/Documents/Step-by-step-publish-to-azure-angular). "**PUBLISH HOST APPLICATION TO THE AZURE**" steps are enough to success.
