### ISSUE TITLE
How to get ProviderKey  before login

### ISSUE THREAD

**Issue by ly303550688** [aspnetboilerplate/module-zero-core-template#271]
before login I can only get the AccessCode and Provider

**Comment by ismcagdas** [comment]
@ly303550688 yes because you need to now userId to query AbpUserLogins.
You can join two tables (AbpUsers & AbpUserLogins) and query using "username", "password" and "tenantId" to get ProviderKey before login.

**Comment by ly303550688** [comment]
I delete the prop.used for wechat oauth login
