### ISSUE TITLE
Default port 5000 is used when start Web.Host with dotnet run

### ISSUE THREAD

**Issue by a-merson** [aspnetboilerplate/module-zero-core-template#274]
Hi!
There is a minor issue with current template: 
when start `Web.Host` app with `dotnet run` command, it uses default port 5000.
This happens because dotnet CLI doesn't know about "launchUrl" parameter.
But starting from Core 2.0 it knows "applicationUrl" parameter that do the trick.
I made PR #273 on this.

**Comment by alirizaadiyahsi** [comment]
https://github.com/aspnetboilerplate/module-zero-core-template/pull/273/commits/927c06e7cb4e13cd697c78ddfc120d1abc2b681c
