### ISSUE TITLE
Culture problem

### ISSUE THREAD

**Issue by rcl4444** [aspnetboilerplate/module-zero-core-template#275]
I have a problem about the default culture.
![image](https://user-images.githubusercontent.com/19640490/41695723-d834f5d8-7542-11e8-93e9-92fb2d35e206.png)
it 's repeat at AbpUserRequestCultureProvider?
![image](https://user-images.githubusercontent.com/19640490/41696964-4c6be6ea-7549-11e8-9c92-0120b4349ddf.png)
Whether using GetSettingValueForApplicationAsync is more appropriate？

**Comment by ismcagdas** [comment]
@rcl4444 couldn't understand the problem. What problem does it cause ? Could you explain with an example ?

**Comment by rcl4444** [comment]
I send a http request,it don't have any culture flag(like the .AspNetCore.Culture in header 
cookie in Abp.Localization.CultureName or any others),the AbpDefaultRequestCultureProvider can't Obtain the default Abp.Localization.DefaultLanguageName setting.
![image](https://user-images.githubusercontent.com/19640490/41700967-168a02b4-755d-11e8-8a56-6ed7996b3765.png)

**Comment by rcl4444** [comment]
I think it's the same of 
![image](https://user-images.githubusercontent.com/19640490/41701025-59e15b7a-755d-11e8-9e4d-fbcbfe30eabb.png)

**Comment by ismcagdas** [comment]
@rcl4444 if you don't send user information on your request, application's default setting must be used.
The example code in this comment https://github.com/aspnetboilerplate/module-zero-core-template/issues/275#issuecomment-398987853 must get application's default setting.

What does it get in your case ?

**Comment by rcl4444** [comment]
the centos' culture don't contain ‘zh-CN’, when I first request the http.It can't get the right Localized string.
![image](https://user-images.githubusercontent.com/19640490/41764510-ed34d40c-7633-11e8-8d22-ffddfbaad42b.png)
when I request for anonymous
![image](https://user-images.githubusercontent.com/19640490/41764562-0cf2d56e-7634-11e8-8733-29b99e8b651c.png)

**Comment by ismcagdas** [comment]
Can you try zh-Hans ? We have changed zh-CN to zh-Hans in ABP and our templates.

**Comment by rcl4444** [comment]
it's 3.6.0 bug, I seem to have to migrate the code to version 3.9。

**Comment by rcl4444** [comment]
@ismcagdas ,Moving from the 3.6.0 template to 3.9.0, I feel this workload is a bit large. Is there a good suggestion or method?

**Comment by ismcagdas** [comment]
you can;

* upgrade ABP nuget packages
* Then, search for zh-CN in your solution (including file names) and change them to zh-Hans.

**Comment by rcl4444** [comment]
Regarding the above bugs, I repaired it based on your suggestions.
My existing code is based on the 3.6.0 (vue) template for development, I always keep the package updated, the above problem is caused due to the implementation of vue, The following code leads
![image](https://user-images.githubusercontent.com/19640490/41778295-e192ea62-7660-11e8-8358-86aa0dd4c8e3.png)
which I spent a long time to investigate, I think Expression, whether there is a better program, can more quickly migrate to 3.9.0 based on the 3.6.0 implementation, otherwise it is more troublesome copy code
