### ISSUE TITLE
SweetAlert - Buttons missing when alert contains single button

### ISSUE THREAD

**Issue by iamseanduffy** [aspnetboilerplate/module-zero-core-template#279]
When a SweetAlert popup is used with a single button, the button is not shown.
This is inconsistent with other uses of the alert and is confusing to some users.

Issue can be reproduced by providing incorrect login details.

Fix for issue:

librarySettings.js

Change this:
```
abp.libs.sweetAlert.config.info.buttons = [app.localize("Ok")];
abp.libs.sweetAlert.config.success.buttons = [app.localize("Ok")];
abp.libs.sweetAlert.config.warn.buttons = [app.localize("Ok")];
abp.libs.sweetAlert.config.error.buttons = [app.localize("Ok")];
```

To this:
```
abp.libs.sweetAlert.config.info.button = app.localize("Ok");
abp.libs.sweetAlert.config.success.button = app.localize("Ok");
abp.libs.sweetAlert.config.warn.button = app.localize("Ok");
abp.libs.sweetAlert.config.error.button = app.localize("Ok");
```

**Comment by ismcagdas** [comment]
Thanks a lot @iamseanduffy

**Comment by alirizaadiyahsi** [comment]
This issue is not related with this repository. I moved this issue to it's own repo (private), so I am closing this.

@iamseanduffy  you can follow it from this issue: https://github.com/aspnetzero/aspnet-zero-core/issues/1349
