### ISSUE TITLE
Adding Static Roles

### ISSUE THREAD

**Issue by iamseanduffy** [aspnetboilerplate/module-zero-core-template#282]
I would like to add new static roles to the 'RoleManagementConfig.StaticRoles' collection.

The only documentation we have found seems to relate to the Framework461 version of Zero
(https://github.com/aspnetboilerplate/aspnetboilerplate/blob/e8bad1daa7abf5887f9df5336c8ace04b9c6cbc8/doc/WebSite/Zero/Role-Management.md)

`Configuration.Modules.Zero().RoleManagement.StaticRoles.Add(new StaticRoleDefinition("Admin", MultiTenancySides.Tenant));`

However this syntax does not seem to be appropriate for the dotnet core implementation.

How would we update this collection?

**Comment by ismcagdas** [comment]
@iamseanduffy I just tried with module-zero-core-template and seems like this can be used;

```
Configuration.Modules.Zero().RoleManagement.StaticRoles.Add(
                new StaticRoleDefinition(
                    "Manager",
                    MultiTenancySides.Host)
            );
```

So, does it build for you when you use the code you have shared ?

**Comment by iamseanduffy** [comment]
Sorry, I had meant to say the code snipped cannot be used.  The code does not build.

In the end I added my static roles to AppRoleConfig.cs

            roleManagementConfig.StaticRoles.Add(
                new StaticRoleDefinition(
                    StaticRoleNames.Tenants.Roles,
                    MultiTenancySides.Tenant)
                );

**Comment by ismcagdas** [comment]
@iamseanduffy have you added below using statements ?

```
using Abp.MultiTenancy;
using Abp.Zero.Configuration;
```

**Comment by iamseanduffy** [comment]
I am embarrassed to say that it works ok today!
Apologies.
Please close this ticket.
