### ISSUE TITLE
Auto login for angular

### ISSUE THREAD

**Issue by Worthy7** [aspnetboilerplate/module-zero-core-template#283]
https://github.com/aspnetboilerplate/module-zero-core-template/blob/f042d7b483fe49d624ea04b7255ddfea289ac2ee/angular/src/shared/auth/auth-route-guard.ts#L22

I'm not an angular expert, but is the template supposed to keep a user logged in? Even if the refresh the page?

**Comment by Worthy7** [comment]
I think perhaps `AppSessionService` is supposed to be using NgOnInit instead of
https://github.com/aspnetboilerplate/module-zero-core-template/blob/f042d7b483fe49d624ea04b7255ddfea289ac2ee/angular/src/shared/session/app-session.service.ts#L46

**Comment by ismcagdas** [comment]
@Worthy7 couldn't understand the problem here. What is the real life scenario you are facing ?

**Comment by Worthy7** [comment]
When I refresh the page the user is logged out.

**Comment by ismcagdas** [comment]
@Worthy7 never faced a similar issue but we will test it.

**Comment by Worthy7** [comment]
There is a chance that I butchered your login component enough to break
that functionality at some point. It's all about AppSessionService.init

**Comment by alirizaadiyahsi** [comment]
Hi @Worthy7, I tested again and there is no such issue that you mentioned.

Actually we have never faced such an error before :)

**Comment by Worthy7** [comment]
Yea I seem to still have the issue - it seems to have returned. I'll work this out why on my end.

So just to confirm, the default template is automatically logging the user in if they have visited before? (Angular)

**Comment by alirizaadiyahsi** [comment]
> So just to confirm, the default template is automatically logging the user in if they have visited before? 

**fix**

> "if they have visited before?" -> "if they have logged in before?"

Yes.

**Comment by Worthy7** [comment]
Ok. Thanks
