### ISSUE TITLE
The Vue project saves the bug of the data

### ISSUE THREAD

**Issue by dafeifei0218** [aspnetboilerplate/module-zero-core-template#287]
When you modify the data, click Cancel, and the data in the table is also updated. The actual data did not update the database.

**Comment by ismcagdas** [comment]
@dafeifei0218 in which page does this happen ? I couldn't reproduce it.

**Comment by dafeifei0218** [comment]
The template I downloaded from the website is v3.5.0 version, generated and running, user management, tenant management, role management have this situation.
Click Edit, modify the data, click Cancel, the data of the form will become the modified data. After refreshing, it is the original data. Let me use the 4.0 version.

**Comment by ismcagdas** [comment]
@dafeifei0218 ok, waiting for your test of v4.0.
