### ISSUE TITLE
Parent already defined

### ISSUE THREAD

**Issue by smooney123** [aspnetboilerplate/module-zero-core-template#296]
![image](https://user-images.githubusercontent.com/5982529/42836923-58a5eb1c-89f4-11e8-8d89-b694bac73f8c.png)

I keep getting this error message now and again. Most of the time it works.

(function () {
    "use strict";

    var app = angular.module("app",
        [
            "ngAnimate",
            "ngSanitize",
            "ui.router",
            "ui.bootstrap",
            "ui.jq",
            "abp",
            "ncy-angular-breadcrumb",
            "ngImageDimensions"
        ]);

    app.config([
        "$stateProvider", "$urlRouterProvider", "$sceProvider",
        function ($stateProvider, $urlRouterProvider, $sceProvider) {
            $sceProvider.enabled(false);

            if (abp.auth.isGranted("SuperAdmins")) {

                console.log("super admin");

                $stateProvider
                    .state("parent",
                    {
                        url: "/#/",
                        abstract: false,
                        template: "<ui-view/>",
                        ncyBreadcrumb: {
                            label: "Dashboard"
                        }
                    }).state("dashboard",
                    {
                        url: "/",
                        templateUrl: "/App/Main/views/tenants/index.cshtml",
                        menu: "Dashboard",
                        ncyBreadcrumb: {
                            label: "Dashboard"
                        }
                    })
                    .state("tenants",
                    {
                        url: "/tenants",
                        templateUrl: "/App/Main/views/tenants/index.cshtml",
                        menu: "Tenants",
                        ncyBreadcrumb: {
                            label: "Tenants"
                        }
                    })
                    .state("add_tenant",
                    {
                        url: "/add_tenant",
                        templateUrl: "/App/Main/views/tenants/create.cshtml",
                        menu: "Tenants",
                        ncyBreadcrumb: {
                            label: "Add Tenant"
                        },
                        parent: "tenants"

                    }).state("edit_tenant",
                    {
                        url: "/edit_tenant/:id",
                        templateUrl: "/App/Main/views/tenants/edit.cshtml",
                        menu: "Tenants",
                        ncyBreadcrumb: {
                            label: "Edit Tenant"
                        },
                        parent: "tenants"
                    })
                    .state("users",
                    {
                        url: "/users",
                        templateUrl: "/App/Main/views/users/list.cshtml",
                        menu: "Users",
                        ncyBreadcrumb: {
                            label: "Users"
                        }
                    }).state("edit_user",
                    {
                        url: "/edit_user/:id",
                        templateUrl: "/App/Main/views/users/edit.cshtml",
                        menu: "Users",
                        ncyBreadcrumb: {
                            label: "Edit User"
                        },
                        parent: "users"
                    })
                    .state("add_user",
                    {
                        url: "/add_user",
                        templateUrl: "/App/Main/views/users/create.cshtml",
                        menu: "Users",
                        ncyBreadcrumb: {
                            label: "Add User"
                        },
                        parent: "users"
                    })
                    .state("profile",
                    {
                        url: "/profile",
                        templateUrl: "/App/Main/views/profile/profile.cshtml",
                        menu: "Profile",
                        ncyBreadcrumb: {
                            label: "Profile"
                        }
                    }).state("change-password",
                    {
                        url: "/change-password",
                        templateUrl: "/App/Main/views/profile/changePassword.cshtml",
                        menu: "Change Password",
                        ncyBreadcrumb: {
                            label: "Change Password"
                        }
                    });

                $urlRouterProvider.otherwise("/");
            }

            if (abp.auth.isGranted("Admins")) {

                console.log("admin");

                $stateProvider
                    .state("parent",
                    {
                        url: "/#/",
                        abstract: false,
                        template: "<ui-view/>",
                        ncyBreadcrumb: {
                            label: "Dashboard"
                        }
                    }).state("dashboard",
                        {
                            url: "/",
                            templateUrl: "/App/Main/views/users/list.cshtml",
                            menu: "Dashboard",

                            ncyBreadcrumb: {
                                label: "Dashboard"
                            }
                    }).state("add_user",
                    {
                        url: "add_user",
                        templateUrl: "/App/Main/views/users/create.cshtml",
                        menu: "Users",
                        ncyBreadcrumb: {
                            label: "Add User"
                        },
                        parent: "dashboard"
                    }).state("edit_user",
                    {
                        url: "edit_user/:userName",
                        templateUrl: "/App/Main/views/users/edit.cshtml",
                        menu: "Users",
                        controller: 'app.views.users.edit',
                        ncyBreadcrumb: {
                            label: 'Edit User / {{userName}}', 
                        },
                        parent: "dashboard"
                    })
                    .state("add_blog",
                        {
                            url: "/add_blog",
                            templateUrl: "/App/Main/views/blogs/create.cshtml",
                            menu: "Blogs",
                            ncyBreadcrumb: {
                                label: "Add Blog"
                            },
                            parent: "list-blogs"
                    })
                    .state("list-blogs",
                        {
                            url: "/list-blogs",
                            templateUrl: "/App/Main/views/blogs/index.cshtml",
                            menu: "Blogs",
                            ncyBreadcrumb: {
                                label: "Blogs"
                            }
                    })
                    .state("edit-blog",
                        {
                            url: "/edit-blog/:id",
                            templateUrl: "/App/Main/views/blogs/edit.cshtml",
                            menu: "Blogs",
                            ncyBreadcrumb: {
                                label: "Edit Blog"
                            },
                            parent: "list-blogs"
                     })
                    
                    .state("profile",
                    {
                        url: "/profile",
                        templateUrl: "/App/Main/views/profile/profile.cshtml",
                        menu: "Profile",
                        ncyBreadcrumb: {
                            label: "Profile"
                        },
                        parent: "dashboard"
                    }).state("change-password",
                    {
                        url: "/change-password",
                        templateUrl: "/App/Main/views/profile/changePassword.cshtml",
                        menu: "Change Password",
                        ncyBreadcrumb: {
                            label: "Change Password"
                        },
                        parent: "dashboard"
                    })
                    .state("role-list",
                    {
                        url: "/role-list",
                        templateUrl: "/App/Main/views/roles/index.cshtml",
                        menu: "Roles",
                        ncyBreadcrumb: {
                            label: "Roles"
                        }
                    });

                $urlRouterProvider.otherwise("/");
            }

            if (abp.auth.isGranted("Users")) {

                console.log("user");

                $stateProvider
                    .state("parent",
                    {
                        url: "/#/",
                        abstract: false,
                        template: "<ui-view/>",
                        ncyBreadcrumb: {
                            label: "Dashboard"
                        }
                    })
                    .state("users",
                    {
                        url: "/users",
                        templateUrl: "/App/Main/views/users/list.cshtml",
                        menu: "Users",
                        ncyBreadcrumb: {
                            label: "Users"
                        }
                    }).state("edit_user",
                    {
                        url: "/edit_user/:userName",
                        templateUrl: "/App/Main/views/users/edit.cshtml",
                        menu: "Users",
                        ncyBreadcrumb: {
                            label: "Edit User"
                        },
                        parent: "users"
                    })
                    .state("add_user",
                    {
                        url: "/add_user",
                        templateUrl: "/App/Main/views/users/create.cshtml",
                        menu: "Users",
                        ncyBreadcrumb: {
                            label: "Add User"
                        },
                        parent: "users"
                    })
                    .state("dashboard",
                    {
                        url: "/",
                        templateUrl: "/App/Main/views/users/list.cshtml",
                        menu: "Dashboard",
                        ncyBreadcrumb: {
                            label: "Dashboard"
                        }
                    })
                    .state("subscription",
                    {
                        url: "/subscription",
                        templateUrl: "/App/Main/views/subscriptions/subscription.cshtml",
                        menu: "Subscription",
                        ncyBreadcrumb: {
                            label: "My Subscription"
                        }
                    })
                    .state("card",
                    {
                        url: "/card",
                        templateUrl: "/App/Main/views/card/card.cshtml",
                        menu: "Payment",
                        ncyBreadcrumb: {
                            label: "Payment Methods"
                        }
                    })
                    .state("edit_card",
                    {
                        url: "/edit_card",
                        templateUrl: "/App/Main/views/card/edit.cshtml",
                        menu: "Payment",
                        params: {
                            myParam: null
                        },
                        ncyBreadcrumb: {
                            label: "Edit Card"
                        },
                        parent: "card"
                    })
                    .state("add_card",
                    {
                        url: "/add_card",
                        templateUrl: "/App/Main/views/card/add.cshtml",
                        menu: "Payment",
                        ncyBreadcrumb: {
                            label: "Add Card"
                        },
                        parent: "card"
                    }).state("profile",
                    {
                        url: "/profile",
                        templateUrl: "/App/Main/views/profile/profile.cshtml",
                        menu: "Profile",
                        ncyBreadcrumb: {
                            label: "Profile"
                        },
                        parent: "dashboard"
                    }).state("change-password",
                    {
                        url: "/change-password",
                        templateUrl: "/App/Main/views/profile/changePassword.cshtml",
                        menu: "Change Password",
                        ncyBreadcrumb: {
                            label: "Change Password"
                        },
                        parent: "dashboard"
                    });

                $urlRouterProvider.otherwise("/");
            }

            if (abp.auth.isGranted("BasicUsers")) {
                $stateProvider
                    .state("parent",
                    {
                        url: "/#/",
                        abstract: false,
                        template: "<ui-view/>",
                        ncyBreadcrumb: {
                            label: "Dashboard"
                        }
                    }).state("dashboard",
                    {
                        url: "/",
                        templateUrl: "/App/Main/views/users/home.cshtml",
                        menu: "Dashboard",
                        ncyBreadcrumb: {
                            label: "Dashboard"
                        }
                    })
                    .state("profile",
                    {
                        url: "/profile",
                        templateUrl: "/App/Main/views/profile/profile.cshtml",
                        menu: "Profile",
                        ncyBreadcrumb: {
                            label: "Profile"
                        },
                        parent: "dashboard"
                    }).state("change-password",
                    {
                        url: "/change-password",
                        templateUrl: "/App/Main/views/profile/changePassword.cshtml",
                        menu: "Change Password",
                        ncyBreadcrumb: {
                            label: "Change Password"
                        },
                        parent: "dashboard"
                    }).state("enter",
                    {
                        url: "/enter",
                        templateUrl: "/App/Main/views/entries/enter.cshtml",
                        menu: "Enter",
                        ncyBreadcrumb: {
                            label: "Enter"
                        }
                    }).state("entries",
                    {
                        url: "/entries",
                        templateUrl: "/App/Main/views/entries/entries.cshtml",
                        menu: "My Entries",
                        ncyBreadcrumb: {
                            label: "My Entries"
                        }
                    }).state("archived",
                    {
                        url: "/archived",
                        templateUrl: "/App/Main/views/entries/archived.cshtml",
                        menu: "Archived",
                        ncyBreadcrumb: {
                            label: "Archived"
                        }
                    }).state("ads",
                    {
                        url: "/ads",
                        templateUrl: "/App/Main/views/advertisements/index.cshtml",
                        menu: "Ads",
                        ncyBreadcrumb: {
                            label: "Ads"
                        }
                    }).state("create-ad",
                    {
                        url: "/create-ad",
                        templateUrl: "/App/Main/views/advertisements/create.cshtml",
                        menu: "Create Ad",
                        ncyBreadcrumb: {
                            label: "Create Ad"
                        },
                        parent: "ads"
                    }).state("edit-ad",
                    {
                        url: "/edit-ad/:id",
                        templateUrl: "/App/Main/views/advertisements/edit.cshtml",
                        menu: "Edit-Ad",
                        ncyBreadcrumb: {
                            label: "Edit-Ad"
                        },
                        parent: "ads"
                    });
                console.log("basic user");
            }

            if (abp.auth.isGranted("Advertisers")) {
                $stateProvider
                    .state("parent",
                    {
                        url: "/#/",
                        abstract: false,
                        template: "<ui-view/>",
                        ncyBreadcrumb: {
                            label: "Dashboard"
                        }
                    }).state("dashboard",
                    {
                        url: "/",
                        templateUrl: "/App/Main/views/advertisements/index.cshtml",
                        menu: "Dashboard",
                        ncyBreadcrumb: {
                            label: "Dashboard"
                        }
                    })
                    .state("profile",
                    {
                        url: "/profile",
                        templateUrl: "/App/Main/views/profile/profile.cshtml",
                        menu: "Profile",
                        ncyBreadcrumb: {
                            label: "Profile"
                        },
                        parent: "dashboard"
                    }).state("change-password",
                    {
                        url: "/change-password",
                        templateUrl: "/App/Main/views/profile/changePassword.cshtml",
                        menu: "Change Password",
                        ncyBreadcrumb: {
                            label: "Change Password"
                        },
                        parent: "dashboard"
                    }).state("ads",
                    {
                        url: "/ads",
                        templateUrl: "/App/Main/views/advertisements/index.cshtml",
                        menu: "Ads",
                        ncyBreadcrumb: {
                            label: "Ads"
                        }
                    }).state("create-ad",
                    {
                        url: "/create-ad",
                        templateUrl: "/App/Main/views/advertisements/create.cshtml",
                        menu: "Create Ad",
                        ncyBreadcrumb: {
                            label: "Create Ad"
                        },
                        parent: "ads"
                    }).state("edit-ad",
                    {
                        url: "/edit-ad/:name",
                        templateUrl: "/App/Main/views/advertisements/edit.cshtml",
                        menu: "Edit-Ad",
                        controller: "app.views.edit",
                        ncyBreadcrumb: {
                            label: "Edit-Ad / {{name}}"
                        },
                        parent: "ads"
                    }).state("subscription",
                    {
                        url: "/subscription",
                        templateUrl: "/App/Main/views/subscriptions/subscription.cshtml",
                        menu: "Subscription",
                        ncyBreadcrumb: {
                            label: "My Subscription"
                        }
                    }).state("card",
                    {
                        url: "/card",
                        templateUrl: "/App/Main/views/card/card.cshtml",
                        menu: "Payment",
                        ncyBreadcrumb: {
                            label: "Payment Methods"
                        },

                    })
                    .state("edit_card",
                    {
                        url: "/edit_card/:id",
                        templateUrl: "/App/Main/views/card/edit.cshtml",
                        menu: "Payment",
                        params: {
                            myParam: null
                        },
                        ncyBreadcrumb: {
                            label: "Edit Card"
                        },
                        parent: "card"
                    })
                    .state("add_card",
                    {
                        url: "/add_card",
                        templateUrl: "/App/Main/views/card/add.cshtml",
                        menu: "Payment",
                        ncyBreadcrumb: {
                            label: "Add Card"
                        },
                        parent: "card"
                    });
                console.log("advertiser");

                $urlRouterProvider.otherwise("/");
            }

            if (abp.auth.isGranted("Drummer")) {
                $stateProvider
                    .state("parent",
                        {
                            url: "/#/",
                            abstract: false,
                            template: "<ui-view/>",
                            ncyBreadcrumb: {
                                label: "Dashboard"
                            }
                        }).state("dashboard",
                        {
                            url: "/",
                            templateUrl: "/App/Main/views/entries/entries.cshtml",
                            menu: "Dashboard",
                            ncyBreadcrumb: {
                                label: "Dashboard"
                            }
                    }).state("enter",
                        {
                            url: "/enter",
                            templateUrl: "/App/Main/views/entries/enter.cshtml",
                            menu: "Enter",
                            ncyBreadcrumb: {
                                label: "Enter"
                            }
                        }).state("entries",
                        {
                            url: "/entries",
                            templateUrl: "/App/Main/views/entries/entries.cshtml",
                            menu: "My Entries",
                            ncyBreadcrumb: {
                                label: "My Entries"
                            }
                        }).state("archived",
                        {
                            url: "/archived",
                            templateUrl: "/App/Main/views/entries/archived.cshtml",
                            menu: "Archived",
                            ncyBreadcrumb: {
                                label: "Archived"
                            }
                        })
                    .state("profile",
                    {
                        url: "profile",
                        templateUrl: "/App/Main/views/profile/profile.cshtml",
                        menu: "Profile",
                        ncyBreadcrumb: {
                            label: "Profile"
                        },
                        parent: "dashboard"
                    }).state("change-password",
                    {
                        url: "/change-password",
                        templateUrl: "/App/Main/views/profile/changePassword.cshtml",
                        menu: "Change Password",
                        ncyBreadcrumb: {
                            label: "Change Password"
                        },
                        parent: "dashboard"
                    });
                console.log("advertiser");

                $urlRouterProvider.otherwise("/");
            }

        }
    ]);
})();

**Comment by ismcagdas** [comment]
@smooney123 according to your state definitions, you have defined parent state several times. If user has more than one permissions like 'SuperAdmins' and 'Admins' this error happens.

So, you need to define parent state only once.
If this state is visible to all permissions, then you can define it outside of all permission checks.

**Comment by smooney123** [comment]
this should not be the case though, i logged out abp.auth.grantPermissions and it thinks every user has every permission. In my database this is not the case.

However in setpermissions inside TestAuthorizationProvider the following permissions are set and this is whats logged to the console in chrome. But in my seed method i only assign one user one permission

  public override void SetPermissions(IPermissionDefinitionContext context)
        {
            //Common permissions
            var pages = context.GetPermissionOrNull(PermissionNames.Pages);
            if (pages == null)
            {
                pages = context.CreatePermission(PermissionNames.Pages, L("Pages"));
            }

            pages.CreateChildPermission(PermissionNames.SuperAdmins, L("Pages.Super_Admin"));

            pages.CreateChildPermission(PermissionNames.Admins, L("Pages.Admins"));

            pages.CreateChildPermission(PermissionNames.Users, L("Pages.Users"));

            pages.CreateChildPermission(PermissionNames.TenantUsers, L("Pages.Tenant_Users"));

            pages.CreateChildPermission(PermissionNames.Advertisers, L("Pages.Advertisers"));

            pages.CreateChildPermission(PermissionNames.Drummers, L("Pages.Drummer"));

            //Host permissions
            pages.CreateChildPermission(PermissionNames.Tenants, L("Pages.Tenants"), multiTenancySides: MultiTenancySides.Host);
        }

**Comment by ismcagdas** [comment]
@smooney123 I'm talking about app.js, not the server-side part.
If you debug your app.js code, you will see that the lines of defining parent state will be hit more than once.

This is the definition I'm talking about. This must be executed or defined only once in app.js

```js
 $stateProvider
                .state("parent",

```

**Comment by smooney123** [comment]
i know that. but surely if(abp.auth.isGranted("Admins")) restricts this code to only the permissions i have assigned in the database?

**Comment by ismcagdas** [comment]
Depending on your ABP version, user might have permission according to your permission definition.
As I said, you can debug abp.js and see if multiple `if(abp.auth.isGranted("XXXXX"))` statements are passed or not.

**Comment by smooney123** [comment]
surely set permissions should have some sort of checking?

**Comment by smooney123** [comment]
why are all permissions assigned to all users?

**Comment by ismcagdas** [comment]
> why are all permissions assigned to all users?

It is not by default. Show your code for 
* defining permissions
* seed method
* static code definitions

**Comment by smooney123** [comment]
using Abp.Authorization;
     using Abp.Localization;
     using Abp.MultiTenancy;

     namespace Test.Authorization
     {
       public class TestAuthorizationProvider : AuthorizationProvider
      {
         public override void SetPermissions(IPermissionDefinitionContext context)
         {
            //Common permissions
            var pages = context.GetPermissionOrNull(PermissionNames.Pages);
            if (pages == null)
            {
                pages = context.CreatePermission("Pages");
            }

            pages.CreateChildPermission("SuperAdmins");

            pages.CreateChildPermission("Admins");

            pages.CreateChildPermission("Users");

            pages.CreateChildPermission("TenantUsers");

            pages.CreateChildPermission("Advertisers");

            pages.CreateChildPermission("Drummers");

            //Host permissions
            pages.CreateChildPermission("Tenants", multiTenancySides: MultiTenancySides.Host);
        }

        private static ILocalizableString L(string name)
        {
            return new LocalizableString(name, TestConsts.LocalizationSourceName);
        }
    }
}

**Comment by smooney123** [comment]
private void CreateRolesAndUsers()
          {
            //Admin role 

            var adminRole =
                _context.Roles.FirstOrDefault(r => r.TenantId == _tenantId && r.Name == StaticRoleNames.Tenants.Admin);
            if (adminRole == null)
            {
                adminRole = _context.Roles.Add(new Role(_tenantId, StaticRoleNames.Tenants.Admin,
                    StaticRoleNames.Tenants.Admin)
                { IsStatic = true });
                _context.SaveChanges();

                _context.Permissions.Add(
                         new RolePermissionSetting
                         {
                             TenantId = _tenantId,
                             Name = "Admins",
                             IsGranted = true,
                             RoleId = adminRole.Id
                         });

                _context.SaveChanges();
            }

            //admin user

            var adminUser =
                _context.Users.FirstOrDefault(u => u.TenantId == _tenantId && u.UserName == User.AdminUserName);
            if (adminUser == null)
            {

                adminUser = User.CreateTenantAdminUser(_tenantId, "admin@defaulttenant.com", "123qwe");
                adminUser.IsEmailConfirmed = true;
                adminUser.IsActive = true;
                adminUser.Avatar = ExtensionMethods.Avatar();


                _context.Users.Add(adminUser);
                _context.SaveChanges();

                //Assign Admin role to admin user
                _context.UserRoles.Add(new UserRole(_tenantId, adminUser.Id, adminRole.Id));
                _context.SaveChanges();

            }


            var basicUser = _context.Users.FirstOrDefault(u => u.TenantId == _tenantId && u.UserName == "Drummer");

            if (basicUser == null)
            {
                User user = new User
                {
                    UserName = "drummer",
                    EmailAddress = "drummer@aspnetboilerplate.com",
                    Password = new PasswordHasher().HashPassword(User.DefaultPassword),
                    Surname = "drummer",
                    IsEmailConfirmed = true,
                    IsActive = true,
                    Avatar = ExtensionMethods.Avatar(),
                    Name = "drummer",
                    TenantId = _tenantId
                };

                _context.Users.Add(user);
                _context.SaveChanges();

                Role role = new Role
                {
                    Name = "drummer",
                    DisplayName = "drummer",
                    IsStatic = true,
                    IsDefault = false,
                    IsDeleted = false,
                    TenantId = _tenantId
                };

                _context.Roles.Add(role);
                _context.SaveChanges();

                _context.UserRoles.Add(new UserRole(_tenantId, user.Id, role.Id));
                _context.SaveChanges();

                _context.Permissions.Add(
                                      new RolePermissionSetting
                                      {
                                          TenantId = _tenantId,
                                          Name = "Drummers",
                                          IsGranted = true,
                                          RoleId = role.Id
                                      });
                _context.SaveChanges();


                var advertiser =
                    _context.Users.FirstOrDefault(u => u.TenantId == _tenantId && u.UserName == "Advertiser");

                if (advertiser == null)
                {
                    User advertiserUser = new User
                    {
                        UserName = "advertiser",
                        EmailAddress = "advertiser@aspnetboilerplate.com",
                        Password = new PasswordHasher().HashPassword(User.DefaultPassword),
                        Surname = "advertiser",
                        IsEmailConfirmed = true,
                        IsActive = true,
                        Avatar = ExtensionMethods.Avatar(),
                        Name = "advertiser",
                        TenantId = _tenantId
                    };

                    _context.Users.Add(advertiserUser);
                    _context.SaveChanges();

                    Role advertiserRole = new Role
                    {
                        Name = "advertiser",
                        DisplayName = "advertiser",
                        IsStatic = true,
                        IsDefault = false,
                        IsDeleted = false,
                        TenantId = _tenantId
                    };

                    _context.Roles.Add(advertiserRole);
                    _context.SaveChanges();

                    _context.UserRoles.Add(new UserRole(_tenantId, advertiserUser.Id, advertiserRole.Id));
                    _context.SaveChanges();

                    _context.Permissions.Add(
                            new RolePermissionSetting
                            {
                                TenantId = _tenantId,
                                Name = "Advertisers",
                                IsGranted = true,
                                RoleId = advertiserRole.Id
                            });
                    _context.SaveChanges();

                }
            }
        }

**Comment by smooney123** [comment]
using Abp.MultiTenancy; 
    using Abp.Zero.Configuration;

     namespace Test.Authorization.Roles
     {
         public static class AppRoleConfig
        {
            public static void Configure(IRoleManagementConfig roleManagementConfig)
           {
               //Static host roles

            roleManagementConfig.StaticRoles.Add(
                new StaticRoleDefinition(
                    StaticRoleNames.Host.SuperAdmin,
                    MultiTenancySides.Host)
                );

            //Static tenant roles

            roleManagementConfig.StaticRoles.Add(
                new StaticRoleDefinition(
                    StaticRoleNames.Tenants.Admin,
                    MultiTenancySides.Tenant)
                );
        }
    }
}

**Comment by smooney123** [comment]
where and how do i create permissions?

**Comment by smooney123** [comment]
sorted my permission checker was not calling the base constructor
