### ISSUE TITLE
Remove EfCore Dependency in UserRegistrationManager

### ISSUE THREAD

**Issue by ryancyq** [aspnetboilerplate/module-zero-core-template#299]
`.ToListAsync()` is used in [UserRegistrationManager.cs#L62](https://github.com/aspnetboilerplate/module-zero-core-template/blob/master/aspnet-core/src/AbpCompanyName.AbpProjectName.Core/Authorization/Users/UserRegistrationManager.cs#L62) which causes the `UserRegistrationManager` in **Core** project to be dependent on **EFCore**

**Comment by hikalkan** [comment]
@ryancyq we added EfCore reference to domain/application layer intentionally.
This makes easy to use ToListAsync() and other async LINQ extensions for applications.
For most applications, it's not needed to be ORM indepdendent. If it requires, they can use `IAsyncQueryableExecuter` ([see](https://github.com/aspnetboilerplate/aspnetboilerplate/blob/dev/src/Abp/Linq/IAsyncQueryableExecuter.cs)) and remove EF Core dependency. But it does not implement every async method of EF Core.
Also, Adding EF Core reference makes possible to use `Include`, `ThenInclude` and other EF Core LINQ extensions.

We didn't want to use `IAsyncQueryableExecuter` to not make LINQ queries complicated and allow to use EF Core functionality easier..
