### ISSUE TITLE
Unable to hit CreateUser service from Postman

### ISSUE THREAD

**Issue by fahadshabbir** [aspnetboilerplate/module-zero-core-template#3]
Hi Hilal,

Sorry for the new-bie question but i have tried hitting the createuser service from Postman using different variations of request but i am unable to hit it. I even disabled the authorization but every time i get bad request. When i use the same values through web application i am able to  hit and create a new user. The token i used had relevant permissions.

Tremendous work by the way. Respect  :)

**Comment by arthurspa** [comment]
@fahadshabbir I may suggest you two things here. First, if you are not sending the header `X-Requested-With : XMLHttpRequest`, send it so you can tell your backend that you're making an AJAX call and will get a proper response message.

Second,  you'll need to create a controller to generate a antiforgery token (antiforgery is enabled by default for POST, PUT, PATCH and DELETE verbs in ABP) and send it in header on postsman actions. 

Example:

```
    [AbpMvcAuthorize]
    public class AntiForgeryController : MansysControllerBase
    {
        private readonly IAbpAntiForgeryManager _antiForgeryManager;

        public AntiForgeryController(IAbpAntiForgeryManager antiForgeryManager)
        {
            _antiForgeryManager = antiForgeryManager;
        }

        public string GetToken()
        {
            return _antiForgeryManager.GenerateToken();
        }
    }
```

The final bare header in postman would be something like this:

```
Content-Type:application/json
Authorization : Bearer {{Authorization}}
X-XSRF-TOKEN : {{X-XSRF-TOKEN}}
X-Requested-With : XMLHttpRequest
```

where `{{Authorization}}` is the authorization token, `{{X-XSRF-TOKEN}}` is the generated antiforgery token.

I hope it helps!

**Comment by fahadshabbir** [comment]
@arthurspa Thanks it worked :)
