### ISSUE TITLE
Register page should not include TenancyName

### ISSUE THREAD

**Issue by hikalkan** [aspnetboilerplate/module-zero-core-template#30]

**Comment by acjh** [comment]
Hi @hikalkan, how do we determine the relevant tenant in this case?

**Comment by hikalkan** [comment]
Register page has already a tenant switch area at the top:

![image](https://cloud.githubusercontent.com/assets/1210527/25386725/04d68caa-29d1-11e7-837a-c3075816e08e.png)

When you switch tenant with this area, it sets Abp.TenantId cookie and server can determine the current tenant (see https://www.aspnetboilerplate.com/Pages/Documents/Multi-Tenancy#determining-current-tenant).

**Comment by acjh** [comment]
Oh right, I thought tenant selection was removed completely. Thanks for the quick reply!
