### ISSUE TITLE
compiler.js is included in Angular --prod

### ISSUE THREAD

**Issue by Worthy7** [aspnetboilerplate/module-zero-core-template#303]
It really shouldn't be, since it's only used for JIT rendering, and --prod uses AOT.
Something from main.ts (I think maybe the AbpBoostrap) is causing it to pull the compiler in but I am not sure what.

![image](https://user-images.githubusercontent.com/4762399/42982045-57303e54-8c1a-11e8-8c2a-af9b7724d8ae.png)

just for comparison the default Angular.io example:
![image](https://user-images.githubusercontent.com/4762399/42982119-b41f0488-8c1a-11e8-879c-ba8f5087e900.png)

I wonder if we can also get moment out of this, probably not.

powershell:
`yarn install; yarn add webpack-bundle-analyzer --dev ; yarn run ng build --prod --stats-json ; yarn webpack-bundle-analyzer wwwroot/dist/stats.json`

**Comment by ismcagdas** [comment]
Thanks @Worthy7 I will check it. For now I have no idea :).

> I wonder if we can also get moment out of this, probably not.

We don't want to exclude moment, don't you use it ?

**Comment by Worthy7** [comment]
I suppose I do, but it's just that it's so massive... anyway still, compiler.js is in there for no reason

**Comment by ismcagdas** [comment]
I have tested this and it seems like compiler.js is not in the published output anymore.
