### ISSUE TITLE
Core version build depends on robocopy, so build fails on linux.

### ISSUE THREAD

**Issue by ismcagdas** [aspnetboilerplate/module-zero-core-template#305]
Moved from https://github.com/aspnetboilerplate/aspnetboilerplate/issues/3664

Version : 3.7.2
Type: .net core
Doing a dotnet build fails in linux, because there is a dependency on robocopy, which does not exist in linux.

How to reproduce:
Generate a combined .net core boilerplate solution from template.
Do a "dotnet build" on linux.

Error:
/bin/sh: 2: /tmp/tmpda90e7b4d99846c4936a6816fb7d9654.exec.cmd: robocopy: not found

Expectation:
I would expect a dotnet core application to build on any platform.

**Comment by alirizaadiyahsi** [comment]
Removed robocopy definition from source(aspnetboilerplate.com) and added these lines to documents to show manually copying files.

https://github.com/aspnetboilerplate/aspnetboilerplate/commit/33c07a68554859ddd21225e585790571e422a58d
