### ISSUE TITLE
Map enums as string through swagger

### ISSUE THREAD

**Issue by vdurante** [aspnetboilerplate/module-zero-core-template#307]
Wouldn't it make more sense to map enums as strings through `options.DescribeAllEnumsAsStrings();` on `Startup.cs > AddSwaggerGen` instead of doing it on AppEnums.ts? https://github.com/aspnetboilerplate/module-zero-core-template/blob/master/angular/src/shared/AppEnums.ts

**Comment by ismcagdas** [comment]
@vdurante we have considered this before https://github.com/aspnetboilerplate/module-zero-core-template/issues/259 but has problems.
