### ISSUE TITLE
Localization error

### ISSUE THREAD

**Issue by venkanna-indpro** [aspnetboilerplate/module-zero-core-template#315]
Currently i am working with ABP  .Net Core and AngularJS6.
I have created new language from admin/language menu and i have added language xml file also. The added language will be 'Swedish(sv-SE)'.
After creating language, when i changed the language it is giving the error.
The error will be like below attachment. Please help us to sort out the issue.

![languageerror](https://user-images.githubusercontent.com/10861129/43832350-cc311d0e-9b24-11e8-8830-e90a6220e96a.PNG)

**Comment by ismcagdas** [comment]
@venkanna-indpro it seems like Angular doesn't have sv-SE locale.
We can create a locale mapping between the original culture and the one angular supports.

In the mean time you can use "sv", "sv-AX" or "sv-FI".

**Comment by venkanna-indpro** [comment]
"sv" is orginal swedish.
"sv-FI" means Swedish-Finland.
"sv-AX" belongs to which country language code? i think, by mistakenly given "sv-AX" instead of "sv-SE"?

**Comment by ismcagdas** [comment]
@venkanna-indpro I don't know. Angular's source code contains this, see below screenshot;

![image](https://user-images.githubusercontent.com/4133525/43834574-353c533a-9b17-11e8-93a3-e8bc4fd9ad6e.png)

**Comment by ismcagdas** [comment]
You can see it in your node_modules folder as well.

**Comment by venkanna-indpro** [comment]
Okay. thank you for your immediate help. we will use sv-AX for now. 
It would be great, if we have sv-SE.js in Angular's source code.
