### ISSUE TITLE
Cannot be build

### ISSUE THREAD

**Issue by zorc** [aspnetboilerplate/module-zero-core-template#316]
41:29 Property 'avatorImgPath' does not exist on type 'Storage'.
    39 |     @Prop({type:Boolean,default:false}) showUnlock:boolean;
    40 |     get avatorPath(){
  > 41 |         return localStorage.avatorImgPath;
       |                             ^
    42 |     }
    43 |     async validator () {
    44 |         let loginModel={
ERROR in D:/Users/Zorc/Desktop/MyABPProject/vue/src/components/tags-page-opened.vue
70:22 Property 'pageOpenedList' does not exist on type 'Storage'.
    68 |         this.$store.commit('app/closePage', name);
    69 |         let pageOpenedList = this.$store.state.app.pageOpenedList;
  > 70 |         localStorage.pageOpenedList = JSON.stringify(pageOpenedList);
       |                      ^
    71 |         if (this.currentPageName === name) {
    72 |             let lastPageName = '';
    73 |             if (pageOpenedList.length > 1) {
ERROR in D:/Users/Zorc/Desktop/MyABPProject/vue/src/store/modules/app.ts
129:30 Property 'cachePage' does not exist on type 'Storage'.
    127 |         },
    128 |         initCachepage (state:AppState) {
  > 129 |             if (localStorage.cachePage) {
        |                              ^
    130 |                 state.cachePage = JSON.parse(localStorage.cachePage);
    131 |             }
    132 |         },
ERROR in D:/Users/Zorc/Desktop/MyABPProject/vue/src/store/modules/app.ts
130:59 Property 'cachePage' does not exist on type 'Storage'.
    128 |         initCachepage (state:AppState) {
    129 |             if (localStorage.cachePage) {
  > 130 |                 state.cachePage = JSON.parse(localStorage.cachePage);
        |                                                           ^
    131 |             }
    132 |         },
    133 |         removeTag (state:AppState, name:string) {
ERROR in D:/Users/Zorc/Desktop/MyABPProject/vue/src/store/modules/app.ts
149:26 Property 'pageOpenedList' does not exist on type 'Storage'.
    147 |             }
    148 |             state.pageOpenedList.splice(get.index, 1, openedPage);
  > 149 |             localStorage.pageOpenedList = JSON.stringify(state.pageOpenedList);
        |                          ^
    150 |         },
    151 |         clearAllTags (state:AppState) {
    152 |             state.pageOpenedList.splice(1);
ERROR in D:/Users/Zorc/Desktop/MyABPProject/vue/src/store/modules/app.ts
154:26 Property 'pageOpenedList' does not exist on type 'Storage'.
    152 |             state.pageOpenedList.splice(1);
    153 |             state.cachePage.length = 0;
  > 154 |             localStorage.pageOpenedList = JSON.stringify(state.pageOpenedList);
        |                          ^
    155 |         },
    156 |         clearOtherTags (state:AppState, vm:Vue) {
    157 |             let currentName = vm.$route.name;
ERROR in D:/Users/Zorc/Desktop/MyABPProject/vue/src/store/modules/app.ts
174:26 Property 'pageOpenedList' does not exist on type 'Storage'.
    172 |             });
    173 |             state.cachePage = newCachepage;
  > 174 |             localStorage.pageOpenedList = JSON.stringify(state.pageOpenedList);
        |                          ^
    175 |         },
    176 |         setOpenedList (state:AppState) {
    177 |             state.pageOpenedList = localStorage.pageOpenedList ? JSON.parse(localStorage.pageOpenedList) : [otherRouters.children[0]];
ERROR in D:/Users/Zorc/Desktop/MyABPProject/vue/src/store/modules/app.ts
177:49 Property 'pageOpenedList' does not exist on type 'Storage'.
    175 |         },
    176 |         setOpenedList (state:AppState) {
  > 177 |             state.pageOpenedList = localStorage.pageOpenedList ? JSON.parse(localStorage.pageOpenedList) : [otherRouters.children[0]];
        |                                                 ^
    178 |         },
    179 |         setCurrentPath (state:AppState, pathArr:Array<any>) {
    180 |             state.currentPath = pathArr;
ERROR in D:/Users/Zorc/Desktop/MyABPProject/vue/src/store/modules/app.ts
177:90 Property 'pageOpenedList' does not exist on type 'Storage'.
    175 |         },
    176 |         setOpenedList (state:AppState) {
  > 177 |             state.pageOpenedList = localStorage.pageOpenedList ? JSON.parse(localStorage.pageOpenedList) : [otherRouters.children[0]];
        |                                                                                          ^
    178 |         },
    179 |         setCurrentPath (state:AppState, pathArr:Array<any>) {
    180 |             state.currentPath = pathArr;
ERROR in D:/Users/Zorc/Desktop/MyABPProject/vue/src/store/modules/app.ts
191:30 Property 'cachePage' does not exist on type 'Storage'.
    189 |             if (!Util.oneOf(tagObj.name, state.dontCache)) {
    190 |                 state.cachePage.push(tagObj.name);
  > 191 |                 localStorage.cachePage = JSON.stringify(state.cachePage);
        |                              ^
    192 |             }
    193 |             state.pageOpenedList.push(tagObj);
    194 |         }
ERROR in D:/Users/Zorc/Desktop/MyABPProject/vue/src/views/main.vue
109:31 Property 'avatorImgPath' does not exist on type 'Storage'.
    107 |         }
    108 |         get avatorPath () {
  > 109 |           return localStorage.avatorImgPath;
        |                               ^
    110 |         }
    111 |         get cachePage () {
    112 |           return this.$store.state.app.cachePage;
ERROR in D:/Users/Zorc/Desktop/MyABPProject/vue/src/views/main.vue
178:24 Property 'currentPageName' does not exist on type 'Storage'.
    176 |           }
    177 |           this.checkTag(to.name);
  > 178 |           localStorage.currentPageName = to.name;
        |                        ^
    179 |         }
    180 |         @Watch('lang')
    181 |         langChange(){

**Comment by zorc** [comment]
Miss setItem and getItem

**Comment by ismcagdas** [comment]
@zorc which version do you use ? As we tested, this problem doesn't happen.

**Comment by ismcagdas** [comment]
Does it work if you use `yarn `to install npm dependencies instead of `npm install` ?

**Comment by dafeifei0218** [comment]
Thank you. After the execution of yarn install, after npm run server, browse http://localhost:8080/#/ is a blank page. What's wrong with no rendering?
![2018-08-11_102303](https://user-images.githubusercontent.com/10148878/43987267-d1d77d1a-9d50-11e8-9488-60905503e0e5.png)
The source is:

**Comment by acjh** [comment]
The error message is pretty straightforward. Enable JavaScript to continue.

**Comment by dafeifei0218** [comment]
@acjh How to enable it? Which file is modified? Which code? Does JavaScript need to be activated? I think this is the content of the index.html page in the public folder.

**Comment by acjh** [comment]
Enable it on your browser...

**Comment by zorc** [comment]
My solution is add setItem and getItem，for example：localStorage.getItem('cachePage')

**Comment by dafeifei0218** [comment]
@acjh 
It doesn't matter. My browser hasn't turned off JavaScript. It's the default setting.
If JavaScript is shut down, no other website can browse.
I think it should be the environment or code, or the configuration.

**Comment by dafeifei0218** [comment]
@ismcagdas Can you write an module-zero VUE 4 usage or deployment document? What environment to use? Which front-end projects?

**Comment by dafeifei0218** [comment]
I know why, because I didn't use Visual Studio to start xxxx.Web.Host. I thought that no need to start, Vue could also run.
