### ISSUE TITLE
Can't authenticate if Abp.AuthToken / Abp.EncryptedAuthToken exceeds 4KB

### ISSUE THREAD

**Issue by daniel-luberda** [aspnetboilerplate/module-zero-core-template#318]
- It can happen for projects which use a lot of `Roles` / `Claims` 
- Can't authenticate if `Abp.AuthToken` exceeds 4KB
- SignalR is not working if `Abp.EncryptedAuthToken` exceeds 4KB
- See current browser cookie entry size limits: http://browsercookielimits.squawky.net

Possible solutions:
- use local storage - https://stackoverflow.com/a/36367799/5064986
- Store auth tokens in chunks (several cookie entries)
- Add gzip compression option for the JWT Claims

**Comment by acjh** [comment]
Can you show your token?

**Comment by ismcagdas** [comment]
@daniel-luberda using local storage is good I think. We can work on it in the future. Thank you for pointing it out.

**Comment by ismcagdas** [comment]
It seems like this is a rare case and the ones face this problem can implement your solution.
