### ISSUE TITLE
How can I display AjaxResponse model on swagger for ApplicationService?

### ISSUE THREAD

**Issue by hemiaoio** [aspnetboilerplate/module-zero-core-template#32]
I want use it for all ApplicationService default.

**Comment by hikalkan** [comment]
Please write your framework type (web api or asp.net core), abp version etc.

**Comment by hemiaoio** [comment]
Sorry,I think I might not have made it clear.
Swagger model dosen't include AjaxResponse ,but the result include it. when I publish the doc for app,this document can't clearly express the API to output the results.
![qq 20170426220835](https://cloud.githubusercontent.com/assets/5441896/25439304/b041117a-2ace-11e7-9b94-66c18fc89729.png)
![qq 20170426220845](https://cloud.githubusercontent.com/assets/5441896/25439305/b0450c6c-2ace-11e7-8138-d13463590ee5.png)

**Comment by hikalkan** [comment]
OK, now understood. I'm not sure if that's possible since ABP dynamically change value on runtime, but swagger generated it based on method definition.
Can you create an issue to https://github.com/aspnetboilerplate/aspnetboilerplate/issues/new to check if we can do that in the framework level.

**Comment by hemiaoio** [comment]
OK!
