### ISSUE TITLE
Is there any major reason to use AdminBSB?

### ISSUE THREAD

**Issue by vdurante** [aspnetboilerplate/module-zero-core-template#320]
I like AdminBSB and have used it for all my projects, since it is the default implementation of the template. But I always wonder why it was chosen as the default theme. Why not another mainstream implementation, such as AdminLTE?

If I make a pull request migrating the implementation from AdminBSB to AdminLTE, would you accept it?

Thanks in advance.

**Comment by ismcagdas** [comment]
@vdurante we would really appriciate it. AdminBSB is a greate template but AdminLTE has a greated community.

We can offer AdminLTE as another option.

**Comment by vdurante** [comment]
@ismcagdas great. It may take a while since I will have to do it during the weekends, not to mention the fact that I am not an expert as you are, but I will eventually make a pull request implementing AdminLTE.

Thank you!
