### ISSUE TITLE
Error dialog when running new ASP.NET Core with Angular startup template

### ISSUE THREAD

**Issue by jessejjohnson** [aspnetboilerplate/module-zero-core-template#324]
Receiving the following dialog message after running a freshy downloaded ASP.NET Core 2.x with Angular startup template.

> An error has occurred! Error detail not sent by server.

This seems to only be an issue when running the ASP.NET Core `[Project Name].Web.Host` project with the `[Project Name].Web.Host` launch settings profile.

**Comment by maliming** [comment]
What is the specific content of the error log?

**Comment by jessejjohnson** [comment]
This issue looks to be due to a typo in the `launchSettings.json` located in the `[Project Name].Web.Host` project. Updating the port number of the `applicationUrl` to _21021_ fixed the issue (`applicationUrl` should match the `launchUrl`).

Pull request #323 was submitted to resolve this issue.

**Comment by jessejjohnson** [comment]
@maliming Is the Angular application configured to log application errors?
