### ISSUE TITLE
Localization and query conditions problem

### ISSUE THREAD

**Issue by dafeifei0218** [aspnetboilerplate/module-zero-core-template#328]
![qq 20180824090329](https://user-images.githubusercontent.com/10148878/44559644-0b2cbf80-a77e-11e8-8966-c9210f09c03e.png)

1. I downloaded the ModuleZero 4.0.1. netCore version from the template. 
This sentence in the Vue's  /src/lib/appconst.ts file needs to be changed to localize its 
own project name for use. After downloading the template, it needs to be a variable.

2. The query conditions of Users, Roles and Tenants list pages are useless. 
How can the background be parsed and searched? Is there no update code?

**Comment by maliming** [comment]
@Mohamedmtc If you are a paid user please create the issue at https://github.com/aspnetzero/aspnet-zero-core/issues/new instead

**Comment by dafeifei0218** [comment]
@ismcagdas 
![2018-08-24_224216](https://user-images.githubusercontent.com/10148878/44591188-a9a53900-a7ef-11e8-9a29-3169bdc798e3.png)
Without writing query conditions, click the screenshots after Find, that is, all data.

![2018-08-24_224327](https://user-images.githubusercontent.com/10148878/44591344-0b65a300-a7f0-11e8-854a-40d9774e97dd.png)
Write the "Role" condition and click the screenshots after Find. No filtered data

Other query conditions for Users and Tenants are also the same.
I looked at the code, and the background didn't receive filters.

**Comment by maliming** [comment]
@dafeifei0218 

You need to override the GetAll method and its arguments and filter within the method.

**Comment by ismcagdas** [comment]
Thanks @maliming.
@dafeifei0218 we need to either remove the filters from the UI or implement them on the server.

**Comment by maliming** [comment]
hi @dafeifei0218 
I didn't find these filters in the UI code of the template,
If it's your own filtering in UI, you need to override and implement filtering at the service layer.

**Comment by dafeifei0218** [comment]
@maliming @ismcagdas 
Yes, The service layer in template code does not have filters.
I would like to ask if there are official universal filters available. To parse keywords such as Where, Contains, StartWith, >, > = and so on.
You do not need to rewrite the GetAll method for each function.

**Comment by maliming** [comment]
Without these features, you need to implement it yourself.
