### ISSUE TITLE
No password validation

### ISSUE THREAD

**Issue by Worthy7** [aspnetboilerplate/module-zero-core-template#330]
https://github.com/aspnetboilerplate/module-zero-core-template/blob/f2deb3b0bef62b3843f0d78e425fc2b7c6df9483/aspnet-core/src/AbpCompanyName.AbpProjectName.Core/Authorization/Users/UserRegistrationManager.cs#L67

This line should instead be:
`CheckErrors(await _userManager.CreateAsync(user, plainPassword));`

and I think `
            user.Password = _passwordHasher.HashPassword(user, plainPassword);
`
can be removed.

**Comment by maliming** [comment]
@Worthy7 You are right. Thank you.
I will update the template

**Comment by Worthy7** [comment]
@maliming Watch out I think this breaks External Social logins, because the randomly generated password doesn't match `'Passwords must have at least one non alphanumeric character. Passwords must have at least one uppercase ('A'-'Z').'`

**Comment by maliming** [comment]
This is because of the default password specification for identity.
https://github.com/aspnet/Identity/blob/c7276ce2f76312ddd7fccad6e399da96b9f6fae1/src/Core/PasswordOptions.cs

We should call `UserManager.InitializeOptionsAsync(tenantId);` overwrite it
