### ISSUE TITLE
The validator does not match when verifying the password

### ISSUE THREAD

**Issue by liangshiw** [aspnetboilerplate/module-zero-core-template#332]
Identity password default specification RequireNonAlphanumeric is true

https://github.com/aspnetboilerplate/aspnetboilerplate/blob/d6765239d0003af4e2cce78fbaa33fe1c9c8377a/src/Abp.ZeroCore/Authorization/Users/AbpUserManager.cs#L594

It is set to false by default in abp
https://github.com/aspnetboilerplate/aspnetboilerplate/blob/e0ded5d8702f389aa1f5947d3446f16aec845287/src/Abp.Zero.Common/Zero/Configuration/AbpZeroSettingProvider.cs#L101

This will not match the rules during password checking
We should call` UserManager.InitializeOptionsAsync(tenantId);` overwrite it

**Comment by maliming** [comment]
https://github.com/aspnetboilerplate/module-zero-core-template/issues/330#issuecomment-416830649
