### ISSUE TITLE
Replace Form Inputs with @angular/material Components

### ISSUE THREAD

**Issue by lprichar** [aspnetboilerplate/module-zero-core-template#341]
The current template uses custom css and javascript for form inputs.  It would be much nicer to replace that custom code with components from @angular/material (https://material.angular.io/).  This would also provide additional components like the calendar picker in the same style to users.  I've done this in my projects and it makes minor UI changes, but overall look pretty similar.  

I'm willing to take a stab at it, but is there any reason why this wouldn't be a good idea?

**Comment by ismcagdas** [comment]
@lprichar this is a good idea, we can work on that for the next versions, thanks.

**Comment by lprichar** [comment]
Does that mean you would prefer to implement this @ismcagdas? Like I said, I don't mind doing it, I've done it for two projects now,  but it is a largish change and I don't want to step on any toes.

**Comment by ismcagdas** [comment]
@lprichar we would like a Pr but as far as I remember another guy wanted to implement a different theme for the module-zero-core-template.

I just want to be sure that, if he started to work on this, his work is not wasted.

**Comment by lprichar** [comment]
Ok, well let me know if you change your mind.  I can do it in multiple small, merge-friendly PR's if it helps.

**Comment by vdurante** [comment]
@ismcagdas @lprichar idk if you are talking about me, but a while ago I suggested re-implementing the angular theme using [ngx-admin](https://github.com/akveo/ngx-admin). I have also considered using [@angular/material](https://material.angular.io/). I constantly face several issues with AdminBSB and I would love to migrate to an angular-friendly theme.

I haven't made much progress, though. I've planned on working on it during the holidays.

**Comment by lprichar** [comment]
Oh, looks like ngx-admin finally got a datepicker.  That negates some of the benefit of the @angular/material argument.

**Comment by lprichar** [comment]
I'm still happy to do the @angular/material implementation though if you like, just lmk

**Comment by ismcagdas** [comment]
@lprichar @vdurante we prefer @angular/material. If you can create a PR for this, we will be happy to accept it.

Before starting to work on this PR, we can consider alternative themes which we can use with @angular/material as well. We are open to suggestions 😄

**Comment by lprichar** [comment]
When I've implemented @angular/material on my various ABP projects I've picked the default magenta theme that comes with it, but then overwritten the highlight colors in a separate less or sass file to match the color theme that the user picks in the right-hand flyout.  That way each user potentially has a different theme and all the glow effects and such all match.

**Comment by lprichar** [comment]
^ also that way, you don't have to upgrade everything at once, because all the controls look nearly identical to the existing controls

**Comment by vdurante** [comment]
@lprichar nice! I will study @angular/material for a few days. Thanks for the input.

**Comment by ismcagdas** [comment]
Thanks guys 😄 
As I said, we prefer @angular/material. If you can work on that we will be very happy.

**Comment by lprichar** [comment]
Does that mean @vdurante that you'd prefer to do this?  I've done it on two projects now, so I have some experience, and a little time coming up, but I'm happy to step aside and just answer questions if it's something you're excited about learning.

**Comment by vdurante** [comment]
@lprichar we can do it together. I don't see a reason to do it alone, since it is an open source project. I must warn you, though, that I am absolutely not an expert on angular.

**Comment by lprichar** [comment]
Ok, if we're going to pair perhaps it might be handy then to break it down into subtasks then.  I think it looks like this where task #1 is a prerequisite for both of us and the remaining tasks can be done in parallel:

1. Add support for date pickers (my usual first task on new abp project) and integrate @angular/material
    * Add `hammerjs` and `@angular/material` to package.json
    * Add indigo-pink.css to angular.json
    * Add HAMMER_GESTURE_CONFIG to root.module.ts (see https://stackoverflow.com/a/49020106/40783)
    * Add MatDatepickerModule, etc to app.module.ts
    * Add a couple of overrides to core.less to fix the date picker
2. Rewrite all add and edit dialogs to use `<mat-form-field>` and `matInput` and `mat-select` instead of all those divs
3. Overwrite the styles in a less or scss so the right-hand flyout theme picker works correctly
4. Rewrite the modal dialogs using `mat-dialog` (this is slightly more involved)

Anything else?

**Comment by vdurante** [comment]
@lprichar if I understood correctly, you intend to work on top of the current existing angular project instead of starting a new one? I was actually thinking about starting fresh with a new project and work 100% using @angular/material. My initial intent was eradicating AdminBSB.

**Comment by lprichar** [comment]
In my experience several small refactorings is less risky and more likely to succeed than a large rewrite.  AdminBSP isn't terrible, I just dislike all the javascript it uses and the non-Angular techniques everywhere.  I feel that can be removed systemically and avoid throwing babies out with bathwater.

**Comment by vdurante** [comment]
Ok, that is fair. Sooner or later, I am still gonna try to re-implement it from scratch, tho. Regarding the `mat-dialog`, I guess you will have to edit it in `abp-ng2-module`

**Comment by ismcagdas** [comment]
> In my experience several small refactorings is less risky and more likely to succeed than a large rewrite. 

I totally agree. 

We might not accept a total re-write so working on a total re-write might waste your time. So, only changing the AdminBsb is what we want 😄

**Comment by vdurante** [comment]
@lprichar @iyilm4z I am working here https://github.com/vdurante/module-zero-core-template

**Comment by iyilm4z** [comment]
Thanks. I took a look at your commit and i can say that we should use BrowserAnimationsModule instead of NoopAnimationsModule and [this](https://stackoverflow.com/a/43362943) explains why. We also don't need custom **gesture config** because BrowserAnimationsModule already does it.

**Comment by vdurante** [comment]
@iyilm4z regarding NoopAnimationsModule, I have removed it on my following commit. I had imported both BrowserAnimationsModule and NoopAnimationsModule. Thanks for the input. Regarding gesture config, @lprichar will have to give you an answer. As I understood from stackoverflow, this was necessary due to an issue. Idk if it was resolved and I just followed @lprichar command hahahha

**Comment by iyilm4z** [comment]
Hmm i see. So let's leave him decide tasks to be done and we do them:)

**Comment by iyilm4z** [comment]
Btw, how about other steps in his command? I think we should make a list of tasks and assign them each other of us. I don't want to spend my time on things you or @lprichar  or others already work on.

**Comment by vdurante** [comment]
@iyilm4z something you could do if you have the time is doing the same as this commit https://github.com/vdurante/module-zero-core-template/commit/caa591be28b1ef1e518770284d346bfc0ce91db3 on the users page!

**Comment by lprichar** [comment]
btw, don't know if you've run into to this yet, but I usually need to add this to core.less to make the material form fields fill out to 100%:

```
// force all material design form fields to be 100% wide
.mat-form-field {
    display: block !important;
}
```

**Comment by lprichar** [comment]
Also, I'm not really sure how to help out at this point.  I've never collaborated with multiple people on a feature, but I can either share a gist for my current solution to #3, or maybe make fork https://github.com/vdurante/module-zero-core-template/commits/master and make a PR into it?

**Comment by lprichar** [comment]
Oh, and to get date pickers to appear over the existing modals:

```
/* fixes date picker in modal, see https://stackoverflow.com/questions/42892584/angular-material-md-datepicker-inside-bootstrap-modal/47274694#47274694 */
.cdk-overlay-container {
    z-index: 1200 !important;
}
```

**Comment by iyilm4z** [comment]
Dear @lprichar ; @vdurante created issues on his fork. I assigned some of them to myself and i'm gonna to make PRs to his repo. Soon i'll do my first commit, please help us by checking our works out to do it correctly and better.

**Comment by iyilm4z** [comment]
@vdurante  @lprichar I'm done with [this](https://github.com/vdurante/module-zero-core-template/issues/6) enhancement. [Here](https://github.com/vdurante/module-zero-core-template/commit/48130ff94dccdbc61f186a8055a46c94ad8c86f5) is the change set, please inform me about your review. I also handled some missing localization stuff and did some changes for better ux like putting actions menu in first column of the table and using better/existing loading indicator(i also have few other ideas for better ux). At least i also used native material menu and button components even for some unimportant elements on the listing component. I think all of these changes up until now made by you and me will make other following changes easier for us because other pages would be mostly the same.

**Comment by vdurante** [comment]
@iyilm4z thanks for the commits! Really great job. Later I will remove the `abp.ui.setBusy` and use a `busy` directive I usually use in my projects. I avoid jQuery at all costs hahaha. I won't be able to work on it today since I was driving for my vacation. I will work on it tomorrow. Great night to everyone!

**Comment by lprichar** [comment]
Very nice @iyilm4z, so much less nested div's 👍 .  I added some comments, feel free to ignore.  The only one that might be worth some discussion is I agree with @vdurante, it'd be nice if we could get rid of the jQuery.  Maybe that's for another day though.

**Comment by lprichar** [comment]
I'm not seeing a task for #3 from above, but after downloading and running it, it still looks like the issue of consistent colors and theming isn't solved.  I'm going to take a stab at a PR for it targeted against vdurante's master.  Please stop me if that isn't desired or someone else is working on it.

**Comment by lprichar** [comment]
Just submitted a PR https://github.com/vdurante/module-zero-core-template/pull/10 lmk if you have questions or changes, I should be available off and on next couple of days

**Comment by iyilm4z** [comment]
@lprichar @vdurante thanks for your feedback, i’m so glad to hear that you liked it. i’m all open to your suggestions for sure. i just did my best in my knowledge and i’m doing all of these efforts only for learning purposes that’s why please explain every important thing by making detailed comments on them.

Dear Lee, i didn’t understand what is the relation between task number 3 and what we are working on. Are you sure on this task number?

**Comment by ismcagdas** [comment]
Done via https://github.com/aspnetboilerplate/module-zero-core-template/pull/382
