### ISSUE TITLE
Build error with Vue using yarn 

### ISSUE THREAD

**Issue by ChenZhaobin** [aspnetboilerplate/module-zero-core-template#343]
![1539744071 1](https://user-images.githubusercontent.com/16506634/47058786-20abec00-d1f9-11e8-9d4f-5d669dddbb88.jpg)

**Comment by mahaoming** [comment]
![_20181112201241](https://user-images.githubusercontent.com/31064550/48346851-61433c00-e6b7-11e8-99a0-491705065bff.png)
how to fix it？，also use yarn build，thanks

**Comment by acjh** [comment]
Change `^3.0.0` to `~3.0.0` in:

https://github.com/aspnetboilerplate/module-zero-core-template/blob/50a1a2d96164c980ecf4163ab843b2f40949b59c/vue/package.json#L14
