### ISSUE TITLE
bundleconfig.json lack of role/index.min.js

### ISSUE THREAD

**Issue by liangshiw** [aspnetboilerplate/module-zero-core-template#344]
https://github.com/aspnetboilerplate/module-zero-core-template/blob/master/aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/bundleconfig.json

This causes the publishing application to lose the index.min.js file

**Comment by ismcagdas** [comment]
Thanks a lot @liangshiw 👍
