### ISSUE TITLE
Removal of CheckErrors() calls in Application Service

### ISSUE THREAD

**Issue by rcyq** [aspnetboilerplate/module-zero-core-template#36]
As noted in the commit 2b00cc0, CheckErrors() calls are removed in application service but still remains is application service base, is there any reason by doing so?

**Comment by hikalkan** [comment]
CheckErrors call is removed from a few method calls because these methods are returning void (instead of IdentityResult) anymore. But CheckErrors method is still used by some other code.

**Comment by rcyq** [comment]
From what I saw from User & Role Managers, it seems that those methods are still returning ```IdentityResult```

For example:
```c#
public override async Task<IdentityResult> CreateAsync(TUser user)
{
    // more codes
}
```
https://github.com/aspnetboilerplate/module-zero/blob/master/src/Abp.ZeroCore/Authorization/Users/AbpUserManager.cs#L102

**Comment by hikalkan** [comment]
You are completely right. I don't remember how I did this mistake. Fixed it: https://github.com/aspnetboilerplate/module-zero-core-template/commit/ac816161c6dc2ee7131231a489eaf85a02a76ea8
Thank you for pointing this.
