### ISSUE TITLE
How to increase the limit on the size of the uploaded file?

### ISSUE THREAD

**Issue by XelaNimed** [aspnetboilerplate/module-zero-core-template#370]
I'm use template with ASP.Net Core 2.x, MVC and jQuery version 4.2.0. When I try to upload a file using the AJAX to controller, I get an [HTTP 404.13][1] error, which indicates that the maximum file size is exceeded. [Here][2] and [here][3] I found solutions to similar problem and try it solved, but solution either do not fit the pattern used, or I'm doing something wrong.

How to increase the maximum upload file size?

```csharp
// *.Web.Host\Startup\Program.cs 
// *.Web.Mvc\Startup\Program.cs
public static IWebHostBuilder CreateWebHostBuilder(string[] args) {
    return WebHost.CreateDefaultBuilder(args)
        .UseKestrel(options => { 
            // no effect...  I can only small files uploaded.
            // I assume that a standard limit of ~ 30 MB is used.
            options.Limits.MaxRequestBodySize = 1024 * 1024 * 1024; 
        })
        .UseStartup<Startup>();
}
```

[Question on StackOverflow](https://stackoverflow.com/q/53829487/3129992)

  [1]: https://docs.microsoft.com/en-us/iis/configuration/system.webServer/security/requestFiltering/requestLimits/
  [2]: https://stackoverflow.com/a/53428815/3129992
  [3]: https://github.com/aspnetboilerplate/aspnetboilerplate/issues/3657

**Comment by maliming** [comment]
Please share your project to Github, I will test it.

**Comment by XelaNimed** [comment]
@maliming  you can download ASP.Net Core 2.x template with MVC and jQuery from [here](https://aspnetboilerplate.com/Templates). Please make sure that in select box the target framework is Net. Core.

**Comment by maliming** [comment]
What is your upload code?
Please share it

**Comment by XelaNimed** [comment]
@maliming I have no problems with the code for file upload, since small files uploads to server successfully.
