### ISSUE TITLE
how to use  IDapperRepository<T> GetAllPaged() method? any example?

### ISSUE THREAD

**Issue by zsanhong** [aspnetboilerplate/module-zero-core-template#373]
I  Integrated Dapper in my application,but I don't know how to use `IDapperRepository<T> GetAllPaged()` method,any example ? Thanks a lot

**Comment by zsanhong** [comment]
the method is :
public virtual Task<IEnumerable<TEntity>> GetAllPagedAsync(
	Expression predicate,
	void pageNumber,
	Func<TEntity, bool> itemsPerPage,
	int sortingProperty,
	int ascending = true
),how to write predicate,Func<TEntity, bool> itemsPerPage?

**Comment by iyilm4z** [comment]
[Here](https://aspnetboilerplate.com/Pages/Documents/Dapper-Integration) is doc which shows how to integrate Dapper. 
[Here](https://github.com/aspnetboilerplate/aspnetboilerplate/tree/dev/test/Abp.Dapper.Tests) is tests which shows how to use Dapper.

Which version of Apb you are using? Latest version of [IDapperRepository](https://github.com/aspnetboilerplate/aspnetboilerplate/blob/42abe88814473ada2453f36caf80275dda861000/src/Abp.Dapper/Dapper/Repositories/IDapperRepositoryOfTEntityAndTPrimaryKey.cs#L140) has no method signature like you said.

**Comment by zsanhong** [comment]
I use Apb.Dapper 4.02

**Comment by zsanhong** [comment]
https://aspnetboilerplate.com/api-docs/html/M_Abp_Dapper_Repositories_AbpDapperRepositoryBase_2_GetAllPagedAsync.htm

**Comment by alirizaadiyahsi** [comment]
If you want to use `GetAllPagedAsync` then you should use `AbpDapperRepositoryBase` that is implemented `IDapperRepository`.

Example: 

````csharp
public class DapperRepositoryExample
{
    private readonly AbpDapperRepositoryBase<Person, int> _dapperPersonRepositoryBase;

    public DapperRepositoryExample(AbpDapperRepositoryBase<Person, int> dapperPersonRepositoryBase)
    {
        _dapperPersonRepositoryBase = dapperPersonRepositoryBase;
    }

    public async Task DoSomething()
    {
        _dapperPersonRepositoryBase.GetAllPagedAsync(...);
    }
}
````
