### ISSUE TITLE
Which is the strategy to update Services and Models in the React template?

### ISSUE THREAD

**Issue by MarcoMedrano** [aspnetboilerplate/module-zero-core-template#376]
The initial project is very nice, specially services and dtos are clean and nicer than the Angular template. But wonder how to update/generate them based on the ones in C#.

In the other templates we have the **refresh.bat** and also the **service.config.nswag** which are missing in this one.

I am pretty sure you guys have something in mind @ryoldash, @mhmtyasr, @smtkby. BTW thank u for the awesome template.

**Comment by ryoldash** [comment]
@MarcoMedrano Thanks for your feedback. We have plan to integrate **refresh.bat** and  **service.config.nswag** like features for React template. Now we have initiated React Native Integration project. After completing React Native Integration we will be implementing auto-generation of service layer accoding to backend services. @smtkby @mhmtyasr @zztrk @asilturk

**Comment by MarcoMedrano** [comment]
Well @ryoldash has the plan! so yeah clossing the issue.
