### ISSUE TITLE
Angular components broken on nswag refresh

### ISSUE THREAD

**Issue by SteveBurgess** [aspnetboilerplate/module-zero-core-template#379]
Hi,

I've just pulled down the latest release (4.3.1). Running the refresh for nswag appears to break the Angular user, role and tenant components.

I'm pretty new to Angular and ABP, so I could be well off the mark but...

I believe its related to this commit: https://github.com/aspnetboilerplate/module-zero-core-template/pull/367/commits/e8507a39589264d5b5dcf24ba61f9fd3291bddfc

It looks like userAppService, RoleAppService and TenantAppService have had their PagedResultRequestDto changed to PagedTenantResultRequestDto, PagedRolesResultRequestDto etc. to facilitate custom filtering.  

It looks like by default everything will work fine as the CreateFilteredQuery method on each app service has been set up to ignore these parameters if they aren't passed to it. However, once you run the nswag refresh the auto generated proxy code is expecting a number of new parameters to be passed to the getAll methods of the user, role and tenant service proxies, which in turn breaks the angular components.

Its easy enough to get around, I’m just passing undefined for those parameters, but I thought I’d just raise the issue.

Apologies if I’m missing something obvious!

**Comment by maliming** [comment]
@personball Can you have a look?

**Comment by personball** [comment]
@maliming I'll check it.

**Comment by ltm0203** [comment]
@SteveBurgess  Can you provide the code segment you modified? Let me verify the content.

**Comment by personball** [comment]
@SteveBurgess @maliming I'll try to fix it by implement keyword filter feature in angular template.

**Comment by personball** [comment]
Fix ng serve error after running nswag\refresh.bat first, List query filter feature on UI will come later.

**Comment by SteveBurgess** [comment]
> @SteveBurgess Can you provide the code segment you modified? Let me verify the content.

So, I've made changes in 3 places. 

roles -> roles.component.ts - line 30
From this:
`this.rolesService.getAll(request.skipCount, request.maxResultCount)`
To this:
`this.rolesService.getAll(undefined, undefined, undefined,request.skipCount, request.maxResultCount)`

tenants -> tenants.component.ts - line 29
From this:
`this._tenantService.getAll(request.skipCount, request.maxResultCount)`
To this:
`this._tenantService.getAll(undefined, undefined, undefined, request.skipCount, request.maxResultCount)`

users - users.component.ts - line 29
From this:
`this._userService.getAll(request.skipCount, request.maxResultCount)`
To this:
`this._userService.getAll(undefined, undefined, undefined, undefined, undefined, request.skipCount, request.maxResultCount)`

That appears to get everything up and running. As I mentioned in the OP I’m fairly new to ABP so doing it like this might have other unintended consequences.

**Comment by personball** [comment]
@SteveBurgess Thanks for your feeback.
