### ISSUE TITLE
How do I re-run Seed method?

### ISSUE THREAD

**Issue by vdurante** [aspnetboilerplate/module-zero-core-template#38]
Apparently, once seed method has run, if I re-run `dotnet ef database update`, the seed method is not run again. How do I force running the seed method?

Thank you

**Comment by hikalkan** [comment]
Hi,

Entity Framework Core does not support Seeding database on running migrations (you can search on the web).
As a current workaround, we do it when the application starts (https://github.com/aspnetboilerplate/module-zero-core-template/blob/master/aspnet-core/src/AbpCompanyName.AbpProjectName.EntityFrameworkCore/EntityFrameworkCore/AbpProjectNameEntityFrameworkModule.cs#L40).
