### ISSUE TITLE
ReferenceError: 'Symbol' (reactjs template)

### ISSUE THREAD

**Issue by maliming** [aspnetboilerplate/module-zero-core-template#393]
https://github.com/aspnetboilerplate/aspnetboilerplate/issues/4188
@rromerodev
Hi, i need help.

im running the react template with abp, but a get the following error on IE11

ReferenceError: 'Symbol' is not defined .

Anonymous function
C:/Lab/abp/4.4.0/reactjs/node_modules/mobx/lib/mobx.module.js:204

![2019-01-16 15_49_27-react app - internet explorer](https://user-images.githubusercontent.com/46759854/51271904-8306bb00-19a7-11e9-80d8-729edd15f810.png)

**Comment by acjh** [comment]
Need `Symbol` polyfill, as done for Angular:
https://github.com/aspnetboilerplate/module-zero-core-template/blob/5c4a038eb704a3cffad9794a7e7f9f2af450a766/angular/src/polyfills.ts#L22

**Comment by alirizaadiyahsi** [comment]
Solution: https://github.com/facebook/create-react-app/tree/master/packages/react-app-polyfill

But there is another issue: 

> Error: [mobx] MobX 5+ requires Proxy and Symbol objects. If your environment doesn't support Proxy objects, please downgrade to MobX 4. For React Native Android, consider upgrading JSCore.

To fix this: it is obvious as error massage say: Downgrade MobX to v4.

Check this: https://github.com/mobxjs/mobx/issues/1634#issuecomment-404833137

**Comment by maliming** [comment]
@alirizaadiyahsi 
I tried to fix it but encountered other errors.

```
\node_modules\mobx\lib\types\observableset.d.ts
(31,5): error TS2416: Property '[Symbol.toStringTag]' in type 'ObservableSet<T>' is not assignable to the same property in base type 'Set<T>'.
  Type 'string' is not assignable to type '"Set"'.
```

![image](https://user-images.githubusercontent.com/6908465/51880765-72950e00-23b3-11e9-9f3e-58ac49c47180.png)

**Comment by alirizaadiyahsi** [comment]
I tried 1 step and get second error, you tried second step you are still getting error. May be there will be more error.

**Comment by ismcagdas** [comment]
Closing as wontfix
