### ISSUE TITLE
Uncaught ReferenceError: abp is not defined

### ISSUE THREAD

**Issue by alpersilistre** [aspnetboilerplate/module-zero-core-template#395]
Hello, I am sorry that I had to open this issue in this repository. I hope this can help me and anyone in the future who encounter something like this. I already opened a [question](https://stackoverflow.com/questions/54310496/how-to-solve-uncaught-referenceerror-abp-is-not-defined-at-module-src-main-t) on StackOverflow two days ago which explains with more detail and I haven't been able to figure out how to solve since then.

I have started to upgrade angular version of the asp net zero-based project which is working fine for last 2 years with Angular version 2. I managed to update it to version 5 without any big issue. Then I followed the angular update guideline and update it to version 7. I also updated 'abp-ng2-module' and 'abp-web-resources' to their latest versions since I checked this repository and saw that angular app also is version 7 and these 2 packages updated along with it. I can compile the project without an error, however, at the start of the client project, I get this error;
```
main.ts:20 Uncaught ReferenceError: abp is not defined
    at Module../src/main.ts (main.ts:20)
    at __webpack_require__ (bootstrap:78)
    at Object.0 (password-complexity-validator.directive.ts:11)
    at __webpack_require__ (bootstrap:78)
    at checkDeferredModules (bootstrap:45)
    at Array.webpackJsonpCallback [as push] (bootstrap:32)
    at main.js:1
```
This is the main.ts file;
```
import './polyfills.ts';

import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { enableProdMode, ChangeDetectorRef } from '@angular/core';
import { environment } from './environments/environment';
import { AccountModule } from './account/account.module';
import { AppConsts } from './shared/AppConsts';
import { AppPreBootstrap } from './AppPreBootstrap';
import { AppModule } from './app/app.module';

import * as moment from 'moment';

import 'moment/min/locales.min';
import 'moment-timezone';

if (environment.production) {
    enableProdMode();
}

abp.ui.setBusy();
AppPreBootstrap.run(() => {
    if (abp.session.userId) {
        AppPreBootstrap.bootstrap(AppModule).then(() => {
            abp.ui.clearBusy();
        });
    } else {
        $('body').attr('class', 'page-md login');
        AppPreBootstrap.bootstrap(AccountModule).then(() => {
            abp.ui.clearBusy();
        });
    }
});

//A workaround to make angular-cli finding the startup module!
var b = false; if (b) { platformBrowserDynamic().bootstrapModule(AccountModule); }
```
I compared previous versions of the 'abp-web-resources' with this version and there weren't any major changes. Somehow, 'abp' namespace was not available when I run the client project. The weird thing is, I can navigate to 'abp.d.ts' file from the main.ts file when I click Go To Definition over 'abp'.

I am putting the screenshot of the tsconfig.json and scripts part of the angular.json to keep the issue shorter.

![angular](https://user-images.githubusercontent.com/6996763/51673600-6be74f00-1fdf-11e9-9bbc-1baf76271add.JPG)

I have added 'include' and 'exclude' to this tsconfig.json file after updated to version 7 and tried every combination of those. I would be thankful if you can point me in any direction about how can I use 'abp' namespace inside the main.ts file like I was using in pre angular version 6. Thank you.

**Comment by ismcagdas** [comment]
Do you have this line in your project https://github.com/aspnetboilerplate/module-zero-core-template/blob/master/angular/src/typings.d.ts#L2 ?

**Comment by alpersilistre** [comment]
Yes, I have. This is the top of the typings.d.ts;
```
///<reference path="../node_modules/@types/jquery/index.d.ts"/>
///<reference path="../node_modules/@types/jstree/index.d.ts"/>
///<reference path="../node_modules/abp-web-resources/Abp/Framework/scripts/abp.d.ts"/>
///<reference path="../node_modules/abp-web-resources/Abp/Framework/scripts/libs/abp.jquery.d.ts"/>
///<reference path="../node_modules/abp-web-resources/Abp/Framework/scripts/libs/abp.signalr.d.ts"/>
///<reference path="../node_modules/moment/moment.d.ts"/>
///<reference path="../node_modules/@types/moment-timezone/index.d.ts"/>
///<reference path="../node_modules/@types/bootstrap/index.d.ts"/>
///<reference path="../node_modules/@types/toastr/index.d.ts"/>

// Typings reference file, see links for more information
// https://github.com/typings/typings
// https://www.typescriptlang.org/docs/handbook/writing-declaration-files.html
```

**Comment by ismcagdas** [comment]
When I check the history of https://github.com/aspnetboilerplate/module-zero-core-template/blob/master/angular/src/main.ts, it seems like we have never used "abp" in it.

Does your angular.json file contains "node_modules/abp-web-resources/Abp/Framework/scripts/abp.js" ?
If so, you need to change your main.ts file to something like https://github.com/aspnetboilerplate/module-zero-core-template/blob/master/angular/src/main.ts and run AppPreBootstrap in the root module.

**Comment by alpersilistre** [comment]
Yes, the 'abp.js' file exists in the node_modules/abp-web-resources/Abp/Framework/scripts/ folder.

I have changed the main.ts file as you suggest, it is bootstrapping the root module right now. Inside the root module, I am calling the appInitializerFactory like in this repository.

```
export function appInitializerFactory() {
    return () => {
        abp.ui.setBusy();
        AppPreBootstrap.run(() => {
            if (abp.session.userId) {
                AppPreBootstrap.bootstrap(AppModule).then(() => {
                    abp.ui.clearBusy();
                });
            }
            else {
                $('body').attr('class', 'page-md login');
                AppPreBootstrap.bootstrap(AccountModule).then(() => {
                    abp.ui.clearBusy();
                });
            }
        });
    }
}
```

I am getting the same error. ERROR ReferenceError: abp is not defined at Array.<anonymous> (root.module.ts:22)

I believe 'abp' is not defined for the entire application but not specific to a single file. Even if I remove all of the 'abp' references from the RootModule file, the same error occurs in token.service.js inside the  node_modules/abp-ng2-module/dist/src/src/auth/token.service.js line 12 which is inside the TokenService.prototype.getToken function.

**Comment by ismcagdas** [comment]
@alpersilistre I actually asked for **angular.json**, could you share it as well ?

**Comment by alpersilistre** [comment]
@ismcagdas Sorry, I didn't include it in the thread. I added that in my question on SO. This is my package.json [file](https://gist.github.com/alpersilistre/b83483cf84ff7530f684fa4f387dd573).

**Comment by ismcagdas** [comment]
@alpersilistre https://gist.github.com/alpersilistre/6eb901f1754339f48a52cbb7a77445ce seems fine. Is ther a way to share your project privately so we can check it ?

**Comment by acjh** [comment]
@alpersilistre Please create a repro that is forked from this repo.
