### ISSUE TITLE
Property IsStatic in Role should not be created or updated

### ISSUE THREAD

**Issue by personball** [aspnetboilerplate/module-zero-core-template#398]
Property `IsStatic` in Role should not be created or updated.

in `CreateRoleDto`  
https://github.com/aspnetboilerplate/module-zero-core-template/blob/master/aspnet-core/src/AbpCompanyName.AbpProjectName.Application/Roles/Dto/CreateRoleDto.cs#L25

and `RoleDto`(update api)  
https://github.com/aspnetboilerplate/module-zero-core-template/blob/master/aspnet-core/src/AbpCompanyName.AbpProjectName.Application/Roles/Dto/RoleDto.cs#L26

also, in `RoleEditDto`  
https://github.com/aspnetboilerplate/module-zero-core-template/blob/d16866c48fa8b152ff2e1363ff71efa84c5ebe88/aspnet-core/src/AbpCompanyName.AbpProjectName.Application/Roles/Dto/RoleEditDto.cs#L21

It should be `IsDefault`

see https://github.com/aspnetboilerplate/aspnetboilerplate/blob/e0ded5d8702f389aa1f5947d3446f16aec845287/src/Abp.Zero.Common/Authorization/Roles/AbpRoleBase.cs#L54

**Comment by personball** [comment]
We should return `IsStatic` to UI, but make name of a static role not editable, also, should config MapProfile to ignore `IsStatic` when map `RoleDto` into `Role`.

**Comment by personball** [comment]
One more question, can we delete a **Static Role**?

**Comment by acjh** [comment]
From the documentation on [Dynamic vs Static Roles](https://aspnetboilerplate.com/Pages/Documents/Zero/Role-Management#dynamic-vs-static-roles):

> Static role: A static role has a known name (like 'admin') which can not be changed (we can change the display name). It exists on the system startup and **can not be deleted**. This way, we can write code based on a static role's name.

**Comment by alirizaadiyahsi** [comment]
Hi @personball, static role is already not created, updated or deleted. `IsStatic` property on `RoleEditDto` is for check role if it is static to prevent update its name.

But `IsStatic` on `CreateRoleDto` and `RoleDto` is looking unnecessary. I will remove them.
