### ISSUE TITLE
ReactJs template production not working

### ISSUE THREAD

**Issue by EddyFerro** [aspnetboilerplate/module-zero-core-template#402]
**Steps to reproduce:**
1) npm run build
2) Run a local server or upload via FTP
3) Make sure to have a running local backend 

**This is the Error:**
Error: MobX injector: Store 'e' is not available! Make sure it is provided by some Provider.

**Comment by ryoldash** [comment]
I have fixed this issue and created a pull request. This is not duplicate of #393.

**Comment by ismcagdas** [comment]
Fixed via https://github.com/aspnetboilerplate/module-zero-core-template/pull/403
