### ISSUE TITLE
Duplicate identifier abp

### ISSUE THREAD

**Issue by siva26051990** [aspnetboilerplate/module-zero-core-template#413]
I have the following error in **src/lib/abp.d.ts** 

![abp_duplicate_error](https://user-images.githubusercontent.com/16757430/52853149-9de95e00-3112-11e9-89d5-d5b1a68c347a.png)

It says that there is a duplicate definition of **abp** inside **src/lib/abp.js**.

**Comment by ismcagdas** [comment]
@siva26051990 are you using ABP's Angular 7 template ?
