### ISSUE TITLE
Module parse failed: 'import' and 'export' may only appear at the top level (39:24)

### ISSUE THREAD

**Issue by rexyluther** [aspnetboilerplate/module-zero-core-template#419]
In root.module.ts, import in a appInitializerFactory gives me an error.

 ```
if (shouldLoadLocale()) {
                            const angularLocale = convertAbpLocaleToAngularLocale(abp.localization.currentLanguage.name);
                            import(`@angular/common/locales/${angularLocale}.js`)
                                .then(module => {
                                    registerLocaleData(module.default);
                                    resolve(result);
                                }, reject);
                        } else {
                            resolve(result);
                        }
```
so I changed System.import
but it says System.import is deprecated. I changed require but it gives me an error.
How can I solve this problem?

**Comment by ismcagdas** [comment]
> In root.module.ts, import in a appInitializerFactory gives me an error.

Could you share the error as well ?

**Comment by rexyluther** [comment]
```
client:168 ./src/root.module.ts 39:24
Module parse failed: 'import' and 'export' may only appear at the top level (39:24)
You may need an appropriate loader to handle this file type.
|                     if (shouldLoadLocale()) {
|                         var angularLocale = convertAbpLocaleToAngularLocale(abp.localization.currentLanguage.name);
>                         import("@angular/common/locales/" + angularLocale + ".js")
|                             .then(function (module) {
|                             registerLocaleData(module.default);
```

**Comment by ismcagdas** [comment]
@rexyluther do you have a higher module than root.module ? Do you get the same problem when you download a fresh Angular template from https://aspnetboilerplate.com/Templates ?

**Comment by rexyluther** [comment]
root.module.ts is highest module and yes that's where I got template from.

**Comment by ismcagdas** [comment]
@rexyluther so you haven't done any modification to the template. If so, could you share your local angular-cli, node and npm versions ?

Also, have you installed packages using yarn ?

**Comment by rexyluther** [comment]
I have downloaded (version 4.6) again and tried. It does not give me any error this time.
Maybe I had old version. 
Thank you.

**Comment by alecsg77** [comment]
I got the same error, after I ran `npm audit fix`
I compared the original package.json with the my current version, and I discovered these two relevant changes
1. `"@angular-devkit/build-angular": "~0.11.3"` -> `"@angular-devkit/build-angular": "^0.13.7"`
2. `"@angular/compiler-cli": "^7.1.3"` -> `"@angular/compiler-cli": "^7.2.11"`

I rolled back and now it works again.

**Comment by ismcagdas** [comment]
@alecsg77 we will upgrade angular packages for the next release. Thank you for informing us.
