### ISSUE TITLE
Duplicate web.config / Web.config

### ISSUE THREAD

**Issue by matthiaswelz** [aspnetboilerplate/module-zero-core-template#423]
I just noticed that there are two web.config in the module-zero-core-template/angular/ folder: One with an uppercase W and one with a lowercase w (**with different content!**):

* module-zero-core-template/angular/web.config
* module-zero-core-template/angular/Web.config

Suggestion: One of them should be deleted.
I am not sure which one is the right one.

**Comment by ismcagdas** [comment]
@matthiaswelz I thought that this was resolved. We will check it again, thank you for reporting it.

**Comment by vdurante** [comment]
Idk if this is related, but on windows whenever I extract the generated zip from the website, it asks me if I want to overwrite Web.config with another web.config. Maybe this is an issue with the generation of the zip file or something.
