### ISSUE TITLE
Angular 2 issue

### ISSUE THREAD

**Issue by abdulrahmanmokhlef** [aspnetboilerplate/module-zero-core-template#424]
How can i solve this  problem?? it appears when i run the application and the build is aborted.

Web.Host/node_modules/abp-ng2-module/node_modules/@angular/http/http.d.ts, found version 4, expected 3, resolving symbol ABP_HTTP_PROVIDER

**Comment by ismcagdas** [comment]
@abdulrahmanmokhlef 

* Which version of abp-ng2-module do you use ? 
* Which version of Angular do you use ?

**Comment by abdulrahmanmokhlef** [comment]
Here is package.json
@ismcagdas 
"name": "abp-zero-template",
  "version": "4.0.0",
  "license": "MIT",
  "angular-cli": {},
  "scripts": {
    "build:prod": "ng build --prod",
    "ng": "ng",
    "start": "ng serve --host 0.0.0.0 --port 4200",
    "hmr": "ng serve --host 0.0.0.0 --port 4200 4201 --hmr -e=hmr",
    "test": "ng test",
    "pree2e": "webdriver-manager update --standalone false --gecko false",
    "e2e": "protractor"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^4.3.1",
    "@angular/common": "^4.3.1",
    "@angular/compiler": "^4.3.1",
    "@angular/core": "^4.3.1",
    "@angular/forms": "^4.3.1",
    "@angular/http": "^7.2.10",
    "@angular/platform-browser": "^4.3.1",
    "@angular/platform-browser-dynamic": "^4.3.1",
    "@angular/router": "^4.3.1",
    "@ngui/popup": "^0.5.1",
    "@types/bootstrap": "^3.3.33",
    "@types/jquery": "^2.0.41",
    "@types/jquery.blockui": "0.0.27",
    "@types/jstree": "^3.3.34",
    "@types/lodash": "^4.14.62",
    "@types/moment": "^2.13.0",
    "@types/moment-timezone": "^0.2.34",
    "@types/node": "^6.0.42",
    "@types/signalr": "^2.2.33",
    "@types/tether": "^1.4.2",
    "@types/toastr": "^2.1.33",
    "abp-ng2-module": "^1.2.0",
    "abp-web-resources": "^2.2.1",
    "angular2-counto": "^1.2.3",
    "block-ui": "^2.70.1",
    "bootstrap": "^3.3.7",
    "bootstrap-daterangepicker": "^2.1.25",
    "bootstrap-select": "^1.12.2",
    "bootstrap-switch": "^3.3.4",
    "codelyzer": "^2.1.1",
    "core-js": "^2.4.1",
    "datamaps": "^0.5.8",
    "eonasdan-bootstrap-datetimepicker": "^4.17.47",
    "famfamfam-flags": "^1.0.0",
    "flot": "^0.8.0-alpha",
    "font-awesome": "^4.7.0",
    "jasmine-spec-reporter": "^3.3.0",
    "jquery": "^3.1.1",
    "jquery-migrate": "^3.0.0",
    "jquery-slimscroll": "^1.3.8",
    "jquery-sparkline": "^2.4.0",
    "jquery.flot.tooltip": "^0.9.0",
    "jquery.inputmask": "^3.3.4",
    "jquery.uniform": "^4.2.0",
    "jqueryui": "^1.11.1",
    "js-cookie": "^2.1.4",
    "jstree": "^3.3.4",
    "karma": "^1.6.0",
    "localforage": "^1.5.0",
    "lodash": "^4.17.4",
    "moment": "^2.18.1",
    "moment-timezone": "^0.5.13",
    "morris.js": "^0.5.0",
    "ng-recaptcha": "^2.0.2",
    "ng2-file-upload": "^1.2.1",
    "ng2-opd-popup": "^1.1.21",
    "ng2modules-easypiechart": "^0.0.4",
    "ng2modules-flot": "^0.0.1",
    "ngx-bootstrap": "^1.8.0",
    "primeng": "^4.1.1",
    "push.js": "0.0.12",
    "raphael": "^2.2.7",
    "rtl-detect": "^1.0.0",
    "rxjs": "^5.4.2",
    "signalr": "^2.2.1",
    "simple-line-icons": "^2.4.1",
    "spin.js": "^2.3.2",
    "sweetalert": "^1.1.3",
    "tether": "^1.4.0",
    "timeago": "^1.6.1",
    "toastr": "^2.1.2",
    "ts-helpers": "^1.1.2",
    "ts-node": "~3.2.0",
    "typescript": "2.4",
    "waypoints": "^4.0.1",
    "zone.js": "0.8.7"
  },
  "devDependencies": {
    "@angular/cli": "1.2.4",
    "@angular/compiler-cli": "^4.3.1",
    "@angularclass/hmr": "^2.1.3",
    "@angularclass/hmr-loader": "^3.0.4",
    "@types/grecaptcha": "^2.0.31",
    "@types/jasmine": "^2.6.2",
    "@types/jasminewd2": "~2.0.2",
    "@types/morris.js": "^0.5.6",
    "@types/node": "^6.0.69",
    "codelyzer": "~3.0.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "nswag": "10.6.0",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.3.2",
    "typescript": "~2.4.0"
  }
}

**Comment by ismcagdas** [comment]
You are using "abp-ng2-module": "^1.2.0", so you must update to to the latest version which is 3.2.5.

**Comment by abdulrahmanmokhlef** [comment]
@ismcagdas  going to try it and back to you again

**Comment by abdulrahmanmokhlef** [comment]
@ismcagdas  that introduced new errors 

/message/message.service.ts (7,16): Expected 1-2 arguments, but got 3.
/src/app/shared/layout/profile/change-profile-picture-modal.component.ts (7,31): Cannot find module '@abp/abpHttp'.


and the same error

ERROR in Metadata version mismatch for module E:/Agile Innovations/Projects/tact.cards/Trunk/src/tactcards.Web.Host/node_modules/@angular/http/http.d.ts, found version 4, expected 3, resolving symbol AppModule in E:/Agile Innovations/Projects/tact.cards/Trunk/src/tactcards.Web.Host/src/app/app.module.ts, resolving symbol AppModule in E:/Agile Innovations/Projects/tact.cards/Trunk/src/tactcards.Web.Host/src/app/app.module.ts

**Comment by ismcagdas** [comment]
It seems like you are using AspNet Zero. Are you able to report on https://github.com/aspnetzero/aspnet-zero-core ?

**Comment by abdulrahmanmokhlef** [comment]
@ismcagdas  Thank you.
  I've solved the problem  by changing version 4 to 3 from .metadata.json files.

**Comment by ismcagdas** [comment]
Great 😄
