### ISSUE TITLE
The key "WebSiteRootAddress" should be changed to "ServerRootAddress"?

### ISSUE THREAD

**Issue by jakeuj** [aspnetboilerplate/module-zero-core-template#426]
[appsettings.Staging.json#L6](https://github.com/aspnetboilerplate/module-zero-core-template/blob/ff80a5a57ed700be57814437a6bc08f3e6324b8c/aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Host/appsettings.Staging.json#L6)

`"WebSiteRootAddress": "http://localhost:9902/",`

[Startup.cs#L121](https://github.com/aspnetboilerplate/module-zero-core-template/blob/ff80a5a57ed700be57814437a6bc08f3e6324b8c/aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Host/Startup/Startup.cs#L121)

`options.SwaggerEndpoint(_appConfiguration["App:ServerRootAddress"].EnsureEndsWith('/') + "swagger/v1/swagger.json", "AbpProjectName API V1");`

The key "WebSiteRootAddress" should be changed to "ServerRootAddress"?

**Comment by ismcagdas** [comment]
Thanks @jakeuj for reporting.
