### ISSUE TITLE
Abp.Authorization.AbpAuthorizationException: Current user did not login to the application!

### ISSUE THREAD

**Issue by wabixia** [aspnetboilerplate/module-zero-core-template#447]
Hi, when I download my dotnet core MVC project from the website, then I setup the Database correctly, but when I used username "admin" and password "123qwe" to login , it didn't work, after clicking login button, it still on login page and did not show me home/index page, and it didn't return any error message on the page. then I check the log message, it shown "Abp.Authorization.AbpAuthorizationException: Current user did not login to the application!", could anyone shed me some lights on this issue? thanks.

[Logs.txt](https://github.com/aspnetboilerplate/module-zero-core-template/files/3106131/Logs.txt)

**Comment by maliming** [comment]
* Your Abp package version.
* Your base framework: .Net Framework or .Net Core.
* Exception message and stack trace if available.
* **Steps needed to reproduce the problem.**

**Comment by wabixia** [comment]
1. Abp package version 4.5.0
2. .Net Core 2.2
3. I attached the log file on the above issue
4. Go to https://aspnetboilerplate.com/Templates, select ASP.NET Core 2.x and Multi PAge Web Application, then create my project, Follow the tutorial step:
Open your solution in Visual Studio 2017 v15.3.5+ and build the solution.
Select the 'Web.Mvc' project as the startup project.
Check the connection string in the appsettings.json file of the Web.Mvc project, change it if you want.
Open Package Manager Console and run the Update-Database command to create your database (ensure that the Default project is selected as .EntityFrameworkCore in the Package Manager Console window).
Run the application.

then Go to login page, the issue occured, 

thanks.

**Comment by liangshiw** [comment]
I will check this

**Comment by liangshiw** [comment]
@wabixia  I can't reproduce your problem , Can you use the template to reproduce the problem and upload it as an attachment?

**Comment by wabixia** [comment]
@liangshiw 
[MyCoreProject.zip](https://github.com/aspnetboilerplate/module-zero-core-template/files/3106381/MyCoreProject.zip)
Attached is my package

**Comment by maliming** [comment]
@wabixia

As liangshiw  said, using your project code can't be reproduced.

![GIF](https://user-images.githubusercontent.com/6908465/56567042-a795b300-65e6-11e9-84e8-23a0807dcc06.gif)

**Comment by liangshiw** [comment]
Using your project code can't be reproduced
![xxx](https://user-images.githubusercontent.com/16813853/56567391-62be4c00-65e7-11e9-9e5f-c0b0a1a5eada.gif)

**Comment by wabixia** [comment]
@liangshiw Thanks for your patient, I notice the little different between my login page with yours, i still struggling  with this,  and my visual studio version is 2019 community, thanks.
![image](https://user-images.githubusercontent.com/35483536/56630747-eb3efa00-6684-11e9-92cc-cc819566d347.png)

**Comment by ismcagdas** [comment]
@wabixia this might be related to cookies since all ABP templates uses same cookie name. Could you try this on another browser. The best option is to try with Google Chrome's incognito mode.

**Comment by wabixia** [comment]
@ @ismcagdas Thank you so much, when try with Google Chrome's incognito mode, it works.
