### ISSUE TITLE
Duplicated injection of PermissionManager in UserAppService

### ISSUE THREAD

**Issue by rcyq** [aspnetboilerplate/module-zero-core-template#45]
In ```UserAppService``` which inherits from ``` Abp.Application.Services.ApplicationService```, permisison manager is injected by the parent class ``` Abp.Application.Services.ApplicationService```.

Thus, ```UserAppService``` should not inject permission manager again.

https://github.com/aspnetboilerplate/module-zero-core-template/blob/master/aspnet-core/src/AbpCompanyName.AbpProjectName.Application/Users/UserAppService.cs#L18

**Comment by hikalkan** [comment]
Thank you. You're right, no need to inject second time. We'll fix it.
