### ISSUE TITLE
Duplicate EndProject tags in sln file from template generation system, causes problems with VSCode Intellisense.

### ISSUE THREAD

**Issue by AlanFlaherty** [aspnetboilerplate/module-zero-core-template#46]
Using the Angular2  templates for ".netcore1.1" Or ".net 461" from http://aspnetboilerplate.com

There are Two EndProject Tags on lines 21 & 22. When the mvc project line is removed it looks like  the corresponding EndProject tag is left behind. 

https://github.com/aspnetboilerplate/module-zero-core-template/blob/master/aspnet-core/AbpCompanyName.AbpProjectName.sln#L22

This causes a serious issue with VSCode intellisense preventing the roslyn engine from parsing any code in the solution.

[TestProject.sln.txt](https://github.com/aspnetboilerplate/module-zero-core-template/files/1049312/TestProject.sln.txt)

**Comment by hikalkan** [comment]
Thank you for reporting. We'll fix this in a short time.

**Comment by ismcagdas** [comment]
Fixed on aspnetboilerplate website.
