### ISSUE TITLE
NULLABLE parameters

### ISSUE THREAD

**Issue by vdurante** [aspnetboilerplate/module-zero-core-template#60]
I am unsure if this is an issue that can be solved by you, maybe working around this issue through tweaking ModelBinders.

Here is how to reproduce the issue:

Create an AppService or use an existing one with a method with a nullable argument. In my case, an integer

```c#
[HttpGet]
public void MyMethod(int? myArgument = null)
{

}
```

Use the `refresh.bat` inside the `nswag` folder to generate the services for your new method. The generated service will not have a nullable argument. This is generated code:

```js
anyMethod(myArgument: number): Observable {
        let url_ = this.baseUrl + "/api/services/app/MyAppService/MyMethod?";
        if (myArgument !== undefined)
        
            url_ += "myArgument=" + encodeURIComponent("" + myArgument) + "&"; 
```

As you can see, if `myArgument` is null, it is passed as the string `null` in the path, resulting in `MyMethod` not being able to instantiate `MyArgument` as NULL, causing the following error:

![image](https://user-images.githubusercontent.com/5401232/27148126-85841a64-5115-11e7-84dd-c08cd26a0954.png)

I know this is most likely an nswag issue. I will post the issue there as well.

Thanks in advance.

**Comment by ebicoglu** [comment]
hi

just send the parameter _myArgument_ as **undefined**. So that it'll not be included to the url and will be binded as null in server side.

**Comment by vdurante** [comment]
Exactly what I did. Thank you!

**Comment by ebicoglu** [comment]
u r wellcome
