### ISSUE TITLE
Current user did not login to the application! on Host project

### ISSUE THREAD

**Issue by longhuynh** [aspnetboilerplate/module-zero-core-template#61]
When I execute api on swagger of host project. Could you help me explain how to do on it. 

Thanks

![image](https://user-images.githubusercontent.com/5002046/27154565-180028f6-511b-11e7-9285-4942546b3cdb.png)

**Comment by alirizaadiyahsi** [comment]
Startup template uses token based authentication mechanism, additionally. Startup template includes bearer token authentication infrastructure. So, first you should get a token from `/api/Account/Authenticate`.

Check this for step by step using postman to call APIs:
https://aspnetboilerplate.com/Pages/Documents/Zero/Startup-Template

**Comment by hikalkan** [comment]
@alirizaadiyahsi the link you shared is for ASP.NET MVC 5.x version, not for this template. Correct link should be https://aspnetboilerplate.com/Pages/Documents/Zero/Startup-Template-Core
Thanks.

**Comment by longhuynh** [comment]
I added on-complete.js and config options.InjectOnCompleteJavaScript("/swagger/ui/on-complete.js");

var getCookieValue = function (key) {
    var equalities = document.cookie.split('; ');
    for (var i = 0; i < equalities.length; i++) {
        if (!equalities[i]) {
            continue;
        }

        var splitted = equalities[i].split('=');
        if (splitted.length !== 2) {
            continue;
        }

        if (decodeURIComponent(splitted[0]) === key) {
            return decodeURIComponent(splitted[1] || '');
        }
    }

    return null;
};

var csrfCookie = getCookieValue("Abp.AuthToken");
var header = 'Bearer ' + csrfCookie;
var csrfCookieAuth = new SwaggerClient.ApiKeyAuthorization("Authorization", header, "header");
swaggerUi.api.clientAuthorizations.add("Authorization", csrfCookieAuth);

So. It work on swagger now

**Comment by hikalkan** [comment]
Thank you @longhuynh for sharing your solution. It would be better if we add this into the template by default.

**Comment by hikalkan** [comment]
Hi @longhuynh,

I suppose this solution can not work if you deploy angular and aspnet core (host) applications to different servers. In that case, when you open swagger UI, that browser will not contain ``Abp.AuthToken`` cookie. So, it may work when you run both applications on localhost, but will not work in production. Right?

**Comment by longhuynh** [comment]
I tested that Abp.AuthToken was not contain in swagger. It will contain when we open angular app and login then refresh and use it.
