### ISSUE TITLE
View refresh event bug, repeated call to localise, l in app.component-base.ts.

### ISSUE THREAD

**Issue by AlanFlaherty** [aspnetboilerplate/module-zero-core-template#68]
Add console.log to app.component-base.ts as follows

```
...
    l(key: string, ...args: any[]): string {
        console.log("localise called with key", key);

        let localizedText = this.localization.localize(key, this.localizationSourceName);
...
```

Initially each menu item gets called once. Once the sidebar-user-area.component is loaded it repeatedly calls l('Logout'), when other views are loaded their calls to l('#ItemName#') are added to the repeated calls.

**Comment by hikalkan** [comment]
Haven't investigated the issue yet, but in general Angular may call view (menu in this case) rendering many many times while it seems not necessary normally.

**Comment by ismcagdas** [comment]
@AlanFlaherty I will check this again. I'm not sure about the Vue project but I think it doesn't have this problem at all.
