### ISSUE TITLE
Probably wrong version of tooling in module-zero-core-template

### ISSUE THREAD

**Issue by ASADeveloper** [aspnetboilerplate/module-zero-core-template#9]
The "module-zero-core-template" uses this in project.json:
```
"Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
      "version": "1.0.0-preview2-final",
```

while the "aspnet-core-template" uses this in project.json:
```
"Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
      "version": "1.1.0-preview4-final",
```

Based on other packages which are mostly on .NET Core 1.1 version, I think the module-zero-core-template should aslo use the "1.1.0-preview4-final" version of tooling.

**Comment by hikalkan** [comment]
We'll update it, thanks. But you can easily upgrade for your solution.

**Comment by ASADeveloper** [comment]
Thanks. I've already done that. I just wanted to report it. 
Feel free to close this issue when ever you want.

**Comment by hikalkan** [comment]
resolved with https://github.com/aspnetboilerplate/module-zero-core-template/commit/0a697d6be02fa87647d8a80b9d59525ba7ddde90#diff-57360232d5db9e23177bd1ad2814e788R7
