### ISSUE TITLE
CREATE TENANT FAILS

### ISSUE THREAD

**Issue by Fellow1** [aspnetboilerplate/module-zero-core-template#97]
Hi!
I am using visual studio 2017, working on boilerplate template, I've upgraded nurget packages to 2.2.1 and it gives me a PermissionChecker error, it doesn't pick up abp.authorization reference

**Comment by hikalkan** [comment]
Have you seen breaking changes in https://github.com/aspnetboilerplate/module-zero/releases/tag/v2.1.0 ?

**Comment by Fellow1** [comment]
I understand, but I cant find
#361 Remove TSecurityStampValidator from ServiceCollection.AddAbpIdentity extension method in my project.

**Comment by ismcagdas** [comment]
Hi @Fellow1 , your first problem is related to https://github.com/aspnetboilerplate/module-zero/issues/380.

**Comment by Fellow1** [comment]
when I'm creating a tenant, its throws " Required permissions are not granted. at least one of these permissions must be granted: tenants"

**Comment by Fellow1** [comment]
Hi @ismcagdas 
I've done that.
now it throwing this error "Required Permissions are not granted. at least one of these permissions must be granted: Tenants" when I'm creating a new tenant.

**Comment by ismcagdas** [comment]
I think your problem is related to this issue https://github.com/aspnetboilerplate/aspnetboilerplate/issues/2253.

Can you try to upgrade ABP v2.2.2 ?

**Comment by Fellow1** [comment]
I am using v2.2.2 @ismcagdas

**Comment by ismcagdas** [comment]
Does your tenantAppService class has AbpAuthorize attribute ?

**Comment by Fellow1** [comment]
Yes it has it @ismcagdas

**Comment by ismcagdas** [comment]
How do you use Abp v2.2.2 ? Normally solution does not contain direct reference to ABP nuget package.
We have manually added a reference to ABP v2.2.2 in *.Core project.

Can you try that if you haven't done this.

**Comment by Fellow1** [comment]
Thank you @ismcagdas
