### ISSUE TITLE
"ng build" fails

### ISSUE THREAD

**Issue by halllo** [aspnetboilerplate/module-zero-core-template#99]
I just forked and cloned this repository (https://github.com/halllo/module-zero-core-template) and tried to build the client side using `npm run ng build`.
Unfortunately it does not build. It says it cannot resolve the `@shared/shared.module` which is strange because the paths seem to be configured correctly in `tsconfig.json` (https://github.com/halllo/module-zero-core-template/blob/master/angular/src/tsconfig.json#L20). I did not change anything.

I get the following error:
![ngbuildfailure](https://user-images.githubusercontent.com/168058/29224648-8366acea-7ecb-11e7-8a6d-ff745dd48703.png)

**Comment by hikalkan** [comment]
Have you ``run npm install`` or ``yarn`` (better) before?

**Comment by halllo** [comment]
`npm install`

**Comment by fileman** [comment]
I dont know if is better, but with npm install, "npm start" fail at "chunk optimization", while with yarn "npm start" success "webpack: Compiled successfully".

**Comment by iyhammad** [comment]
It's an issue with angular/cli you may update the angular/cli to 1.3.0-rc.5
https://github.com/angular/angular-cli/issues/7341

**Comment by ismcagdas** [comment]
there is a yarn.lock file in project and when you use yarn to install dependencies, it install the ones that we defined in project while we are developing the template.

But "npm install" installs latest minor version and probably some of the updated packages causes such problems. We tried to use npm-shrinkwrap (similar to yarn.lock) but it has some problems as well.

So, it is better to use yarn :).

**Comment by FabriDamazio** [comment]
I can confirm that dont work with npm and works with yarn.
I had the same issue and using yarn install then yarn run start solved the issue.

If yarn is recommended i suggest change this documentation to warning about npm issues.

**Comment by ismcagdas** [comment]
Hi @FabriDamazio,
changed "npm install" to "yarn" in documentation https://aspnetboilerplate.com/Pages/Documents/Zero/Startup-Template-Angular#angular-application.

Thanks for your suggestion.

**Comment by SpiraMira** [comment]
fyi still an issue with @angular/cli 1.4.betas. 
As reported above 1.3.0.-rc.5 seems to be the last version that works.

**Comment by ismcagdas** [comment]
Hi @SpiraMira,

We haven't upgraded angular-cli yet, so you should use the version that we used in templates.
If you want to upgrade it before we do, you need to fix the problems by yourself.

**Comment by SpiraMira** [comment]
Of course no suggestion to do otherwise. 

Just curious. An FYI given that you distribute ^1.2.4 which yarns to 1.3.1 which doesn't seem to work for me.  Same thing for  ~1.2.4 which currently yarns to 1.2.8. 

Drove me a little nuts for a while so I removed the semver ranges to 1.2.4. Any idea why this is happening?
